package buckgen

import (
	"encoding/json"
	"os"
)

// Config represents buckgen configuration (compatible with gobuckify.json)
type Config struct {
	Buck      BuckConfig `json:"buck"`
	Platforms []Platform `json:"platforms"`
}

type BuckConfig struct {
	Preambule             string `json:"preambule"` // Note: gobuckify spells it this way
	GoLibraryRule         string `json:"go_library_rule"`
	DepsTargetLabelPrefix string `json:"deps_target_label_prefix"`
	DepsAttr              string `json:"deps_attr"`
	OSConstraintPrefix    string `json:"os_constraint_prefix"`
	ArchConstraintPrefix  string `json:"arch_constraint_prefix"`
	BuildfileName         string `json:"buildfile_name"`
}

type Platform struct {
	GoOS     string `json:"go_os"`
	GoArch   string `json:"go_arch"`
	BuckOS   string `json:"buck_os"`
	BuckArch string `json:"buck_arch"`
}

// DefaultConfig returns sensible defaults
func DefaultConfig() *Config {
	return &Config{
		Buck: BuckConfig{
			Preambule:             "# Auto-generated by turnkey buckgen",
			GoLibraryRule:         "go_library",
			DepsTargetLabelPrefix: "godeps//",
			DepsAttr:              "deps",
			OSConstraintPrefix:    "config//os:",
			ArchConstraintPrefix:  "config//cpu:",
			BuildfileName:         "rules.star",
		},
		Platforms: []Platform{
			{GoOS: "linux", GoArch: "amd64", BuckOS: "linux", BuckArch: "x86_64"},
			{GoOS: "linux", GoArch: "arm64", BuckOS: "linux", BuckArch: "aarch64"},
			{GoOS: "darwin", GoArch: "amd64", BuckOS: "macos", BuckArch: "x86_64"},
			{GoOS: "darwin", GoArch: "arm64", BuckOS: "macos", BuckArch: "aarch64"},
		},
	}
}

// LoadConfig loads config from gobuckify.json
func LoadConfig(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var cfg Config
	if err := json.Unmarshal(data, &cfg); err != nil {
		return nil, err
	}
	return &cfg, nil
}
