{
  description = "Turnkey toolchain management for Nix flakes";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-parts.url = "github:hercules-ci/flake-parts";
    devenv.url = "github:cachix/devenv";

    # Beads - distributed git-backed graph issue tracker for AI agents
    beads = {
      url = "github:steveyegge/beads/v0.46.0";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Beads Viewer - visualization tool for beads graphs
    beads_viewer = {
      url = "github:Dicklesworthstone/beads_viewer/v0.12.1";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Jujutsu - Git-compatible VCS
    jj = {
      url = "github:jj-vcs/jj/v0.37.0";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    inputs@{
      self,
      flake-parts,
      nixpkgs,
      ...
    }:
    flake-parts.lib.mkFlake { inherit inputs; } {
      # Export the turnkey flake-parts module
      flake.flakeModules = {
        turnkey = ./nix/flake-parts/turnkey;
      };

      # Export the turnkey devenv module separately
      flake.devenvModules = {
        turnkey = ./nix/devenv/turnkey;
      };

      # Use the module ourselves as a working example
      imports = [
        inputs.devenv.flakeModule
        ./nix/flake-parts/turnkey
      ];

      systems = [
        "x86_64-linux"
        "aarch64-linux"
        "x86_64-darwin"
        "aarch64-darwin"
      ];

      perSystem =
        {
          config,
          pkgs,
          lib,
          system,
          ...
        }:
        {
          # Export tools as packages
          packages.godeps-gen = import ./nix/packages/godeps-gen.nix { inherit pkgs lib; };
          packages.gobuckify = import ./nix/packages/gobuckify.nix { inherit pkgs lib; };

          # Configure turnkey to use our local toolchain files
          # Each file creates a corresponding shell
          turnkey.toolchains = {
            enable = true;
            declarationFiles = {
              default = ./toolchain.toml; # Creates devShells.default with buck2 + nix + beads + go
              ci = ./toolchain.ci.toml; # Creates devShells.ci with just nix
            };
            # Extend the default registry with packages from flake inputs
            registry = {
              buck2 = pkgs.buck2;
              nix = pkgs.nix;
              beads = inputs.beads.packages.${system}.default;
              beads_viewer = inputs.beads_viewer.packages.${system}.default;
              jj = inputs.jj.packages.${system}.default;
              # Language toolchains for Buck2 integration
              go = pkgs.go;
              python = pkgs.python3;
              cxx = pkgs.stdenv.cc;
              clang = pkgs.clang;
              # Internal tools
              godeps-gen = config.packages.godeps-gen;
              gobuckify = config.packages.gobuckify;
            };
            # Enable Buck2 toolchain generation
            buck2 = {
              enable = true;
              prelude.strategy = "bundled";
              goDepsFile = ./go-deps.toml; # Auto-generated by .envrc, tracked in git
              generateOnShellEntry = false; # .envrc handles generation
            };
          };
        };
    };
}
