//! A vendored crate's rules.star, as text.
//!
//! The layout is the merged cell's (src/python/buck's generate_buck_file),
//! byte for byte, so a crate's rules.star doesn't change with the generator
//! that writes it.

use crate::fixup::{NativeLibrary, Split};
use std::collections::BTreeMap;

/// Everything a crate's rules.star says
pub struct Crate {
    pub name: String,
    pub edition: String,
    pub crate_root: Option<String>,
    pub proc_macro: bool,
    pub features: Split<Vec<String>>,
    pub deps: Split<Vec<String>>,
    /// Renamed deps: the name the crate's code uses -> the target
    pub named_deps: Split<Vec<(String, String)>>,
    pub env: Split<BTreeMap<String, String>>,
    pub rustc_flags: Split<Vec<String>>,
    pub native_libraries: Vec<NativeLibrary>,
    /// The combined config_setting of the platform the crate is built on:
    /// its native libraries exist only there
    pub host_key: String,
}

impl Crate {
    /// The targets the rules.star defines: the library, and each native
    /// library's file and library
    pub fn target_names(&self) -> Vec<String> {
        let mut names = vec![self.name.clone()];
        for lib in &self.native_libraries {
            names.push(format!("{}_file", lib.lib_name));
            names.push(lib.lib_name.clone());
        }
        names.sort();
        names
    }

    pub fn render(&self) -> String {
        let mut rules = vec!["rust_library"];
        let mut native_content = Vec::new();
        let mut native_deps = Vec::new();
        let mut native_flags = Vec::new();
        for lib in &self.native_libraries {
            for rule in ["prebuilt_cxx_library", "export_file"] {
                if !rules.contains(&rule) {
                    rules.push(rule);
                }
            }
            native_content.push(native_library(lib));
            native_deps.push(format!(":{}", lib.lib_name));
            native_flags.push(format!("-Lnative={}", lib.link_search_path));
        }

        let rules = rules
            .iter()
            .map(|r| format!("\"{r}\""))
            .collect::<Vec<_>>()
            .join(", ");
        let mut lines = vec![
            "# Auto-generated by turnkey rust-deps-cell".to_string(),
            format!("load(\"@prelude//:rules.bzl\", {rules})"),
            String::new(),
        ];
        lines.extend(native_content);
        lines.extend([
            "rust_library(".to_string(),
            format!("    name = \"{}\",", self.name),
            "    srcs = glob([\"**/*\"]),".to_string(),
            format!("    edition = \"{}\",", self.edition),
        ]);
        if self.proc_macro {
            lines.push("    proc_macro = True,".to_string());
        }

        let quoted = |s: &String| format!("\"{s}\"");
        let features = &self.features;
        if !features.by_platform.is_empty() {
            let mut parts = Vec::new();
            if !features.common.is_empty() {
                parts.push(list_literal(&sorted(&features.common), quoted));
            }
            parts.push(format_select(&features.by_platform, quoted, true));
            attr(&mut lines, "features", &parts, "+");
        } else if !features.common.is_empty() {
            lines.push("    features = [".to_string());
            for feature in sorted(&features.common) {
                lines.push(format!("        \"{feature}\","));
            }
            lines.push("    ],".to_string());
        }

        if let Some(root) = &self.crate_root {
            lines.push(format!("    crate_root = \"{root}\","));
        }

        // Deps: common, then per platform, then the host's native libraries
        let mut deps = Vec::new();
        if !self.deps.common.is_empty() {
            deps.push(list_literal(&sorted(&self.deps.common), quoted));
        }
        if !self.deps.by_platform.is_empty() {
            deps.push(format_select(&self.deps.by_platform, quoted, true));
        }
        if !native_deps.is_empty() {
            deps.push(host_select(&self.host_key, &native_deps, quoted));
        }
        attr(&mut lines, "deps", &deps, "+");

        let mut named = Vec::new();
        if !self.named_deps.common.is_empty() {
            let common: BTreeMap<String, String> = self.named_deps.common.iter().cloned().collect();
            named.push(dict_literal(&common));
        }
        if !self.named_deps.by_platform.is_empty() {
            let by_platform: BTreeMap<String, BTreeMap<String, String>> = self
                .named_deps
                .by_platform
                .iter()
                .map(|(k, v)| (k.clone(), v.iter().cloned().collect()))
                .collect();
            named.push(format_dict_select(&by_platform, false));
        }
        attr(&mut lines, "named_deps", &named, "|");

        // Cargo's and the fixup's environment variables
        let mut envs = Vec::new();
        if !self.env.common.is_empty() {
            envs.push(dict_literal(&self.env.common));
        }
        if !self.env.by_platform.is_empty() {
            envs.push(format_dict_select(&self.env.by_platform, true));
        }
        attr(&mut lines, "env", &envs, "|");

        // Rustc flags, kept in order: they come in pairs
        let flag = |s: &String| format!("\"{}\"", escape(s));
        let mut flags = Vec::new();
        if !self.rustc_flags.common.is_empty() {
            flags.push(list_literal(&self.rustc_flags.common, flag));
        }
        if !self.rustc_flags.by_platform.is_empty() {
            flags.push(format_select(&self.rustc_flags.by_platform, flag, false));
        }
        if !native_flags.is_empty() {
            flags.push(host_select(&self.host_key, &native_flags, flag));
        }
        attr(&mut lines, "rustc_flags", &flags, "+");

        lines.extend([
            "    visibility = [\"PUBLIC\"],".to_string(),
            ")".to_string(),
            String::new(),
        ]);
        // The Python generator printed it, adding a newline
        lines.join("\n") + "\n"
    }
}

fn sorted(items: &[String]) -> Vec<String> {
    let mut items = items.to_vec();
    items.sort();
    items.dedup();
    items
}

/// A string's content, escaped for a Starlark double-quoted literal on one
/// line
fn escape(value: &str) -> String {
    value
        .replace(['\n', '\r'], " ")
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
}

/// A multi-line list literal, its first line unindented (it follows
/// `name = `)
fn list_literal(items: &[String], format_item: impl Fn(&String) -> String) -> String {
    let mut lines = vec!["[".to_string()];
    lines.extend(items.iter().map(|i| format!("        {},", format_item(i))));
    lines.push("    ]".to_string());
    lines.join("\n")
}

/// A multi-line dict literal of strings, its first line unindented
fn dict_literal(items: &BTreeMap<String, String>) -> String {
    let mut lines = vec!["{".to_string()];
    lines.extend(
        items
            .iter()
            .map(|(k, v)| format!("        \"{}\": \"{}\",", escape(k), escape(v))),
    );
    lines.push("    }".to_string());
    lines.join("\n")
}

/// A select() of lists, one branch per key. Every platform matches a key,
/// even with nothing to add: there's no default branch, so an unlisted
/// platform fails instead of missing values.
fn format_select(
    by_platform: &BTreeMap<String, Vec<String>>,
    format_item: impl Fn(&String) -> String,
    dedup_sort: bool,
) -> String {
    let mut lines = vec!["    select({".to_string()];
    for (key, items) in by_platform {
        if items.is_empty() {
            lines.push(format!("        \"{key}\": [],"));
            continue;
        }
        lines.push(format!("        \"{key}\": ["));
        let ordered = if dedup_sort {
            sorted(items)
        } else {
            items.clone()
        };
        for item in &ordered {
            lines.push(format!("            {},", format_item(item)));
        }
        lines.push("        ],".to_string());
    }
    lines.push("    })".to_string());
    lines.join("\n")
}

/// A select() of dicts: named deps as they are, env entries escaped
fn format_dict_select(
    by_platform: &BTreeMap<String, BTreeMap<String, String>>,
    escaped: bool,
) -> String {
    let text = |s: &String| if escaped { escape(s) } else { s.clone() };
    let mut lines = vec!["    select({".to_string()];
    for (key, items) in by_platform {
        if items.is_empty() {
            lines.push(format!("        \"{key}\": {{}},"));
            continue;
        }
        lines.push(format!("        \"{key}\": {{"));
        for (k, v) in items {
            lines.push(format!("            \"{}\": \"{}\",", text(k), text(v)));
        }
        lines.push("        },".to_string());
    }
    lines.push("    })".to_string());
    lines.join("\n")
}

/// A select() with only the host platform's branch: what a fixup builds
/// natively exists only there, so configuring the crate for any other
/// platform fails ("no condition matched") instead of linking a missing
/// library
fn host_select(
    host_key: &str,
    items: &[String],
    format_item: impl Fn(&String) -> String,
) -> String {
    let mut lines = vec![
        "    select({".to_string(),
        format!("        \"{host_key}\": ["),
    ];
    lines.extend(
        items
            .iter()
            .map(|i| format!("            {},", format_item(i))),
    );
    lines.extend(["        ],".to_string(), "    })".to_string()]);
    lines.join("\n")
}

/// Append `name = part1 <op> part2 ...,` when there are parts
fn attr(lines: &mut Vec<String>, name: &str, parts: &[String], operator: &str) {
    if parts.is_empty() {
        return;
    }
    let joined = parts
        .iter()
        .map(|p| p.trim_start())
        .collect::<Vec<_>>()
        .join(&format!(" {operator}\n    "));
    lines.push(format!("    {name} = {joined},"));
}

/// A native library's export_file and prebuilt_cxx_library
fn native_library(lib: &NativeLibrary) -> String {
    [
        "# Native library pre-compiled in Nix".to_string(),
        "export_file(".to_string(),
        format!("    name = \"{}_file\",", lib.lib_name),
        format!("    src = \"{}\",", lib.static_lib_path),
        "    visibility = [\"PUBLIC\"],".to_string(),
        ")".to_string(),
        String::new(),
        "prebuilt_cxx_library(".to_string(),
        format!("    name = \"{}\",", lib.lib_name),
        format!("    static_lib = \":{}_file\",", lib.lib_name),
        "    link_whole = True,".to_string(),
        "    preferred_linkage = \"static\",".to_string(),
        "    visibility = [\"PUBLIC\"],".to_string(),
        ")".to_string(),
        String::new(),
    ]
    .join("\n")
}
