//! deps-gen-kit: what turnkey's deps generators share
//!
//! A deps generator reads one language's lock file and writes the deps file
//! (rust-deps.toml, python-deps.toml, ...) its deps cell is built from. Only
//! the lock file parsing and the record type are the generator's own; this
//! module holds the rest:
//!
//! - the flags every generator takes: [`OutputArgs`] and [`PrefetchArgs`],
//!   flattened into its clap `Args`;
//! - the [`Prefetcher`] seam, with [`NixPrefetcher`] as the real adapter,
//!   on turnkey's prefetch cache, and [`MemoryPrefetcher`] for tests;
//! - [`OutputArgs::write`], which writes the common header and the
//!   serde-serialized record.
//!
//! Generators run through `tk sync`, from the sync rules turnkey generates
//! (nix/buck2/languages.nix), which read the deps file from stdout.

use anyhow::{Context, Result, anyhow};
use prefetch_cache::{PrefetchCache, nix_prefetch_url};
use serde::Serialize;
use std::collections::BTreeMap;
use std::io::Write;
use std::path::PathBuf;

/// Where a generator writes its deps file
#[derive(clap::Args, Debug, Clone, Default)]
pub struct OutputArgs {
    /// Output file path (default: stdout)
    #[arg(short = 'o', long)]
    pub output: Option<PathBuf>,
}

impl OutputArgs {
    /// Write `doc` with the common header to the output file or stdout
    ///
    /// `generator` is the generator's name and `source` the file it read,
    /// both for the header.
    pub fn write(&self, generator: &str, source: &str, doc: &impl Serialize) -> Result<()> {
        self.write_text(&render(generator, source, doc)?)
    }

    /// Write a deps file already rendered (`header` and its TOML) to the
    /// output file or stdout
    pub fn write_text(&self, content: &str) -> Result<()> {
        match &self.output {
            Some(path) => {
                std::fs::write(path, content)
                    .with_context(|| format!("Failed to write {}", path.display()))?;
                eprintln!("Wrote {}", path.display());
            }
            None => std::io::stdout()
                .write_all(content.as_bytes())
                .context("Failed to write to stdout")?,
        }
        Ok(())
    }
}

/// A deps file: the common header, then `doc` as TOML
pub fn render(generator: &str, source: &str, doc: &impl Serialize) -> Result<String> {
    let body = toml::to_string_pretty(doc).context("Failed to serialize to TOML")?;
    Ok(format!("{}{body}", header(generator, source)))
}

/// The common header of a deps file, up to its TOML
pub fn header(generator: &str, source: &str) -> String {
    format!(
        "# Auto-generated by {generator} from {source}. Do not edit.\n\
         # To regenerate: tk sync\n\
         \n"
    )
}

/// Whether and how a generator prefetches the Nix hashes its deps cell
/// fetches with
///
/// Prefetching is on by default: without it, a deps file has hashes Nix
/// can't fetch with.
#[derive(clap::Args, Debug, Clone, Default)]
pub struct PrefetchArgs {
    /// Skip prefetching (the deps file gets placeholder or missing hashes)
    #[arg(long)]
    pub no_prefetch: bool,

    /// Always fetch from the network, bypassing turnkey's prefetch cache
    #[arg(long, conflicts_with = "no_prefetch")]
    pub no_cache: bool,
}

impl PrefetchArgs {
    /// The prefetcher these flags ask for, or none with --no-prefetch
    pub fn prefetcher(&self) -> Option<NixPrefetcher> {
        (!self.no_prefetch).then(|| NixPrefetcher::new(!self.no_cache))
    }
}

/// The seam through which a generator gets the Nix hash of a URL
pub trait Prefetcher {
    /// Nix SRI hash of a URL, of its unpacked contents when `unpack` is set
    /// (as Nix's fetchzip hashes it)
    fn prefetch(&mut self, url: &str, unpack: bool) -> Result<String>;
}

/// The real adapter: turnkey's prefetch cache, falling back to
/// `nix-prefetch-url`
pub struct NixPrefetcher {
    cache: Option<PrefetchCache>,
}

impl NixPrefetcher {
    /// A prefetcher that reads and fills the prefetch cache when
    /// `use_cache` is set and the cache can be opened
    pub fn new(use_cache: bool) -> Self {
        let cache = use_cache
            .then(|| match PrefetchCache::new() {
                Ok(cache) => Some(cache),
                Err(e) => {
                    eprintln!("warning: prefetch cache unavailable: {}", e);
                    None
                }
            })
            .flatten();
        Self { cache }
    }
}

impl Prefetcher for NixPrefetcher {
    fn prefetch(&mut self, url: &str, unpack: bool) -> Result<String> {
        match &mut self.cache {
            Some(cache) => Ok(cache.prefetch(url, unpack)?.hash),
            None => nix_prefetch_url(url, unpack),
        }
    }
}

/// An in-memory adapter for tests: answers from a fixed table and records
/// every call
#[derive(Debug, Default)]
pub struct MemoryPrefetcher {
    hashes: BTreeMap<(String, bool), String>,
    /// Every URL asked for, with its `unpack`, in order
    pub calls: Vec<(String, bool)>,
}

impl MemoryPrefetcher {
    /// This prefetcher, answering `hash` for `url` with `unpack`
    pub fn with(mut self, url: &str, unpack: bool, hash: &str) -> Self {
        self.hashes
            .insert((url.to_string(), unpack), hash.to_string());
        self
    }
}

impl Prefetcher for MemoryPrefetcher {
    fn prefetch(&mut self, url: &str, unpack: bool) -> Result<String> {
        self.calls.push((url.to_string(), unpack));
        self.hashes
            .get(&(url.to_string(), unpack))
            .cloned()
            .ok_or_else(|| anyhow!("no hash for {} (unpack={})", url, unpack))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::Parser;

    #[derive(Parser, Debug)]
    struct Args {
        #[command(flatten)]
        output: OutputArgs,
        #[command(flatten)]
        prefetch: PrefetchArgs,
    }

    #[test]
    fn prefetching_is_on_by_default() {
        let args = Args::try_parse_from(["gen"]).unwrap();
        assert!(!args.prefetch.no_prefetch);
        assert!(args.output.output.is_none());

        let args = Args::try_parse_from(["gen", "--no-prefetch", "-o", "x.toml"]).unwrap();
        assert!(args.prefetch.prefetcher().is_none());
        assert_eq!(args.output.output, Some(PathBuf::from("x.toml")));

        // The old opt-in flag is gone
        assert!(Args::try_parse_from(["gen", "--prefetch"]).is_err());
        assert!(Args::try_parse_from(["gen", "--no-cache", "--no-prefetch"]).is_err());
    }

    #[test]
    fn memory_prefetcher_answers_and_records() {
        let mut p = MemoryPrefetcher::default().with("https://a", true, "sha256-a");
        assert_eq!(p.prefetch("https://a", true).unwrap(), "sha256-a");
        assert!(p.prefetch("https://a", false).is_err());
        assert_eq!(
            p.calls,
            vec![
                ("https://a".to_string(), true),
                ("https://a".to_string(), false)
            ]
        );
    }

    #[test]
    fn render_writes_header_then_toml() {
        #[derive(Serialize)]
        struct Doc {
            schema_version: u32,
            deps: BTreeMap<String, Dep>,
        }
        #[derive(Serialize)]
        struct Dep {
            version: String,
        }

        let doc = Doc {
            schema_version: 1,
            deps: BTreeMap::from([(
                "a@1.0".to_string(),
                Dep {
                    version: "1.0".to_string(),
                },
            )]),
        };
        let out = render("x-gen", "x.lock", &doc).unwrap();
        assert!(
            out.starts_with(
                "# Auto-generated by x-gen from x.lock. Do not edit.\n# To regenerate: tk sync\n\n"
            ),
            "{out}"
        );
        let parsed: toml::Value = toml::from_str(&out).unwrap();
        assert_eq!(parsed["deps"]["a@1.0"]["version"].as_str(), Some("1.0"));
    }
}
