// godeps-gen generates go-deps.toml from go.mod and go.sum files.
//
// This tool parses Go module files and outputs dependency declarations
// in the format expected by turnkey's go-deps-cell.nix.
//
// Usage:
//
//	godeps-gen --go-mod go.mod --go-sum go.sum > go-deps.toml
package main

import (
	"bufio"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"sort"
	"strings"

	"golang.org/x/mod/modfile"
)

// Dependency represents a Go module dependency
type Dependency struct {
	ImportPath string
	Version    string
	Indirect   bool   // true if this is an indirect (transitive) dependency
	Hash       string // h1: hash from go.sum (for reference)
	NixHash    string // Nix SRI hash from nix-prefetch-github
}

func main() {
	goModPath := flag.String("go-mod", "go.mod", "path to go.mod file")
	goSumPath := flag.String("go-sum", "go.sum", "path to go.sum file")
	prefetch := flag.Bool("prefetch", false, "fetch Nix hashes using nix-prefetch-github (requires nix)")
	includeIndirect := flag.Bool("indirect", true, "include indirect (transitive) dependencies")
	flag.Parse()

	// Parse go.mod for dependencies
	deps, err := parseGoMod(*goModPath, *includeIndirect)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error parsing go.mod: %v\n", err)
		os.Exit(1)
	}

	// Parse go.sum for hashes (for reference)
	hashes, err := parseGoSum(*goSumPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error parsing go.sum: %v\n", err)
		os.Exit(1)
	}

	// Merge go.sum hashes into deps (for reference comments)
	for i, dep := range deps {
		key := dep.ImportPath + " " + dep.Version
		if hash, ok := hashes[key]; ok {
			deps[i].Hash = hash
		}
	}

	// Prefetch Nix hashes if requested
	if *prefetch {
		for i, dep := range deps {
			nixHash, err := prefetchGitHub(dep.ImportPath, dep.Version)
			if err != nil {
				fmt.Fprintf(os.Stderr, "warning: failed to prefetch %s: %v\n", dep.ImportPath, err)
				continue
			}
			deps[i].NixHash = nixHash
		}
	}

	// Output TOML
	if err := outputTOML(deps, *prefetch); err != nil {
		fmt.Fprintf(os.Stderr, "error writing output: %v\n", err)
		os.Exit(1)
	}
}

// parseGoMod extracts require directives from go.mod using the official Go module parser.
func parseGoMod(path string, includeIndirect bool) ([]Dependency, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading go.mod: %w", err)
	}

	f, err := modfile.Parse(path, data, nil)
	if err != nil {
		return nil, fmt.Errorf("parsing go.mod: %w", err)
	}

	var deps []Dependency
	for _, req := range f.Require {
		// Skip indirect dependencies if not requested
		if req.Indirect && !includeIndirect {
			continue
		}

		deps = append(deps, Dependency{
			ImportPath: req.Mod.Path,
			Version:    req.Mod.Version,
			Indirect:   req.Indirect,
		})
	}

	// Sort by import path for consistent output
	sort.Slice(deps, func(i, j int) bool {
		return deps[i].ImportPath < deps[j].ImportPath
	})

	return deps, nil
}

// parseGoSum extracts h1: hashes from go.sum
func parseGoSum(path string) (map[string]string, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	hashes := make(map[string]string)
	scanner := bufio.NewScanner(file)

	// go.sum format: github.com/foo/bar v1.0.0 h1:abc123...
	// We want the h1: hash, not the /go.mod hash
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.Fields(line)
		if len(parts) != 3 {
			continue
		}

		importPath := parts[0]
		version := parts[1]
		hash := parts[2]

		// Skip go.mod hashes (we want source hashes)
		if strings.HasSuffix(version, "/go.mod") {
			continue
		}

		// Only take h1: hashes
		if strings.HasPrefix(hash, "h1:") {
			key := importPath + " " + version
			hashes[key] = hash
		}
	}

	return hashes, scanner.Err()
}

// outputTOML writes dependencies in go-deps.toml format
func outputTOML(deps []Dependency, prefetched bool) error {
	fmt.Println("# Auto-generated by godeps-gen")
	fmt.Println("# Source: go.mod + go.sum")
	fmt.Println("#")
	if !prefetched {
		fmt.Println("# IMPORTANT: Nix hashes must be obtained separately.")
		fmt.Println("# Run with --prefetch to automatically fetch hashes, or manually run:")
		fmt.Println("# nix-prefetch-github --owner OWNER --repo REPO --rev VERSION")
		fmt.Println("#")
	}
	fmt.Println("# To regenerate: godeps-gen --go-mod go.mod --go-sum go.sum --prefetch > go-deps.toml")
	fmt.Println()

	for _, dep := range deps {
		fmt.Printf("[deps.\"%s\"]\n", dep.ImportPath)
		fmt.Printf("version = \"%s\"\n", dep.Version)
		if dep.NixHash != "" {
			fmt.Printf("hash = \"%s\"\n", dep.NixHash)
		} else {
			fmt.Printf("hash = \"\"%s\n", formatHashComment(dep.Hash))
		}
		if dep.Indirect {
			fmt.Println("indirect = true")
		}
		fmt.Println()
	}

	return nil
}

// prefetchGitHub uses nix-prefetch-github to get the Nix hash for a GitHub repo
func prefetchGitHub(importPath, version string) (string, error) {
	// Parse GitHub import path: github.com/owner/repo
	parts := strings.Split(importPath, "/")
	if len(parts) < 3 || parts[0] != "github.com" {
		return "", fmt.Errorf("not a github.com import path: %s", importPath)
	}
	owner := parts[1]
	repo := parts[2]

	fmt.Fprintf(os.Stderr, "prefetching %s/%s@%s...\n", owner, repo, version)

	// nix-prefetch-github owner repo --rev version --json
	cmd := exec.Command("nix-prefetch-github", owner, repo, "--rev", version, "--json")
	output, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("nix-prefetch-github failed: %w", err)
	}

	// Parse JSON output
	var result struct {
		Hash string `json:"hash"`
	}
	if err := json.Unmarshal(output, &result); err != nil {
		return "", fmt.Errorf("failed to parse nix-prefetch-github output: %w", err)
	}

	return result.Hash, nil
}

// goHashToNix notes that the Go h1: hash cannot be directly converted to Nix hash.
//
// The h1: hash is a hash of the Go module zip contents (from proxy.golang.org),
// while Nix needs a hash of the fetchFromGitHub output (git archive contents).
// These are different formats and cannot be directly converted.
//
// Options for getting the correct Nix hash:
// 1. Run: nix-prefetch-github --owner X --repo Y --rev vZ.Z.Z
// 2. Use fetchzip with Go module proxy (preserves h1: hash semantics)
// 3. Let Nix fail once and copy the expected hash from the error
//
// For now, we output the h1: hash as a comment for reference.
func goHashToNix(goHash string) string {
	// Cannot directly convert - return empty and add comment
	return ""
}

// formatHashComment returns the h1: hash as a reference comment
func formatHashComment(goHash string) string {
	if goHash != "" {
		return fmt.Sprintf(" # go.sum %s - run nix-prefetch-github to get correct hash", goHash)
	}
	return ""
}
