[package]
name = "turnkey-test-runner"
version = "0.1.0"
edition.workspace = true
description = "Turnkey's buck2 test runner, with test result caching"

[dependencies]
anyhow.workspace = true
clap.workspace = true
futures-util.workspace = true
hyper-util.workspace = true
tokio.workspace = true
tower.workspace = true
prost.workspace = true
prost-types.workspace = true
tonic.workspace = true
tonic-prost.workspace = true
