package godeps

import (
	"fmt"
	"io"
)

// OutputOptions configures the TOML output format.
type OutputOptions struct {
	// IncludeHeader adds the auto-generated header comment.
	IncludeHeader bool

	// IncludeHashWarning adds a warning when hashes are missing.
	IncludeHashWarning bool

	// IncludeRegenerateHint adds the regeneration command hint.
	IncludeRegenerateHint bool
}

// DefaultOutputOptions returns the default output options.
func DefaultOutputOptions() OutputOptions {
	return OutputOptions{
		IncludeHeader:         true,
		IncludeHashWarning:    true,
		IncludeRegenerateHint: true,
	}
}

// WriteTOML writes dependencies in go-deps.toml format to the given writer.
func WriteTOML(w io.Writer, deps []Dependency, opts OutputOptions) error {
	return WriteDepsFile(w, DepsFile{Deps: deps}, opts)
}

// DepsFile is what go-deps.toml holds.
type DepsFile struct {
	// Deps are the third-party modules the godeps cell fetches.
	Deps []Dependency

	// Sources are the files the deps were resolved from (Workspace's
	// Sources): the Go sync rule's target_sources, so a change to any of
	// them makes go-deps.toml stale. Omitted when empty.
	Sources []string

	// Members are the workspace's modules, the first-party ones rules sync
	// maps imports to. Omitted when empty.
	Members []Member
}

// WriteDepsFile writes a go-deps.toml.
func WriteDepsFile(w io.Writer, file DepsFile, opts OutputOptions) error {
	deps := file.Deps

	// Check if any deps are missing hashes
	hasMissingHashes := false
	for _, dep := range deps {
		if dep.NixHash == "" {
			hasMissingHashes = true
			break
		}
	}

	// Write header
	if opts.IncludeHeader {
		_, _ = fmt.Fprintln(w, "# Auto-generated by godeps-gen")
		_, _ = fmt.Fprintln(w, "# Source: the files listed under sources")
		_, _ = fmt.Fprintln(w, "#")
		_, _ = fmt.Fprintln(w, "# Key format: deps.\"import-path@version\" to support multiple versions")
		_, _ = fmt.Fprintln(w, "#")
	}

	if opts.IncludeHashWarning && hasMissingHashes {
		_, _ = fmt.Fprintln(w, "# IMPORTANT: Nix hashes must be obtained separately.")
		_, _ = fmt.Fprintln(w, "# Prefetching (on unless --no-prefetch) fetches them; or manually run:")
		_, _ = fmt.Fprintln(w, "# nix-prefetch-cached --unpack https://proxy.golang.org/MODULE/@v/VERSION.zip")
		_, _ = fmt.Fprintln(w, "#")
	}

	if opts.IncludeRegenerateHint {
		_, _ = fmt.Fprintln(w, "# To regenerate: tk sync")
		_, _ = fmt.Fprintln(w)
	}

	// Write schema version for forward compatibility
	// v2: versioned keys like [deps."path@version"] with import_path field
	_, _ = fmt.Fprintln(w, "schema_version = 2")
	_, _ = fmt.Fprintln(w)

	if len(file.Sources) > 0 {
		_, _ = fmt.Fprintln(w, "sources = [")
		for _, source := range file.Sources {
			_, _ = fmt.Fprintf(w, "    %q,\n", source)
		}
		_, _ = fmt.Fprintln(w, "]")
		_, _ = fmt.Fprintln(w)
	}

	// Write each dependency
	for _, dep := range deps {
		if err := writeDependency(w, dep); err != nil {
			return err
		}
	}

	// Write the workspace members, by module path
	for _, m := range file.Members {
		_, _ = fmt.Fprintf(w, "[members.%q]\n", m.Path)
		_, _ = fmt.Fprintf(w, "dir = %q\n", m.Dir)
		_, _ = fmt.Fprintln(w)
	}

	return nil
}

// writeDependency writes a single dependency entry in TOML format.
// Uses versioned key format: [deps."import-path@version"]
func writeDependency(w io.Writer, dep Dependency) error {
	// Versioned key format (schema v2)
	_, _ = fmt.Fprintf(w, "[deps.\"%s@%s\"]\n", dep.ImportPath, dep.Version)
	_, _ = fmt.Fprintf(w, "import_path = \"%s\"\n", dep.ImportPath)

	// Include fetch_path when it differs from import_path (external fork replace)
	if dep.FetchPath != "" && dep.FetchPath != dep.ImportPath {
		_, _ = fmt.Fprintf(w, "fetch_path = \"%s\"\n", dep.FetchPath)
	}

	_, _ = fmt.Fprintf(w, "version = \"%s\"\n", dep.Version)

	if dep.NixHash != "" {
		_, _ = fmt.Fprintf(w, "hash = \"%s\"\n", dep.NixHash)
	} else {
		// Empty hash with go.sum hash as comment for reference
		_, _ = fmt.Fprintf(w, "hash = \"\"%s\n", formatHashComment(dep.GoSumHash))
	}

	if dep.Indirect {
		_, _ = fmt.Fprintln(w, "indirect = true")
	}

	_, _ = fmt.Fprintln(w)
	return nil
}

// formatHashComment returns the go.sum hash as a reference comment.
func formatHashComment(goSumHash string) string {
	if goSumHash != "" {
		return fmt.Sprintf(" # go.sum %s - run godeps-gen without --no-prefetch to get correct hash", goSumHash)
	}
	return ""
}
