package godeps

import (
	"bytes"
	"strings"
	"testing"
)

func TestWriteTOML_BasicOutput(t *testing.T) {
	deps := []Dependency{
		{ImportPath: "github.com/foo/bar", Version: "v1.0.0", NixHash: "sha256-abc123="},
	}

	var buf bytes.Buffer
	opts := OutputOptions{
		IncludeHeader:         false,
		IncludeHashWarning:    false,
		IncludeRegenerateHint: false,
	}

	err := WriteTOML(&buf, deps, opts)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	output := buf.String()
	// Schema v2 uses versioned key format: [deps."import-path@version"]
	if !strings.Contains(output, `[deps."github.com/foo/bar@v1.0.0"]`) {
		t.Errorf("missing versioned dependency section, got:\n%s", output)
	}
	if !strings.Contains(output, `import_path = "github.com/foo/bar"`) {
		t.Error("missing import_path field")
	}
	if !strings.Contains(output, `version = "v1.0.0"`) {
		t.Error("missing version")
	}
	if !strings.Contains(output, `hash = "sha256-abc123="`) {
		t.Error("missing hash")
	}
}

func TestWriteTOML_IndirectDependency(t *testing.T) {
	deps := []Dependency{
		{ImportPath: "github.com/foo/bar", Version: "v1.0.0", Indirect: true, NixHash: "sha256-abc="},
	}

	var buf bytes.Buffer
	opts := OutputOptions{}

	err := WriteTOML(&buf, deps, opts)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	output := buf.String()
	if !strings.Contains(output, "indirect = true") {
		t.Error("missing indirect flag")
	}
}

func TestWriteTOML_MissingHash(t *testing.T) {
	deps := []Dependency{
		{ImportPath: "github.com/foo/bar", Version: "v1.0.0", GoSumHash: "h1:somehash="},
	}

	var buf bytes.Buffer
	opts := OutputOptions{
		IncludeHeader:         false,
		IncludeHashWarning:    true,
		IncludeRegenerateHint: false,
	}

	err := WriteTOML(&buf, deps, opts)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	output := buf.String()
	// Should have empty hash with comment
	if !strings.Contains(output, `hash = ""`) {
		t.Error("expected empty hash")
	}
	if !strings.Contains(output, "go.sum h1:somehash=") {
		t.Error("expected go.sum hash in comment")
	}
	// Should have warning about missing hashes
	if !strings.Contains(output, "IMPORTANT") {
		t.Error("expected hash warning")
	}
}

func TestWriteTOML_WithHeader(t *testing.T) {
	deps := []Dependency{}

	var buf bytes.Buffer
	opts := OutputOptions{
		IncludeHeader:         true,
		IncludeHashWarning:    false,
		IncludeRegenerateHint: true,
	}

	err := WriteTOML(&buf, deps, opts)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	output := buf.String()
	if !strings.Contains(output, "Auto-generated by godeps-gen") {
		t.Error("missing header")
	}
	if !strings.Contains(output, "To regenerate:") {
		t.Error("missing regenerate hint")
	}
	if !strings.Contains(output, "schema_version = 2") {
		t.Error("missing or incorrect schema version")
	}
	if !strings.Contains(output, "Key format: deps.") {
		t.Error("missing key format comment")
	}
}

func TestWriteTOML_NoHashWarningWhenAllHashed(t *testing.T) {
	deps := []Dependency{
		{ImportPath: "github.com/foo/bar", Version: "v1.0.0", NixHash: "sha256-abc="},
	}

	var buf bytes.Buffer
	opts := OutputOptions{
		IncludeHeader:         false,
		IncludeHashWarning:    true, // Warning enabled, but shouldn't appear
		IncludeRegenerateHint: false,
	}

	err := WriteTOML(&buf, deps, opts)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	output := buf.String()
	// Should NOT have warning since all deps have hashes
	if strings.Contains(output, "IMPORTANT") {
		t.Error("unexpected hash warning when all hashes present")
	}
}

func TestWriteTOML_MultipleDependencies(t *testing.T) {
	deps := []Dependency{
		{ImportPath: "github.com/aaa/first", Version: "v1.0.0", NixHash: "sha256-a="},
		{ImportPath: "github.com/bbb/second", Version: "v1.1.0", NixHash: "sha256-b="},
		{ImportPath: "github.com/ccc/third", Version: "v1.2.0", NixHash: "sha256-c=", Indirect: true},
	}

	var buf bytes.Buffer
	opts := OutputOptions{}

	err := WriteTOML(&buf, deps, opts)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	output := buf.String()
	// Check all deps are present
	if !strings.Contains(output, "github.com/aaa/first") {
		t.Error("missing first dep")
	}
	if !strings.Contains(output, "github.com/bbb/second") {
		t.Error("missing second dep")
	}
	if !strings.Contains(output, "github.com/ccc/third") {
		t.Error("missing third dep")
	}
}

func TestWriteTOML_EmptyDeps(t *testing.T) {
	deps := []Dependency{}

	var buf bytes.Buffer
	opts := OutputOptions{
		IncludeHeader: true,
	}

	err := WriteTOML(&buf, deps, opts)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Should still output header even with no deps
	output := buf.String()
	if !strings.Contains(output, "Auto-generated") {
		t.Error("expected header for empty deps")
	}
}

func TestFormatHashComment(t *testing.T) {
	tests := []struct {
		name     string
		hash     string
		expected string
	}{
		{
			name:     "with hash",
			hash:     "h1:abc123=",
			expected: " # go.sum h1:abc123= - run nix-prefetch-github to get correct hash",
		},
		{
			name:     "empty hash",
			hash:     "",
			expected: "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := formatHashComment(tt.hash)
			if result != tt.expected {
				t.Errorf("expected %q, got %q", tt.expected, result)
			}
		})
	}
}
