package godeps

import (
	"fmt"
	"io"
)

// OutputOptions configures the TOML output format.
type OutputOptions struct {
	// IncludeHeader adds the auto-generated header comment.
	IncludeHeader bool

	// IncludeHashWarning adds a warning when hashes are missing.
	IncludeHashWarning bool

	// IncludeRegenerateHint adds the regeneration command hint.
	IncludeRegenerateHint bool
}

// DefaultOutputOptions returns the default output options.
func DefaultOutputOptions() OutputOptions {
	return OutputOptions{
		IncludeHeader:         true,
		IncludeHashWarning:    true,
		IncludeRegenerateHint: true,
	}
}

// WriteTOML writes dependencies in go-deps.toml format to the given writer.
func WriteTOML(w io.Writer, deps []Dependency, opts OutputOptions) error {
	return WriteTOMLWithReplaces(w, deps, nil, opts)
}

// WriteTOMLWithReplaces writes dependencies and local replace directives in go-deps.toml format.
func WriteTOMLWithReplaces(w io.Writer, deps []Dependency, replaces []Replace, opts OutputOptions) error {
	// Check if any deps are missing hashes
	hasMissingHashes := false
	for _, dep := range deps {
		if dep.NixHash == "" {
			hasMissingHashes = true
			break
		}
	}

	// Filter to only local replaces (external replaces are handled separately)
	var localReplaces []Replace
	for _, r := range replaces {
		if r.IsLocal() {
			localReplaces = append(localReplaces, r)
		}
	}

	// Write header
	if opts.IncludeHeader {
		_, _ = fmt.Fprintln(w, "# Auto-generated by godeps-gen")
		_, _ = fmt.Fprintln(w, "# Source: go.mod + go.sum")
		_, _ = fmt.Fprintln(w, "#")
		_, _ = fmt.Fprintln(w, "# Key format: deps.\"import-path@version\" to support multiple versions")
		_, _ = fmt.Fprintln(w, "#")
	}

	if opts.IncludeHashWarning && hasMissingHashes {
		_, _ = fmt.Fprintln(w, "# IMPORTANT: Nix hashes must be obtained separately.")
		_, _ = fmt.Fprintln(w, "# Run with --prefetch to automatically fetch hashes, or manually run:")
		_, _ = fmt.Fprintln(w, "# nix-prefetch-github --owner OWNER --repo REPO --rev VERSION")
		_, _ = fmt.Fprintln(w, "#")
	}

	if opts.IncludeRegenerateHint {
		_, _ = fmt.Fprintln(w, "# To regenerate: godeps-gen --prefetch -o go-deps.toml")
		_, _ = fmt.Fprintln(w)
	}

	// Write schema version for forward compatibility
	// v2: versioned keys like [deps."path@version"] with import_path field
	_, _ = fmt.Fprintln(w, "schema_version = 2")
	_, _ = fmt.Fprintln(w)

	// Write each dependency
	for _, dep := range deps {
		if err := writeDependency(w, dep); err != nil {
			return err
		}
	}

	// Write local replace directives
	if len(localReplaces) > 0 {
		_, _ = fmt.Fprintln(w, "# Local replace directives - these map import paths to local Buck2 targets")
		_, _ = fmt.Fprintln(w)
		for _, rep := range localReplaces {
			if err := writeLocalReplace(w, rep); err != nil {
				return err
			}
		}
	}

	return nil
}

// writeDependency writes a single dependency entry in TOML format.
// Uses versioned key format: [deps."import-path@version"]
func writeDependency(w io.Writer, dep Dependency) error {
	// Versioned key format (schema v2)
	_, _ = fmt.Fprintf(w, "[deps.\"%s@%s\"]\n", dep.ImportPath, dep.Version)
	_, _ = fmt.Fprintf(w, "import_path = \"%s\"\n", dep.ImportPath)

	// Include fetch_path when it differs from import_path (external fork replace)
	if dep.FetchPath != "" && dep.FetchPath != dep.ImportPath {
		_, _ = fmt.Fprintf(w, "fetch_path = \"%s\"\n", dep.FetchPath)
	}

	_, _ = fmt.Fprintf(w, "version = \"%s\"\n", dep.Version)

	if dep.NixHash != "" {
		_, _ = fmt.Fprintf(w, "hash = \"%s\"\n", dep.NixHash)
	} else {
		// Empty hash with go.sum hash as comment for reference
		_, _ = fmt.Fprintf(w, "hash = \"\"%s\n", formatHashComment(dep.GoSumHash))
	}

	if dep.Indirect {
		_, _ = fmt.Fprintln(w, "indirect = true")
	}

	_, _ = fmt.Fprintln(w)
	return nil
}

// formatHashComment returns the go.sum hash as a reference comment.
func formatHashComment(goSumHash string) string {
	if goSumHash != "" {
		return fmt.Sprintf(" # go.sum %s - run nix-prefetch-github to get correct hash", goSumHash)
	}
	return ""
}

// writeLocalReplace writes a local replace directive entry in TOML format.
func writeLocalReplace(w io.Writer, rep Replace) error {
	// Key format: [replace."import-path"] or [replace."import-path@version"]
	key := rep.Old
	if rep.OldVersion != "" {
		key = rep.Old + "@" + rep.OldVersion
	}

	_, _ = fmt.Fprintf(w, "[replace.\"%s\"]\n", key)
	_, _ = fmt.Fprintf(w, "import_path = \"%s\"\n", rep.Old)
	_, _ = fmt.Fprintf(w, "local_path = \"%s\"\n", rep.NewPath)
	if rep.OldVersion != "" {
		_, _ = fmt.Fprintf(w, "version = \"%s\"\n", rep.OldVersion)
	}
	_, _ = fmt.Fprintln(w)

	return nil
}
