# Go Language Adapter for Dependency Cells
#
# Provides:
#   - mkGoDepPackage: Build a single Go module package
#   - mkGoDepsCell: Build a complete Go dependency cell
#
# Go dependencies are fetched from GitHub or Go module proxy.
# BUCK files are generated by gobuckify during the merge phase.

{ pkgs, lib }:

let
  fetchers = import ../fetchers.nix { inherit pkgs lib; };
  fixups = import ../fixups { inherit pkgs lib; };

  # gobuckify configuration (JSON)
  gobuckifyConfig = builtins.toJSON {
    buck = {
      # Note: preambule (sic) must end with newline for valid BUCK syntax
      preambule = "# Auto-generated by turnkey gobuckify\n";
      go_library_rule = "go_library";
      deps_target_label_prefix = "godeps//vendor/";
      deps_attr = "deps";
      # Constraint prefixes for platform-specific select() statements
      os_constraint_prefix = "config//os:";
      arch_constraint_prefix = "config//cpu:";
      # Output filename for build files
      buildfile_name = "rules.star";
    };
    platforms = [
      { go_os = "linux"; go_arch = "amd64"; buck_os = "linux"; buck_arch = "x86_64"; }
      { go_os = "linux"; go_arch = "arm64"; buck_os = "linux"; buck_arch = "aarch64"; }
      { go_os = "darwin"; go_arch = "amd64"; buck_os = "macos"; buck_arch = "x86_64"; }
      { go_os = "darwin"; go_arch = "arm64"; buck_os = "macos"; buck_arch = "arm64"; }
    ];
    default_tags = [ ];
  };
in
rec {
  # Build inputs for per-dependency builds
  buildInputs = [ pkgs.go ];

  # Build inputs for cell builds
  cellBuildInputs = [ pkgs.go pkgs.findutils ];

  # Hooks for per-dependency phases
  # Go doesn't need per-dep BUCK generation - it's done at merge time by gobuckify
  hooks = {
    # No per-dep hooks needed for Go
  };

  # Hooks for cell merge phase
  cellHooks = {
    # BUCK generation happens via gobuckify in mergeCommands
  };

  # ==========================================================================
  # Public API
  # ==========================================================================

  # Build a single Go module package
  mkGoDepPackage = {
    importPath,         # Go import path (e.g., "github.com/spf13/cobra")
    version,            # Version string (e.g., "v1.8.0")
    sha256,             # SRI hash of the source

    # Optional
    subPackages ? [],   # Specific packages within module (not used currently)
    fixup ? null,       # Custom fixup commands
  }:
  let
    fetchSpec = mkFetchSpec importPath version sha256;
    patchCommands = if fixup != null then fixup else "";
  in
  pkgs.runCommand "dep-go-${lib.replaceStrings ["/" "."] ["-" "-"] importPath}" {
    nativeBuildInputs = buildInputs;
    src = fetchers.fetch fetchSpec;
  } ''
    mkdir -p $out
    cp -r $src/* $out/
    chmod -R u+w $out

    # Apply fixup if provided
    cd $out
    ${patchCommands}
  '';

  # Build a complete Go dependency cell
  mkGoDepsCell = {
    depsFile,           # Path to go-deps.toml
    gobuckify,          # gobuckify tool derivation

    # Optional
    userFixups ? {},    # Additional fixups
  }:
  let
    depsToml = builtins.fromTOML (builtins.readFile depsFile);
    deps = depsToml.deps or {};

    # Merge built-in fixups with user-provided
    allFixups = (fixups.builtinFixups.go or {}) // userFixups;

    # Build individual dep packages
    depPackages = lib.mapAttrs (key: depSpec:
      mkGoDepPackage {
        importPath = key;
        version = depSpec.version;
        sha256 = depSpec.hash;
        fixup = allFixups.${key} or null;
      }
    ) deps;

    # Go standard assembly headers content
    # These headers are normally at $GOROOT/pkg/include but Buck2's system_go_toolchain
    # doesn't include them in the assembly include path. We generate them in packages
    # that have assembly files so they can be found locally.
    textflagH = ''
      // textflag.h - Go assembly flags
      // Generated by turnkey for Buck2 compatibility
      #define NOPROF      1
      #define DUPOK       2
      #define NOSPLIT     4
      #define RODATA      8
      #define NOPTR       16
      #define WRAPPER     32
      #define NEEDCTXT    64
      #define TLSBSS      256
      #define NOFRAME     512
      #define REFLECTMETHOD 1024
      #define TOPFRAME    2048
      #define ABIWRAPPER  4096
    '';

    funcdataH = ''
      // funcdata.h - Go funcdata constants
      // Generated by turnkey for Buck2 compatibility
      #define PCDATA_UnsafePoint      0
      #define PCDATA_StackMapIndex    1
      #define PCDATA_InlTreeIndex     2
      #define PCDATA_ArgLiveIndex     3

      #define FUNCDATA_ArgsPointerMaps    0
      #define FUNCDATA_LocalsPointerMaps  1
      #define FUNCDATA_StackObjects       2
      #define FUNCDATA_InlTree            3
      #define FUNCDATA_OpenCodedDeferInfo 4
      #define FUNCDATA_ArgInfo            5
      #define FUNCDATA_ArgLiveInfo        6
      #define FUNCDATA_WrapInfo           7
    '';
  in
  pkgs.runCommand "godeps-cell" {
    nativeBuildInputs = cellBuildInputs ++ [ gobuckify ];
    passthru = { inherit depPackages; };
    # Go needs a writable cache directory
    HOME = "/tmp";
    GOCACHE = "/tmp/go-cache";
    # Pass headers as environment variables for the build script
    inherit textflagH funcdataH;
  } ''
    mkdir -p $out/vendor

    # Copy each dep package into vendor/
    ${lib.concatStringsSep "\n" (lib.mapAttrsToList (importPath: pkg: ''
      mkdir -p "$out/vendor/${importPath}"
      cp -r ${pkg}/* "$out/vendor/${importPath}/"
      chmod -R u+w "$out/vendor/${importPath}"
    '') depPackages)}

    # Generate assembly headers in packages that have .s files
    # Buck2's system_go_toolchain doesn't provide -I $GOROOT/pkg/include,
    # so we generate textflag.h and funcdata.h locally where needed.
    echo "Adding assembly headers to packages with .s files..."
    find $out/vendor -name '*.s' -type f -printf '%h\n' | sort -u | while read dir; do
      if grep -q '#include "textflag.h"' "$dir"/*.s 2>/dev/null; then
        echo "$textflagH" > "$dir/textflag.h"
        echo "  Added textflag.h to $dir"
      fi
      if grep -q '#include "funcdata.h"' "$dir"/*.s 2>/dev/null; then
        echo "$funcdataH" > "$dir/funcdata.h"
        echo "  Added funcdata.h to $dir"
      fi
    done

    # Discover all Go packages by finding directories with .go files
    # Exclude testdata directories and test-only packages
    echo "Discovering Go packages..."
    find $out/vendor -type f -name '*.go' ! -name '*_test.go' -printf '%h\n' | \
      sort -u | \
      grep -v '/testdata/' > /tmp/all_packages.txt || true

    # Convert absolute paths to import paths
    sed -i "s|$out/vendor/||g" /tmp/all_packages.txt

    echo "Found $(wc -l < /tmp/all_packages.txt) packages"

    # Generate vendor/modules.txt
    # Format: module header, ## explicit, then all packages belonging to that module
    {
      ${lib.concatStringsSep "\n      " (lib.mapAttrsToList (importPath: depSpec: ''
      echo "# ${importPath} ${depSpec.version}"
      echo "## explicit"
      grep -E "^${lib.escapeRegex importPath}(/|$)" /tmp/all_packages.txt || true
      '') deps)}
    } > $out/vendor/modules.txt

    echo "Generated modules.txt"

    # Generate go.mod for gobuckify with actual versions
    cat > $out/go.mod << 'GOMOD'
    module godeps

    go 1.21

    require (
    ${lib.concatStringsSep "\n" (lib.mapAttrsToList (importPath: depSpec:
      "\t${importPath} ${depSpec.version}"
    ) deps)}
    )
    GOMOD

    # Generate main.go that imports all discovered packages
    {
      echo "package main"
      echo ""
      echo "import ("
      while read import_path; do
        echo "	_ \"$import_path\""
      done < /tmp/all_packages.txt
      echo ")"
      echo ""
      echo "func main() {}"
    } > $out/main.go

    echo "Generated main.go with $(wc -l < /tmp/all_packages.txt) imports"

    # Create gobuckify configuration
    cat > $out/gobuckify.json << 'GOBUCKIFY_CONFIG'
    ${gobuckifyConfig}
    GOBUCKIFY_CONFIG

    # Run gobuckify to generate BUCK files
    cd $out
    ${gobuckify}/bin/gobuckify .

    # Generate cell .buckconfig
    cat > $out/.buckconfig << 'CELLCONFIG'
    [cells]
        godeps = .
        prelude = prelude

    [buildfile]
        name = rules.star
    CELLCONFIG
  '';

  # ==========================================================================
  # Internal Helpers
  # ==========================================================================

  # Create fetch spec from Go import path
  mkFetchSpec = importPath: version: sha256:
    let
      parts = lib.splitString "/" importPath;
      host = lib.elemAt parts 0;
    in
    if host == "github.com" then
      fetchers.mkGitHubSpec {
        owner = lib.elemAt parts 1;
        repo = lib.elemAt parts 2;
        rev = version;
        inherit sha256;
      }
    else if host == "golang.org" && lib.length parts >= 3 && lib.elemAt parts 1 == "x" then
      # golang.org/x/* -> github.com/golang/*
      fetchers.mkGitHubSpec {
        owner = "golang";
        repo = lib.elemAt parts 2;
        rev = version;
        inherit sha256;
      }
    else if lib.hasPrefix "go.uber.org/" importPath then
      # go.uber.org/* -> github.com/uber-go/*
      fetchers.mkGitHubSpec {
        owner = "uber-go";
        repo = lib.removePrefix "go.uber.org/" (lib.head (lib.splitString "/" (lib.removePrefix "go.uber.org/" importPath)));
        rev = version;
        inherit sha256;
      }
    else if lib.hasPrefix "gopkg.in/" importPath then
      # gopkg.in handling is complex - use go proxy as fallback
      fetchers.mkGoProxySpec {
        modulePath = importPath;
        inherit version sha256;
      }
    else
      # Fallback to Go module proxy
      fetchers.mkGoProxySpec {
        modulePath = importPath;
        inherit version sha256;
      };

  # Internal mkDepPackage for generic builder compatibility
  mkDepPackage = { key, depSpec, config, allDeps }:
    mkGoDepPackage {
      importPath = key;
      version = depSpec.version;
      sha256 = depSpec.hash;
      fixup = (config.userFixups or {}).${key} or null;
    };

  # Merge commands for generic builder
  mergeCommands = ctx: ''
    # Go merge commands are handled directly in mkGoDepsCell
  '';
}
