# Go Language Adapter for Dependency Cells
#
# Provides:
#   - mkGoDepPackage: Build a single Go module package
#   - mkGoDepsCell: Build a complete Go dependency cell
#
# Go dependencies are fetched from GitHub or Go module proxy.
# BUCK files are generated by buckgen during the merge phase.

{ pkgs, lib }:

let
  fetchers = import ../fetchers.nix { inherit pkgs lib; };
  fixups = import ../fixups { inherit pkgs lib; };

  # buckgen configuration (JSON)
  buckgenConfig = builtins.toJSON {
    buck = {
      # Note: preambule (sic) must end with newline for valid BUCK syntax
      preambule = "# Auto-generated by turnkey buckgen\n";
      go_library_rule = "go_library";
      deps_target_label_prefix = "godeps//vendor/";
      deps_attr = "deps";
      # Constraint prefixes for platform-specific select() statements
      os_constraint_prefix = "config//os:";
      arch_constraint_prefix = "config//cpu:";
      # Output filename for build files
      buildfile_name = "rules.star";
    };
    platforms = [
      {
        go_os = "linux";
        go_arch = "amd64";
        buck_os = "linux";
        buck_arch = "x86_64";
      }
      {
        go_os = "linux";
        go_arch = "arm64";
        buck_os = "linux";
        buck_arch = "aarch64";
      }
      {
        go_os = "darwin";
        go_arch = "amd64";
        buck_os = "macos";
        buck_arch = "x86_64";
      }
      {
        go_os = "darwin";
        go_arch = "arm64";
        buck_os = "macos";
        buck_arch = "arm64";
      }
    ];
    default_tags = [ ];
  };
in
rec {
  # Build inputs for per-dependency builds
  buildInputs = [ pkgs.go ];

  # Build inputs for cell builds
  cellBuildInputs = [
    pkgs.go
    pkgs.findutils
  ];

  # Hooks for per-dependency phases
  # Go doesn't need per-dep BUCK generation - it's done at merge time by buckgen
  hooks = {
    # No per-dep hooks needed for Go
  };

  # Hooks for cell merge phase
  cellHooks = {
    # BUCK generation happens via buckgen in mergeCommands
  };

  # ==========================================================================
  # Public API
  # ==========================================================================

  # Build a single Go module package
  mkGoDepPackage =
    {
      importPath, # Go import path (e.g., "github.com/spf13/cobra")
      version, # Version string (e.g., "v1.8.0")
      sha256, # SRI hash of the source

      # Optional
      subPackages ? [ ], # Specific packages within module (not used currently)
      fixup ? null, # Custom fixup commands
    }:
    let
      fetchSpec = mkFetchSpec importPath version sha256;
      patchCommands = if fixup != null then fixup else "";
    in
    pkgs.runCommand "dep-go-${lib.replaceStrings [ "/" "." ] [ "-" "-" ] importPath}"
      {
        nativeBuildInputs = buildInputs;
        src = fetchers.fetch fetchSpec;
      }
      ''
        mkdir -p $out
        cp -r $src/* $out/
        chmod -R u+w $out

        # Apply fixup if provided
        cd $out
        ${patchCommands}
      '';

  # Build a complete Go dependency cell
  mkGoDepsCell =
    {
      depsFile, # Path to go-deps.toml
      buckgen, # buckgen tool derivation

      # Optional
      userFixups ? { }, # Additional fixups
    }:
    let
      depsToml = builtins.fromTOML (builtins.readFile depsFile);
      deps = depsToml.deps or { };
      schemaVersion = depsToml.schema_version or 1;

      # Merge built-in fixups with user-provided
      allFixups = (fixups.builtinFixups.go or { }) // userFixups;

      # Parse dependency info based on schema version
      # v1: key is import path, version in depSpec.version
      # v2: key is "import-path@version", import_path in depSpec.import_path
      parseDep = key: depSpec:
        if schemaVersion >= 2 then {
          importPath = depSpec.import_path;
          version = depSpec.version;
          # Key includes version for v2, e.g., "github.com/foo/bar@v1.0.0"
          versionedKey = key;
        } else {
          importPath = key;
          version = depSpec.version;
          # For v1, construct versioned key
          versionedKey = "${key}@${depSpec.version}";
        };

      # Build individual dep packages
      depPackages = lib.mapAttrs (
        key: depSpec:
        let
          parsed = parseDep key depSpec;
        in
        mkGoDepPackage {
          importPath = parsed.importPath;
          version = parsed.version;
          sha256 = depSpec.hash;
          fixup = allFixups.${parsed.importPath} or allFixups.${key} or null;
        }
      ) deps;

      # Parsed dependency info for use in merge phase
      parsedDeps = lib.mapAttrs parseDep deps;

      # Go standard assembly headers content
      # These headers are normally at $GOROOT/pkg/include but Buck2's system_go_toolchain
      # doesn't include them in the assembly include path. We generate them in packages
      # that have assembly files so they can be found locally.
      textflagH = ''
        // textflag.h - Go assembly flags
        // Generated by turnkey for Buck2 compatibility
        #define NOPROF      1
        #define DUPOK       2
        #define NOSPLIT     4
        #define RODATA      8
        #define NOPTR       16
        #define WRAPPER     32
        #define NEEDCTXT    64
        #define TLSBSS      256
        #define NOFRAME     512
        #define REFLECTMETHOD 1024
        #define TOPFRAME    2048
        #define ABIWRAPPER  4096
      '';

      funcdataH = ''
        // funcdata.h - Go funcdata constants
        // Generated by turnkey for Buck2 compatibility
        #define PCDATA_UnsafePoint      0
        #define PCDATA_StackMapIndex    1
        #define PCDATA_InlTreeIndex     2
        #define PCDATA_ArgLiveIndex     3

        #define FUNCDATA_ArgsPointerMaps    0
        #define FUNCDATA_LocalsPointerMaps  1
        #define FUNCDATA_StackObjects       2
        #define FUNCDATA_InlTree            3
        #define FUNCDATA_OpenCodedDeferInfo 4
        #define FUNCDATA_ArgInfo            5
        #define FUNCDATA_ArgLiveInfo        6
        #define FUNCDATA_WrapInfo           7
      '';
    in
    pkgs.runCommand "godeps-cell"
      {
        nativeBuildInputs = [
          buckgen
          pkgs.findutils
        ];
        passthru = { inherit depPackages; };
        # Pass headers as environment variables for the build script
        inherit textflagH funcdataH;
      }
      ''
        mkdir -p $out/vendor

        # Copy each dep package into vendor/ with versioned paths
        # For schema v2: create vendor/path@version/ directories
        # For both: create symlinks from vendor/path -> vendor/path@version
        ${lib.concatStringsSep "\n" (
          lib.mapAttrsToList (key: depSpec:
            let
              parsed = parsedDeps.${key};
              pkg = depPackages.${key};
              # Directory name includes version
              versionedPath = "${parsed.importPath}@${parsed.version}";
            in ''
            # Create versioned directory
            mkdir -p "$out/vendor/${versionedPath}"
            cp -r ${pkg}/* "$out/vendor/${versionedPath}/"
            chmod -R u+w "$out/vendor/${versionedPath}"
          '') deps
        )}

        # Create unversioned symlinks for backwards compatibility
        # These point to the versioned directories
        ${lib.concatStringsSep "\n" (
          let
            # Group by import path to find all versions
            byImportPath = lib.groupBy (key:
              let parsed = parsedDeps.${key};
              in parsed.importPath
            ) (lib.attrNames deps);

            # For each import path, create symlink to highest version
            mkSymlink = importPath: keys:
              let
                versions = map (key: parsedDeps.${key}.version) keys;
                # Sort versions (simple string sort works for semver with same prefix)
                sortedVersions = lib.sort (a: b: a > b) versions;
                highestVersion = lib.head sortedVersions;
                versionedPath = "${importPath}@${highestVersion}";
                # Get parent directory path
                parentDir = lib.concatStringsSep "/" (lib.init (lib.splitString "/" importPath));
              in ''
              # Create parent directories for symlink
              mkdir -p "$out/vendor/${parentDir}"
              # Create relative symlink from unversioned to versioned path
              ln -sfn "${lib.last (lib.splitString "/" importPath)}@${highestVersion}" "$out/vendor/${importPath}"
            '';
          in
          lib.mapAttrsToList mkSymlink byImportPath
        )}

        # Generate assembly headers in packages that have .s files
        # Buck2's system_go_toolchain doesn't provide -I $GOROOT/pkg/include,
        # so we generate textflag.h and funcdata.h locally where needed.
        echo "Adding assembly headers to packages with .s files..."
        find $out/vendor -name '*.s' -type f -printf '%h\n' | sort -u | while read dir; do
          if grep -q '#include "textflag.h"' "$dir"/*.s 2>/dev/null; then
            echo "$textflagH" > "$dir/textflag.h"
            echo "  Added textflag.h to $dir"
          fi
          if grep -q '#include "funcdata.h"' "$dir"/*.s 2>/dev/null; then
            echo "$funcdataH" > "$dir/funcdata.h"
            echo "  Added funcdata.h to $dir"
          fi
        done


        # Create buckgen configuration
        cat > $out/buckgen.json << 'BUCKGEN_CONFIG'
        ${buckgenConfig}
        BUCKGEN_CONFIG

        # Run buckgen to generate BUCK files
        cd $out
        ${buckgen}/bin/buckgen .

        # Generate cell .buckconfig
        cat > $out/.buckconfig << 'CELLCONFIG'
        [cells]
            godeps = .
            prelude = prelude

        [buildfile]
            name = rules.star
        CELLCONFIG
      '';

  # ==========================================================================
  # Internal Helpers
  # ==========================================================================

  # Create fetch spec from Go import path
  mkFetchSpec =
    importPath: version: sha256:
    let
      parts = lib.splitString "/" importPath;
      host = lib.elemAt parts 0;
    in
    if host == "github.com" then
      fetchers.mkGitHubSpec {
        owner = lib.elemAt parts 1;
        repo = lib.elemAt parts 2;
        rev = version;
        inherit sha256;
      }
    else if host == "golang.org" && lib.length parts >= 3 && lib.elemAt parts 1 == "x" then
      # golang.org/x/* -> github.com/golang/*
      fetchers.mkGitHubSpec {
        owner = "golang";
        repo = lib.elemAt parts 2;
        rev = version;
        inherit sha256;
      }
    else if lib.hasPrefix "go.uber.org/" importPath then
      # go.uber.org/* -> github.com/uber-go/*
      fetchers.mkGitHubSpec {
        owner = "uber-go";
        repo = lib.removePrefix "go.uber.org/" (
          lib.head (lib.splitString "/" (lib.removePrefix "go.uber.org/" importPath))
        );
        rev = version;
        inherit sha256;
      }
    else if lib.hasPrefix "gopkg.in/" importPath then
      # gopkg.in handling is complex - use go proxy as fallback
      fetchers.mkGoProxySpec {
        modulePath = importPath;
        inherit version sha256;
      }
    else
      # Fallback to Go module proxy
      fetchers.mkGoProxySpec {
        modulePath = importPath;
        inherit version sha256;
      };

  # Internal mkDepPackage for generic builder compatibility
  mkDepPackage =
    {
      key,
      depSpec,
      config,
      allDeps,
    }:
    mkGoDepPackage {
      importPath = key;
      version = depSpec.version;
      sha256 = depSpec.hash;
      fixup = (config.userFixups or { }).${key} or null;
    };

  # Merge commands for generic builder
  mergeCommands = ctx: ''
    # Go merge commands are handled directly in mkGoDepsCell
  '';
}
