# JavaScript/TypeScript Language Adapter for Dependency Cells
#
# Provides:
#   - mkJsDepPackage: Build a single npm package
#   - mkJsDepsCell: Build a complete JavaScript dependency cell
#
# JavaScript dependencies are fetched from npm registry.
# BUCK files expose packages as filegroups (for now).
#
# Future: Integrate with typescript_library for proper module resolution.

{ pkgs, lib, genericBuilder }:

let
  fetchers = import ../fetchers.nix { inherit pkgs lib; };
  fixups = import ../fixups { inherit pkgs lib; };
  platformsLib = import ../../../buck2/platforms.nix { inherit lib; };
  inherit (genericBuilder) genericMkDepsCell;

  # npm's names for Buck2's OS and CPU constraint values
  npmOS = {
    linux = "linux";
    macos = "darwin";
  };
  npmCPU = {
    x86_64 = "x64";
    arm64 = "arm64";
  };

  # Whether a package.json-style field (os, cpu, libc: names, or "!name" to
  # exclude one) allows value: when it lists none, any
  allows =
    field: value:
    let
      excluded = map (lib.removePrefix "!") (builtins.filter (lib.hasPrefix "!") field);
      included = builtins.filter (v: !(lib.hasPrefix "!" v)) field;
    in
    !(builtins.elem value excluded) && (included == [ ] || builtins.elem value included);

  # Whether npm installs pkg (a js-deps.toml entry) on a platform (Buck2's
  # names): its os and cpu allow the platform's, and on Linux, its libc
  # allows glibc, the C library turnkey's Linux platforms use
  installsOn =
    pkg: platform:
    allows (pkg.os or [ ]) npmOS.${platform.os}
    && allows (pkg.cpu or [ ]) npmCPU.${platform.cpu}
    && (platform.os != "linux" || allows (pkg.libc or [ ]) "glibc");

  # The npm_package rule of the cell's root: a package's files together
  # with those of the optional dependencies it gets on the platform, each
  # its own default output, so that consumers link each into node_modules
  npmPackageBzl = ''
    # Auto-generated by turnkey deps-cell

    def _npm_package_impl(ctx):
        outputs = []
        for dep in [ctx.attrs.package] + ctx.attrs.platform_deps:
            outputs.extend(dep[DefaultInfo].default_outputs)
        return [DefaultInfo(default_outputs = outputs)]

    npm_package = rule(
        impl = _npm_package_impl,
        attrs = {
            "package": attrs.dep(),
            "platform_deps": attrs.list(attrs.dep(), default = []),
        },
    )
  '';
in
rec {
  # Build inputs for per-dependency builds
  buildInputs = [];

  # Build inputs for cell builds
  cellBuildInputs = [];

  # Hooks for per-dependency phases
  hooks = {
    # JavaScript BUCK generation is done per-dep
  };

  # Hooks for cell merge phase
  cellHooks = {
    # No special merge operations needed for JavaScript
  };

  # ==========================================================================
  # Public API
  # ==========================================================================

  # Build a single npm package
  mkJsDepPackage = {
    name,               # Package name (e.g., "lodash" or "@types/node")
    version,            # Version string (e.g., "4.17.21")
    integrity,          # SRI hash (sha512-...)
    url,                # URL to fetch from (npm tarball)
    dependencies ? [],  # List of dependency names

    # Optional
    fixup ? null,       # Custom fixup commands
  }:
  let
    # Fetch spec for npm tarball
    fetchSpec = {
      type = "url";
      inherit url;
      hash = integrity;
    };

    # Sanitize name for Buck target (replace @ and / with _)
    targetName = lib.replaceStrings ["@" "/"] ["" "_"] name;

    # Generate BUCK file content
    # For now, expose as filegroup. Future: npm_library
    buckContent = ''
      # Auto-generated by turnkey deps-cell
      # Package: ${name}@${version}

      filegroup(
          name = "${targetName}",
          srcs = glob(["**/*"]),
          visibility = ["PUBLIC"],
      )
    '';
  in
  pkgs.runCommand "dep-js-${targetName}-${version}" {
    nativeBuildInputs = buildInputs;
    src = fetchers.fetch fetchSpec;
    passthru = { inherit name version; };
  } ''
    mkdir -p $out

    # npm tarballs have a 'package/' prefix, extract contents directly
    if [[ -d $src ]]; then
      cp -r $src/* $out/
    else
      tar -xzf $src --strip-components=1 -C $out
    fi
    chmod -R u+w $out

    # Apply fixup if provided
    cd $out
    ${if fixup != null then fixup else ""}

    # Generate rules.star file
    cat > $out/rules.star << 'RULES'
    ${buckContent}
    RULES
  '';

  # Build a complete JavaScript dependency cell
  mkJsDepsCell = {
    cellName,           # The cell's name (nix/buck2/languages.nix)
    depsFile,           # Path to js-deps.toml

    # The platforms to build for and their combined settings
    # (nix/buck2/platforms.nix's conditions): a package's optional
    # dependencies restricted to some platforms (os/cpu/libc) are a select()
    conditions,

    # Optional
    userFixups ? {},    # Additional fixups
    userPatchesDir ? null, # Path to .turnkey/patches directory (from FUSE edit layer)
  }:
  let
    depsToml = builtins.fromTOML (builtins.readFile depsFile);
    packages = depsToml.package or [];

    # Merge built-in fixups with user-provided
    allFixups = (fixups.builtinFixups.javascript or {}) // userFixups;

    # Build individual dep packages
    depPackages = builtins.listToAttrs (map (pkg: {
      name = pkg.name;
      value = mkJsDepPackage {
        inherit (pkg) name version url integrity;
        dependencies = pkg.dependencies or [];
        fixup = allFixups.${pkg.name} or null;
      };
    }) packages);

    byName = builtins.listToAttrs (map (pkg: lib.nameValuePair pkg.name pkg) packages);
    targetOf = name: lib.replaceStrings ["@" "/"] ["" "_"] name;
    vendorLabel = name: "//vendor/${name}:${targetOf name}";

    # A package's root target: an alias to its vendor target, or, when it
    # has optional dependencies npm installs on some platforms only, an
    # npm_package adding those the platform gets, keyed with the
    # conditions core's rules, with no DEFAULT. Optional dependencies
    # missing from js-deps.toml are left out.
    rootTarget = pkg:
      let
        targetName = targetOf pkg.name;
        optional = builtins.filter (name: byName ? ${name}) (pkg.optional_dependencies or []);
        split = platformsLib.split conditions (platform:
          map vendorLabel (builtins.filter (name: installsOn byName.${name} platform) optional));
        labels = values: "[${lib.concatMapStringsSep ", " (v: ''"${v}"'') values}]";
        select = "select({\n"
          + lib.concatMapStrings (b: "        \"${b.key}\": ${labels b.values},\n") split.branches
          + "    })";
        platformDeps =
          if split.branches == [] then labels split.common
          else if split.common == [] then select
          else "${labels split.common} + ${select}";
      in
      if optional == [] then ''
      alias(
          name = "${targetName}",
          actual = "${vendorLabel pkg.name}",
          visibility = ["PUBLIC"],
      )
      '' else ''
      npm_package(
          name = "${targetName}",
          package = "${vendorLabel pkg.name}",
          platform_deps = ${platformDeps},
          visibility = ["PUBLIC"],
      )
      '';

    # Generate root BUCK file for the cell (aliases to vendor packages)
    rootBuckContent = ''
      # Auto-generated by turnkey deps-cell
      # JavaScript dependencies cell

      load(":npm.bzl", "npm_package")

      ${lib.concatMapStringsSep "\n" rootTarget packages}
    '';
  in
  genericMkDepsCell {
    inherit cellName depPackages rootBuckContent userPatchesDir;
    mergeCommands = ''
      cat > $out/npm.bzl << 'NPMBZL'
      ${npmPackageBzl}
      NPMBZL
    '';
    # JavaScript uses simple name-only paths, no versioning or symlinks
    keyToPath = name: name;
    createSymlinks = false;
    cellBuildInputs = cellBuildInputs;
  };

}
