# JavaScript/TypeScript Language Adapter for Dependency Cells
#
# Provides:
#   - mkJsDepPackage: Build a single npm package
#   - mkJsDepsCell: Build a complete JavaScript dependency cell
#
# JavaScript dependencies are fetched from npm registry.
# BUCK files expose packages as filegroups (for now).
#
# Future: Integrate with typescript_library for proper module resolution.

{ pkgs, lib, genericBuilder }:

let
  fetchers = import ../fetchers.nix { inherit pkgs lib; };
  fixups = import ../fixups { inherit pkgs lib; };
  inherit (genericBuilder) genericMkDepsCell;
in
rec {
  # Build inputs for per-dependency builds
  buildInputs = [];

  # Build inputs for cell builds
  cellBuildInputs = [];

  # Hooks for per-dependency phases
  hooks = {
    # JavaScript BUCK generation is done per-dep
  };

  # Hooks for cell merge phase
  cellHooks = {
    # No special merge operations needed for JavaScript
  };

  # ==========================================================================
  # Public API
  # ==========================================================================

  # Build a single npm package
  mkJsDepPackage = {
    name,               # Package name (e.g., "lodash" or "@types/node")
    version,            # Version string (e.g., "4.17.21")
    integrity,          # SRI hash (sha512-...)
    url,                # URL to fetch from (npm tarball)
    dependencies ? [],  # List of dependency names

    # Optional
    fixup ? null,       # Custom fixup commands
  }:
  let
    # Fetch spec for npm tarball
    fetchSpec = {
      type = "url";
      inherit url;
      hash = integrity;
    };

    # Sanitize name for Buck target (replace @ and / with _)
    targetName = lib.replaceStrings ["@" "/"] ["" "_"] name;

    # Generate BUCK file content
    # For now, expose as filegroup. Future: npm_library
    buckContent = ''
      # Auto-generated by turnkey deps-cell
      # Package: ${name}@${version}

      filegroup(
          name = "${targetName}",
          srcs = glob(["**/*"]),
          visibility = ["PUBLIC"],
      )
    '';
  in
  pkgs.runCommand "dep-js-${targetName}-${version}" {
    nativeBuildInputs = buildInputs;
    src = fetchers.fetch fetchSpec;
    passthru = { inherit name version; };
  } ''
    mkdir -p $out

    # npm tarballs have a 'package/' prefix, extract contents directly
    if [[ -d $src ]]; then
      cp -r $src/* $out/
    else
      tar -xzf $src --strip-components=1 -C $out
    fi
    chmod -R u+w $out

    # Apply fixup if provided
    cd $out
    ${if fixup != null then fixup else ""}

    # Generate rules.star file
    cat > $out/rules.star << 'RULES'
    ${buckContent}
    RULES
  '';

  # Build a complete JavaScript dependency cell
  mkJsDepsCell = {
    depsFile,           # Path to js-deps.toml

    # Optional
    userFixups ? {},    # Additional fixups
    userPatchesDir ? null, # Path to .turnkey/patches directory (from FUSE edit layer)
  }:
  let
    depsToml = builtins.fromTOML (builtins.readFile depsFile);
    packages = depsToml.package or [];

    # Merge built-in fixups with user-provided
    allFixups = (fixups.builtinFixups.javascript or {}) // userFixups;

    # Build individual dep packages
    depPackages = builtins.listToAttrs (map (pkg: {
      name = pkg.name;
      value = mkJsDepPackage {
        inherit (pkg) name version url integrity;
        dependencies = pkg.dependencies or [];
        fixup = allFixups.${pkg.name} or null;
      };
    }) packages);

    # Generate root BUCK file for the cell (aliases to vendor packages)
    rootBuckContent = ''
      # Auto-generated by turnkey deps-cell
      # JavaScript dependencies cell

      ${lib.concatMapStringsSep "\n" (pkg:
        let targetName = lib.replaceStrings ["@" "/"] ["" "_"] pkg.name;
        in ''
      alias(
          name = "${targetName}",
          actual = "//vendor/${pkg.name}:${targetName}",
          visibility = ["PUBLIC"],
      )
        ''
      ) packages}
    '';
  in
  genericMkDepsCell {
    cellName = "jsdeps";
    inherit depPackages rootBuckContent userPatchesDir;
    # JavaScript uses simple name-only paths, no versioning or symlinks
    keyToPath = name: name;
    createSymlinks = false;
    cellBuildInputs = cellBuildInputs;
  };

}
