# JavaScript/TypeScript Language Adapter for Dependency Cells
#
# Provides:
#   - mkJsDepPackage: Build a single npm package
#   - mkJsDepsCell: Build a complete JavaScript dependency cell
#
# JavaScript dependencies are fetched from npm registry.
# BUCK files expose packages as filegroups (for now).
#
# Future: Integrate with typescript_library for proper module resolution.

{ pkgs, lib }:

let
  fetchers = import ../fetchers.nix { inherit pkgs lib; };
  fixups = import ../fixups { inherit pkgs lib; };
in
rec {
  # Build inputs for per-dependency builds
  buildInputs = [];

  # Build inputs for cell builds
  cellBuildInputs = [];

  # Hooks for per-dependency phases
  hooks = {
    # JavaScript BUCK generation is done per-dep
  };

  # Hooks for cell merge phase
  cellHooks = {
    # No special merge operations needed for JavaScript
  };

  # ==========================================================================
  # Public API
  # ==========================================================================

  # Build a single npm package
  mkJsDepPackage = {
    name,               # Package name (e.g., "lodash" or "@types/node")
    version,            # Version string (e.g., "4.17.21")
    integrity,          # SRI hash (sha512-...)
    url,                # URL to fetch from (npm tarball)
    dependencies ? [],  # List of dependency names

    # Optional
    fixup ? null,       # Custom fixup commands
  }:
  let
    # Fetch spec for npm tarball
    fetchSpec = {
      type = "url";
      inherit url;
      hash = integrity;
    };

    # Sanitize name for Buck target (replace @ and / with _)
    targetName = lib.replaceStrings ["@" "/"] ["" "_"] name;

    # Generate BUCK file content
    # For now, expose as filegroup. Future: npm_library
    buckContent = ''
      # Auto-generated by turnkey deps-cell
      # Package: ${name}@${version}

      filegroup(
          name = "${targetName}",
          srcs = glob(["**/*"]),
          visibility = ["PUBLIC"],
      )
    '';
  in
  pkgs.runCommand "dep-js-${targetName}-${version}" {
    nativeBuildInputs = buildInputs;
    src = fetchers.fetch fetchSpec;
    passthru = { inherit name version; };
  } ''
    mkdir -p $out

    # npm tarballs have a 'package/' prefix, extract contents directly
    if [[ -d $src ]]; then
      cp -r $src/* $out/
    else
      tar -xzf $src --strip-components=1 -C $out
    fi
    chmod -R u+w $out

    # Apply fixup if provided
    cd $out
    ${if fixup != null then fixup else ""}

    # Generate rules.star file
    cat > $out/rules.star << 'RULES'
    ${buckContent}
    RULES
  '';

  # Build a complete JavaScript dependency cell
  mkJsDepsCell = {
    depsFile,           # Path to js-deps.toml

    # Optional
    userFixups ? {},    # Additional fixups
  }:
  let
    depsToml = builtins.fromTOML (builtins.readFile depsFile);
    packages = depsToml.package or [];

    # Merge built-in fixups with user-provided
    allFixups = (fixups.builtinFixups.javascript or {}) // userFixups;

    # Build individual dep packages
    depPackages = builtins.listToAttrs (map (pkg: {
      name = pkg.name;
      value = mkJsDepPackage {
        inherit (pkg) name version url integrity;
        dependencies = pkg.dependencies or [];
        fixup = allFixups.${pkg.name} or null;
      };
    }) packages);

    # Generate root BUCK file for the cell
    rootBuckContent = ''
      # Auto-generated by turnkey deps-cell
      # JavaScript dependencies cell

      ${lib.concatMapStringsSep "\n" (pkg:
        let targetName = lib.replaceStrings ["@" "/"] ["" "_"] pkg.name;
        in ''
      alias(
          name = "${targetName}",
          actual = "//vendor/${pkg.name}:${targetName}",
          visibility = ["PUBLIC"],
      )
        ''
      ) packages}
    '';
  in
  pkgs.runCommand "jsdeps-cell" {
    nativeBuildInputs = cellBuildInputs;
    passthru = { inherit depPackages; };
  } ''
    mkdir -p $out/vendor

    # Copy each dep package into vendor/
    ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: pkg: ''
      mkdir -p "$out/vendor/${name}"
      cp -r ${pkg}/* "$out/vendor/${name}/"
      chmod -R u+w "$out/vendor/${name}"
    '') depPackages)}

    # Generate root rules.star file with aliases
    cat > $out/rules.star << 'RULES'
    ${rootBuckContent}
    RULES

    # Generate cell .buckconfig
    cat > $out/.buckconfig << 'CELLCONFIG'
    [cells]
        jsdeps = .
        prelude = prelude

    [buildfile]
        name = rules.star
    CELLCONFIG
  '';

  # ==========================================================================
  # Internal Helpers
  # ==========================================================================

  # Internal mkDepPackage for generic builder compatibility
  mkDepPackage = { key, depSpec, config, allDeps }:
    mkJsDepPackage {
      name = key;
      version = depSpec.version;
      integrity = depSpec.integrity;
      url = depSpec.url;
      dependencies = depSpec.dependencies or [];
      fixup = (config.userFixups or {}).${key} or null;
    };

  # Merge commands for generic builder
  mergeCommands = ctx: ''
    # JavaScript merge commands are handled directly in mkJsDepsCell
  '';
}
