# Python Language Adapter for Dependency Cells
#
# Provides:
#   - mkPythonDepPackage: Build a single Python package
#   - mkPythonDepsCell: Build a complete Python dependency cell
#
# Python dependencies are fetched from PyPI.
# rules.star files are generated per-dependency (simple python_library rules).

{ pkgs, lib }:

let
  fetchers = import ../fetchers.nix { inherit pkgs lib; };
  fixups = import ../fixups { inherit pkgs lib; };
in
rec {
  # Build inputs for per-dependency builds
  buildInputs = [];

  # Build inputs for cell builds
  cellBuildInputs = [];

  # Hooks for per-dependency phases
  hooks = {
    # Python BUCK generation is simple enough to be done per-dep
  };

  # Hooks for cell merge phase
  cellHooks = {
    # No special merge operations needed for Python
  };

  # ==========================================================================
  # Public API
  # ==========================================================================

  # Build a single Python package
  mkPythonDepPackage = {
    name,               # Package name (e.g., "requests")
    version,            # Version string (e.g., "2.31.0")
    sha256,             # SRI hash of the source
    url,                # URL to fetch from

    # Optional
    namespace ? false,  # Whether this is a namespace package
    fixup ? null,       # Custom fixup commands
  }:
  let
    fetchSpec = fetchers.mkPyPISpec {
      inherit url sha256;
    };

    # Generate BUCK file content
    buckContent = ''
      # Auto-generated by turnkey deps-cell
      load("@prelude//:rules.bzl", "python_library")

      python_library(
          name = "${name}",
          srcs = glob(["**/*.py"]),
          base_module = "",
          visibility = ["PUBLIC"],
      )
    '';
  in
  pkgs.runCommand "dep-python-${name}-${version}" {
    nativeBuildInputs = buildInputs;
    src = fetchers.fetch fetchSpec;
    passthru = { inherit name version; };
  } ''
    mkdir -p $out
    cp -r $src/* $out/
    chmod -R u+w $out

    # Apply fixup if provided
    cd $out
    ${if fixup != null then fixup else ""}

    # Generate rules.star file
    cat > $out/rules.star << 'RULES'
    ${buckContent}
    RULES
  '';

  # Build a complete Python dependency cell
  mkPythonDepsCell = {
    depsFile,           # Path to python-deps.toml

    # Optional
    userFixups ? {},    # Additional fixups
  }:
  let
    depsToml = builtins.fromTOML (builtins.readFile depsFile);
    deps = depsToml.deps or {};

    # Merge built-in fixups with user-provided
    allFixups = (fixups.builtinFixups.python or {}) // userFixups;

    # Build individual dep packages
    depPackages = lib.mapAttrs (name: depSpec:
      mkPythonDepPackage {
        inherit name;
        version = depSpec.version;
        sha256 = depSpec.hash;
        url = depSpec.url;
        fixup = allFixups.${name} or null;
      }
    ) deps;
  in
  pkgs.runCommand "pydeps-cell" {
    nativeBuildInputs = cellBuildInputs;
    passthru = { inherit depPackages; };
  } ''
    mkdir -p $out/vendor

    # Copy each dep package into vendor/
    ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: pkg: ''
      mkdir -p "$out/vendor/${name}"
      cp -r ${pkg}/* "$out/vendor/${name}/"
      chmod -R u+w "$out/vendor/${name}"
    '') depPackages)}

    # Generate cell .buckconfig
    cat > $out/.buckconfig << 'CELLCONFIG'
    [cells]
        pydeps = .
        prelude = prelude

    [buildfile]
        name = rules.star
    CELLCONFIG
  '';

  # ==========================================================================
  # Internal Helpers
  # ==========================================================================

  # Internal mkDepPackage for generic builder compatibility
  mkDepPackage = { key, depSpec, config, allDeps }:
    mkPythonDepPackage {
      name = key;
      version = depSpec.version;
      sha256 = depSpec.hash;
      url = depSpec.url;
      fixup = (config.userFixups or {}).${key} or null;
    };

  # Merge commands for generic builder
  mergeCommands = ctx: ''
    # Python merge commands are handled directly in mkPythonDepsCell
  '';
}
