# Python Language Adapter for Dependency Cells
#
# Provides:
#   - mkPythonDepPackage: Build a single Python package
#   - mkPythonDepsCell: Build a complete Python dependency cell
#
# Python dependencies are fetched from PyPI.
# rules.star files are generated per-dependency (simple python_library rules).

{ pkgs, lib, genericBuilder }:

let
  fetchers = import ../fetchers.nix { inherit pkgs lib; };
  fixups = import ../fixups { inherit pkgs lib; };
  inherit (genericBuilder) genericMkDepsCell;
in
rec {
  # Build inputs for per-dependency builds
  buildInputs = [];

  # Build inputs for cell builds
  cellBuildInputs = [];

  # Hooks for per-dependency phases
  hooks = {
    # Python BUCK generation is simple enough to be done per-dep
  };

  # Hooks for cell merge phase
  cellHooks = {
    # No special merge operations needed for Python
  };

  # ==========================================================================
  # Public API
  # ==========================================================================

  # Build a single Python package
  mkPythonDepPackage = {
    name,               # Package name (e.g., "requests")
    version,            # Version string (e.g., "2.31.0")
    sha256,             # SRI hash of the source
    url,                # URL to fetch from

    # Optional
    namespace ? false,  # Whether this is a namespace package
    fixup ? null,       # Custom fixup commands
  }:
  let
    fetchSpec = fetchers.mkPyPISpec {
      inherit url sha256;
    };

    # Generate BUCK file content
    buckContent = ''
      # Auto-generated by turnkey deps-cell
      load("@prelude//:rules.bzl", "python_library")

      python_library(
          name = "${name}",
          srcs = glob(["**/*.py"]),
          base_module = "",
          visibility = ["PUBLIC"],
      )
    '';
  in
  pkgs.runCommand "dep-python-${name}-${version}" {
    nativeBuildInputs = buildInputs;
    src = fetchers.fetch fetchSpec;
    passthru = { inherit name version; };
  } ''
    mkdir -p $out
    cp -r $src/* $out/
    chmod -R u+w $out

    # Apply fixup if provided
    cd $out
    ${if fixup != null then fixup else ""}

    # Generate rules.star file
    cat > $out/rules.star << 'RULES'
    ${buckContent}
    RULES
  '';

  # Build a complete Python dependency cell
  mkPythonDepsCell = {
    depsFile,           # Path to python-deps.toml

    # Optional
    userFixups ? {},    # Additional fixups
    userPatchesDir ? null, # Path to .turnkey/patches directory (from FUSE edit layer)
  }:
  let
    depsToml = builtins.fromTOML (builtins.readFile depsFile);
    deps = depsToml.deps or {};

    # Merge built-in fixups with user-provided
    allFixups = (fixups.builtinFixups.python or {}) // userFixups;

    # Build individual dep packages
    depPackages = lib.mapAttrs (name: depSpec:
      mkPythonDepPackage {
        inherit name;
        version = depSpec.version;
        sha256 = depSpec.hash;
        url = depSpec.url;
        fixup = allFixups.${name} or null;
      }
    ) deps;
  in
  genericMkDepsCell {
    cellName = "pydeps";
    inherit depPackages userPatchesDir;
    # Python uses simple name-only paths, no versioning or symlinks
    keyToPath = name: name;
    createSymlinks = false;
    cellBuildInputs = cellBuildInputs;
  };

}
