# Python Language Adapter for Dependency Cells
#
# Provides:
#   - mkPythonDepPackage: Build a single Python package
#   - mkPythonDepsCell: Build a complete Python dependency cell
#
# Python dependencies are fetched from PyPI.
# rules.star files are generated per-dependency (simple python_library rules).

{
  pkgs,
  lib,
  genericBuilder,
}:

let
  fetchers = import ../fetchers.nix { inherit pkgs lib; };
  fixups = import ../fixups { inherit pkgs lib; };
  inherit (genericBuilder) genericMkDepsCell;
in
rec {
  # Build inputs for per-dependency builds
  buildInputs = [ ];

  # Build inputs for cell builds
  cellBuildInputs = [ ];

  # ==========================================================================
  # Public API
  # ==========================================================================

  # Build a single Python package
  mkPythonDepPackage =
    {
      name, # Package name (e.g., "requests")
      version, # Version string (e.g., "2.31.0")
      sha256, # SRI hash of the source
      url, # URL to fetch from

      # Optional
      namespace ? false, # Whether this is a namespace package
      fixup ? null, # Custom fixup commands
    }:
    let
      fetchSpec = fetchers.mkPyPISpec {
        inherit url sha256;
      };

      # Generate BUCK file content
      buckContent = ''
        # Auto-generated by turnkey deps-cell
        load("@prelude//:rules.bzl", "python_library")

        python_library(
            name = "${name}",
            srcs = glob(["**/*.py"]),
            base_module = "",
            visibility = ["PUBLIC"],
        )
      '';
    in
    pkgs.runCommand "dep-python-${name}-${version}"
      {
        nativeBuildInputs = buildInputs;
        src = fetchers.fetch fetchSpec;
        passthru = { inherit name version; };
      }
      ''
        mkdir -p $out
        cp -r $src/* $out/
        chmod -R u+w $out

        # Apply fixup if provided
        cd $out
        ${if fixup != null then fixup else ""}

        # Generate rules.star file
        cat > $out/rules.star << 'RULES'
        ${buckContent}
        RULES
      '';

  # Build a complete Python dependency cell
  mkPythonDepsCell =
    {
      cellName, # The cell's name (nix/buck2/languages.nix)
      depsFile, # Path to python-deps.toml

      # The platforms to build for and their combined settings
      # (nix/buck2/platforms.nix's conditions), and the tool that writes the
      # packages' rules.star with the dependencies between them, each
      # dependency's marker evaluated per platform (nix/packages/pydeps-cell.nix)
      conditions,
      pydepsCell,
      # The Python toolchain's version the markers are evaluated for
      pythonVersion ? pkgs.python3.version,

      # Optional
      userFixups ? { }, # Additional fixups
      # The locked dependencies' fixups: [ { key; name; version; } ] ->
      # { <key> = { commands; }; } (nix/lib/fixups's resolve)
      resolveFixups ? (_: { }),
      userPatchesDir ? null, # Path to .turnkey/patches directory (from FUSE edit layer)
    }:
    let
      depsToml = builtins.fromTOML (builtins.readFile depsFile);
      deps = depsToml.deps or { };

      # Merge built-in fixups with user-provided
      allFixups = (fixups.builtinFixups.python or { }) // userFixups;

      # The locked distributions' fixups
      fixups = resolveFixups (
        lib.mapAttrsToList (name: depSpec: {
          key = name;
          inherit name;
          inherit (depSpec) version;
        }) deps
      );

      # Build individual dep packages
      depPackages = lib.mapAttrs (
        name: depSpec:
        mkPythonDepPackage {
          inherit name;
          version = depSpec.version;
          sha256 = depSpec.hash;
          url = depSpec.url;
          fixup = (fixups.${name}.commands or "") + (allFixups.${name} or "");
        }
      ) deps;
    in
    genericMkDepsCell {
      inherit cellName depPackages userPatchesDir;
      mergeCommands = ''
        cat > $out/pydeps-cell.json << 'PYDEPSCELL'
        ${builtins.toJSON (conditions // { python_version = pythonVersion; })}
        PYDEPSCELL
        ${lib.getExe pydepsCell} $out ${depsFile}
      '';
      # Python uses simple name-only paths, no versioning or symlinks
      keyToPath = name: name;
      createSymlinks = false;
      cellBuildInputs = cellBuildInputs;
    };

}
