# Solidity Language Adapter for Dependency Cells
#
# Provides:
#   - mkSolDepPackage: Build a single Solidity dependency (npm or git)
#   - mkSolDepsCell: Build a complete Solidity dependency cell
#
# Solidity dependencies can come from:
#   - npm: Packages like @openzeppelin/contracts
#   - git: Foundry-style git dependencies (forge-std, solady, etc.)
#
# The cell generates a remappings.json that solidity_library uses automatically.

{ pkgs, lib }:

let
  fetchers = import ../fetchers.nix { inherit pkgs lib; };
  fixups = import ../fixups { inherit pkgs lib; };
in
rec {
  # Build inputs for per-dependency builds
  buildInputs = [];

  # Build inputs for cell builds
  cellBuildInputs = [];

  # Hooks for per-dependency phases
  hooks = {};

  # Hooks for cell merge phase
  cellHooks = {};

  # ==========================================================================
  # Public API
  # ==========================================================================

  # Build a single Solidity dependency package
  mkSolDepPackage = {
    name,               # Package name (e.g., "forge-std" or "@openzeppelin/contracts")
    version,            # Version string (e.g., "1.8.0" or "5.0.0")
    source,             # "git" or "npm"

    # For npm packages
    url ? null,         # URL to fetch from (npm tarball)
    integrity ? null,   # SRI hash (sha512-...)

    # For git packages
    repo ? null,        # Git repository URL
    rev ? null,         # Git revision/tag/branch

    # Auto-generated remapping from soldeps-gen
    remapping ? null,

    # Optional
    fixup ? null,       # Custom fixup commands
  }:
  let
    # Fetch spec based on source type
    fetchSpec =
      if source == "npm" then {
        type = "url";
        inherit url;
        hash = integrity;
      }
      else if source == "git" then {
        type = "git";
        url = repo;
        rev = if rev != null then rev else "main";
      }
      else throw "Unknown source type: ${source}";

    # Sanitize name for Buck target (replace @ and / with _)
    targetName = lib.replaceStrings ["@" "/" "-"] ["" "_" "_"] name;

    # Generate BUCK file content
    buckContent = ''
      # Auto-generated by turnkey deps-cell
      # Package: ${name}@${version}
      # Source: ${source}

      filegroup(
          name = "${targetName}",
          srcs = glob(["**/*.sol"]),
          visibility = ["PUBLIC"],
      )

      filegroup(
          name = "${targetName}_all",
          srcs = glob(["**/*"]),
          visibility = ["PUBLIC"],
      )
    '';
  in
  pkgs.runCommand "dep-sol-${targetName}-${version}" {
    nativeBuildInputs = buildInputs;
    src = fetchers.fetch fetchSpec;
    passthru = { inherit name version source remapping; };
  } ''
    mkdir -p $out

    # Handle different source types
    if [[ -d $src ]]; then
      # Git checkout - copy directly
      cp -r $src/* $out/ 2>/dev/null || cp -r $src/. $out/
    else
      # npm tarball - extract with strip-components
      tar -xzf $src --strip-components=1 -C $out 2>/dev/null || tar -xf $src --strip-components=1 -C $out
    fi
    chmod -R u+w $out

    # Apply fixup if provided
    cd $out
    ${if fixup != null then fixup else ""}

    # Generate rules.star file
    cat > $out/rules.star << 'RULES'
    ${buckContent}
    RULES
  '';

  # Build a complete Solidity dependency cell
  mkSolDepsCell = {
    depsFile,           # Path to solidity-deps.toml

    # Optional
    userFixups ? {},    # Additional fixups
    cellName ? "soldeps",
  }:
  let
    depsToml = builtins.fromTOML (builtins.readFile depsFile);
    packages = depsToml.package or [];

    # Merge built-in fixups with user-provided
    allFixups = (fixups.builtinFixups.solidity or {}) // userFixups;

    # Build individual dep packages
    depPackages = builtins.listToAttrs (map (pkg: {
      name = pkg.name;
      value = mkSolDepPackage {
        inherit (pkg) name version source;
        url = pkg.url or null;
        integrity = pkg.integrity or null;
        repo = pkg.repo or null;
        rev = pkg.rev or null;
        remapping = pkg.remapping or null;
        fixup = allFixups.${pkg.name} or null;
      };
    }) packages);

    # Sanitize name for Buck target
    sanitizeName = name: lib.replaceStrings ["@" "/" "-"] ["" "_" "_"] name;

    # Generate remappings JSON - maps import prefixes to relative paths within the cell
    # This is read by solidity_library to auto-generate remappings
    remappingsJson = builtins.toJSON (builtins.listToAttrs (map (pkg: {
      name = sanitizeName pkg.name;  # Buck target name
      value = {
        package = pkg.name;
        prefix =
          # Use the remapping prefix from solidity-deps.toml, or derive from package name
          if pkg.remapping or null != null then
            let parts = lib.splitString "=" pkg.remapping;
            in builtins.head parts
          else if lib.hasPrefix "@" pkg.name then
            "${pkg.name}/"
          else
            "${pkg.name}/";
        # Path relative to the cell root where the package lives
        path = "vendor/${pkg.name}";
      };
    }) packages));

    # Generate root BUCK file for the cell
    rootBuckContent = ''
      # Auto-generated by turnkey deps-cell
      # Solidity dependencies cell

      ${lib.concatMapStringsSep "\n" (pkg:
        let targetName = sanitizeName pkg.name;
        in ''
      alias(
          name = "${targetName}",
          actual = "//vendor/${pkg.name}:${targetName}",
          visibility = ["PUBLIC"],
      )
        ''
      ) packages}
    '';

    # Generate remappings.txt in solc format for convenience
    remappingsTxt = lib.concatMapStringsSep "\n" (pkg:
      let
        prefix =
          if pkg.remapping or null != null then
            let parts = lib.splitString "=" pkg.remapping;
            in builtins.head parts
          else if lib.hasPrefix "@" pkg.name then
            "${pkg.name}/"
          else
            "${pkg.name}/";
      in
      "${prefix}=vendor/${pkg.name}/"
    ) packages;
  in
  pkgs.runCommand "${cellName}-cell" {
    nativeBuildInputs = cellBuildInputs;
    passthru = {
      inherit depPackages;
    };
  } ''
    mkdir -p $out/vendor

    # Copy each dep package into vendor/
    ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: pkg: ''
      mkdir -p "$out/vendor/${name}"
      cp -r ${pkg}/* "$out/vendor/${name}/"
      chmod -R u+w "$out/vendor/${name}"
    '') depPackages)}

    # Generate root rules.star file with aliases
    cat > $out/rules.star << 'RULES'
    ${rootBuckContent}
    RULES

    # Generate remappings.json for solidity_library to use
    cat > $out/remappings.json << 'REMAPPINGS_JSON'
    ${remappingsJson}
    REMAPPINGS_JSON

    # Generate remappings.txt in solc format for manual use
    cat > $out/remappings.txt << 'REMAPPINGS'
    ${remappingsTxt}
    REMAPPINGS

    # Generate cell .buckconfig
    cat > $out/.buckconfig << CELLCONFIG
    [cells]
        ${cellName} = .
        prelude = prelude

    [buildfile]
        name = rules.star
    CELLCONFIG
  '';

  # ==========================================================================
  # Internal Helpers
  # ==========================================================================

  mkDepPackage = { key, depSpec, config, allDeps }:
    mkSolDepPackage {
      name = key;
      version = depSpec.version;
      source = depSpec.source;
      url = depSpec.url or null;
      integrity = depSpec.integrity or null;
      repo = depSpec.repo or null;
      rev = depSpec.rev or null;
      remapping = depSpec.remapping or null;
      fixup = (config.userFixups or {}).${key} or null;
    };

  mergeCommands = ctx: "";
}
