# Solidity Language Adapter for Dependency Cells
#
# Provides:
#   - mkSolDepPackage: Build a single Solidity dependency (npm or git)
#   - mkSolDepsCell: Build a complete Solidity dependency cell
#
# Solidity dependencies can come from:
#   - npm: Packages like @openzeppelin/contracts
#   - git: Foundry-style git dependencies (forge-std, solady, etc.)
#
# The cell generates a remappings.json that solidity_library uses automatically.

{ pkgs, lib }:

let
  fetchers = import ../fetchers.nix { inherit pkgs lib; };
  fixups = import ../fixups { inherit pkgs lib; };
in
rec {
  # Build inputs for per-dependency builds
  buildInputs = [];

  # Build inputs for cell builds
  cellBuildInputs = [];

  # Hooks for per-dependency phases
  hooks = {};

  # Hooks for cell merge phase
  cellHooks = {};

  # ==========================================================================
  # Public API
  # ==========================================================================

  # The cell's remapping for one solidity-deps.toml package, as
  # { prefix, target } with target relative to the cell root.
  #
  # soldeps-gen writes remappings for a Foundry/npm checkout, where the
  # package sits at lib/<name>/ (git) or node_modules/<name>/ (npm), and the
  # target may go deeper: forge-std's sources are in src/. The cell vendors
  # every package at vendor/<name>/, so the target moves there and keeps
  # whatever follows the package directory. A package without a remapping
  # maps its own name to its root.
  cellRemapping = pkg:
    let
      remapping = pkg.remapping or null;
      prefix =
        if remapping == null then "${pkg.name}/"
        else builtins.head (lib.splitString "=" remapping);
      # Everything after the first "=": the target in soldeps-gen's layout
      target = lib.removePrefix "${prefix}=" remapping;
      # Where soldeps-gen puts git and npm packages (src/cmd/soldeps-gen/src/main.rs)
      layouts = [ "lib/${pkg.name}/" "node_modules/${pkg.name}/" ];
      layout = lib.findFirst (root: lib.hasPrefix root target) null layouts;
      subpath =
        if remapping == null then ""
        else if layout == null then
          throw "Solidity deps cell: remapping `${remapping}` for ${pkg.name} does not point into ${lib.concatStringsSep " or " layouts}"
        else lib.removePrefix layout target;
    in {
      inherit prefix;
      target = "vendor/${pkg.name}/${subpath}";
    };

  # Build a single Solidity dependency package
  mkSolDepPackage = {
    name,               # Package name (e.g., "forge-std" or "@openzeppelin/contracts")
    version,            # Version string (e.g., "1.8.0" or "5.0.0")
    source,             # "git" or "npm"

    # For npm packages
    url ? null,         # URL to fetch from (npm tarball)
    integrity ? null,   # SRI hash (sha512-...)

    # For git packages
    repo ? null,        # Git repository URL
    rev ? null,         # Git revision/tag/branch
    hash ? null,        # SRI hash of the unpacked `url` archive (soldeps-gen --prefetch)

    # Auto-generated remapping from soldeps-gen
    remapping ? null,

    # Optional
    fixup ? null,       # Custom fixup commands
  }:
  let
    # Fetch spec based on source type
    fetchSpec =
      if source == "npm" then {
        type = "url";
        inherit url;
        hash = integrity;
      }
      # A prefetched git package: the archive of its pinned commit, fetched as
      # a fixed-output derivation
      else if source == "git" && url != null && hash != null then {
        type = "zip";
        inherit url hash;
      }
      else if source == "git" then {
        type = "git";
        url = repo;
        rev = if rev != null then rev else "main";
      }
      else throw "Unknown source type: ${source}";

    # Sanitize name for Buck target (replace @ and / with _)
    targetName = lib.replaceStrings ["@" "/" "-"] ["" "_" "_"] name;

    # Generate BUCK file content
    buckContent = ''
      # Auto-generated by turnkey deps-cell
      # Package: ${name}@${version}
      # Source: ${source}

      filegroup(
          name = "${targetName}",
          srcs = glob(["**/*.sol"]),
          visibility = ["PUBLIC"],
      )

      filegroup(
          name = "${targetName}_all",
          srcs = glob(["**/*"]),
          visibility = ["PUBLIC"],
      )
    '';
  in
  pkgs.runCommand "dep-sol-${targetName}-${version}" {
    nativeBuildInputs = buildInputs;
    src = fetchers.fetch fetchSpec;
    passthru = { inherit name version source remapping; };
  } ''
    mkdir -p $out

    # Handle different source types
    if [[ -d $src ]]; then
      # Git checkout - copy directly
      cp -r $src/* $out/ 2>/dev/null || cp -r $src/. $out/
    else
      # npm tarball - extract with strip-components
      tar -xzf $src --strip-components=1 -C $out 2>/dev/null || tar -xf $src --strip-components=1 -C $out
    fi
    chmod -R u+w $out

    # Apply fixup if provided
    cd $out
    ${if fixup != null then fixup else ""}

    # Generate rules.star file
    cat > $out/rules.star << 'RULES'
    ${buckContent}
    RULES
  '';

  # Build a complete Solidity dependency cell
  mkSolDepsCell = {
    cellName,           # The cell's name (nix/buck2/languages.nix)
    depsFile,           # Path to solidity-deps.toml

    # Optional
    userFixups ? {},    # Additional fixups
  }:
  let
    depsToml = builtins.fromTOML (builtins.readFile depsFile);
    packages = depsToml.package or [];

    # Merge built-in fixups with user-provided
    allFixups = (fixups.builtinFixups.solidity or {}) // userFixups;

    # Build individual dep packages
    depPackages = builtins.listToAttrs (map (pkg: {
      name = pkg.name;
      value = mkSolDepPackage {
        inherit (pkg) name version source;
        url = pkg.url or null;
        integrity = pkg.integrity or null;
        repo = pkg.repo or null;
        rev = pkg.rev or null;
        hash = pkg.hash or null;
        remapping = pkg.remapping or null;
        fixup = allFixups.${pkg.name} or null;
      };
    }) packages);

    # Sanitize name for Buck target
    sanitizeName = name: lib.replaceStrings ["@" "/" "-"] ["" "_" "_"] name;

    # Generate remappings JSON - maps import prefixes to relative paths within the cell
    # This is read by solidity_library to auto-generate remappings
    remappingsJson = builtins.toJSON (builtins.listToAttrs (map (pkg: {
      name = sanitizeName pkg.name;  # Buck target name
      value = {
        package = pkg.name;
        inherit (cellRemapping pkg) prefix;
        # Path relative to the cell root where the package lives
        path = "vendor/${pkg.name}";
      };
    }) packages));

    # Generate root BUCK file for the cell
    #
    # `bundle` lays out every vendor package at its vendor/<name> path next to
    # remappings.txt, so the remappings stay valid inside it. Rules that read
    # dependency sources through remappings (solidity_test) depend on it, which
    # makes those sources declared inputs instead of files read in place.
    rootBuckContent = ''
      # Auto-generated by turnkey deps-cell
      # Solidity dependencies cell

      filegroup(
          name = "bundle",
          srcs = {
              "remappings.txt": "remappings.txt",
      ${lib.concatMapStringsSep "\n" (
        pkg: "        \"vendor/${pkg.name}\": \"//vendor/${pkg.name}:${sanitizeName pkg.name}_all\","
      ) packages}
          },
          visibility = ["PUBLIC"],
      )

      ${lib.concatMapStringsSep "\n" (pkg:
        let targetName = sanitizeName pkg.name;
        in ''
      alias(
          name = "${targetName}",
          actual = "//vendor/${pkg.name}:${targetName}",
          visibility = ["PUBLIC"],
      )
        ''
      ) packages}
    '';

    # Generate remappings.txt in solc format for convenience
    remappingsTxt = lib.concatMapStringsSep "\n" (pkg:
      let r = cellRemapping pkg;
      in "${r.prefix}=${r.target}"
    ) packages;
  in
  pkgs.runCommand "${cellName}-cell" {
    nativeBuildInputs = cellBuildInputs;
    passthru = {
      inherit depPackages;
    };
  } ''
    mkdir -p $out/vendor

    # Copy each dep package into vendor/
    ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: pkg: ''
      mkdir -p "$out/vendor/${name}"
      cp -r ${pkg}/* "$out/vendor/${name}/"
      chmod -R u+w "$out/vendor/${name}"
    '') depPackages)}

    # Generate root rules.star file with aliases
    cat > $out/rules.star << 'RULES'
    ${rootBuckContent}
    RULES

    # Generate remappings.json for solidity_library to use
    cat > $out/remappings.json << 'REMAPPINGS_JSON'
    ${remappingsJson}
    REMAPPINGS_JSON

    # Generate remappings.txt in solc format for manual use
    cat > $out/remappings.txt << 'REMAPPINGS'
    ${remappingsTxt}
    REMAPPINGS

    # Generate cell .buckconfig
    cat > $out/.buckconfig << CELLCONFIG
    [cells]
        ${cellName} = .
        prelude = prelude

    [buildfile]
        name = rules.star
    CELLCONFIG
  '';

  # ==========================================================================
  # Internal Helpers
  # ==========================================================================

  mkDepPackage = { key, depSpec, config, allDeps }:
    mkSolDepPackage {
      name = key;
      version = depSpec.version;
      source = depSpec.source;
      url = depSpec.url or null;
      integrity = depSpec.integrity or null;
      repo = depSpec.repo or null;
      rev = depSpec.rev or null;
      hash = depSpec.hash or null;
      remapping = depSpec.remapping or null;
      fixup = (config.userFixups or {}).${key} or null;
    };

  mergeCommands = ctx: "";
}
