//! Composition daemon configuration file parsing
//!
//! Reads `.turnkey/compose.toml` to configure the FUSE mount:
//! - Mount point and repo root
//! - Cell mappings (name → Nix store path)
//! - Layout and policy settings
//!
//! This file is typically generated by the Nix devenv module.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use serde::Deserialize;

use crate::config::{CellConfig, CompositionConfig};

/// Top-level compose.toml structure
#[derive(Debug, Deserialize)]
pub struct ComposeFile {
    /// Mount configuration
    pub mount: MountConfig,

    /// Cell mappings: name → source path
    #[serde(default)]
    pub cells: HashMap<String, CellEntry>,

    /// Optional settings
    #[serde(default)]
    pub settings: Settings,
}

/// Mount point and repo root configuration
#[derive(Debug, Deserialize)]
pub struct MountConfig {
    /// Where to mount the composed view (e.g., "/firefly/turnkey")
    pub point: PathBuf,

    /// Path to the repository root
    pub repo_root: PathBuf,
}

/// A cell entry — either a simple path string or a table with options
#[derive(Debug, Deserialize)]
#[serde(untagged)]
pub enum CellEntry {
    /// Simple form: just a path
    Path(PathBuf),
    /// Table form with optional fields
    Table {
        path: PathBuf,
        #[serde(default)]
        editable: bool,
    },
}

impl CellEntry {
    pub fn path(&self) -> &Path {
        match self {
            CellEntry::Path(p) => p,
            CellEntry::Table { path, .. } => path,
        }
    }

    pub fn editable(&self) -> bool {
        match self {
            CellEntry::Path(_) => false,
            CellEntry::Table { editable, .. } => *editable,
        }
    }
}

/// Optional daemon settings
#[derive(Debug, Deserialize)]
pub struct Settings {
    /// Layout plugin name (default: "buck2")
    #[serde(default = "default_layout")]
    pub layout: String,

    /// Source directory name in the mount (default: "root")
    #[serde(default = "default_source_dir")]
    pub source_dir: String,

    /// Cell prefix directory name (default: "external")
    #[serde(default = "default_cell_prefix")]
    pub cell_prefix: String,

    /// Backend type: "auto", "fuse", or "symlink"
    #[serde(default = "default_backend")]
    pub backend: String,
}

impl Default for Settings {
    fn default() -> Self {
        Self {
            layout: default_layout(),
            source_dir: default_source_dir(),
            cell_prefix: default_cell_prefix(),
            backend: default_backend(),
        }
    }
}

fn default_layout() -> String {
    "buck2".to_string()
}
fn default_source_dir() -> String {
    "root".to_string()
}
fn default_cell_prefix() -> String {
    "external".to_string()
}
fn default_backend() -> String {
    "auto".to_string()
}

impl ComposeFile {
    /// Read and parse a compose.toml file
    pub fn read(path: &Path) -> Result<Self, ComposeFileError> {
        let content = std::fs::read_to_string(path).map_err(|e| ComposeFileError::Io {
            path: path.to_path_buf(),
            source: e,
        })?;
        toml::from_str(&content).map_err(|e| ComposeFileError::Parse {
            path: path.to_path_buf(),
            source: e,
        })
    }

    /// Convert to a CompositionConfig
    pub fn into_composition_config(self) -> CompositionConfig {
        let mut config =
            CompositionConfig::new(&self.mount.point, &self.mount.repo_root)
                .with_source_dir_name(&self.settings.source_dir)
                .with_cell_prefix(&self.settings.cell_prefix);

        for (name, entry) in &self.cells {
            let cell = CellConfig::new(name, entry.path()).with_editable(entry.editable());
            config = config.with_cell(cell);
        }

        config
    }
}

/// Errors from reading compose.toml
#[derive(Debug)]
pub enum ComposeFileError {
    Io {
        path: PathBuf,
        source: std::io::Error,
    },
    Parse {
        path: PathBuf,
        source: toml::de::Error,
    },
}

impl std::fmt::Display for ComposeFileError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ComposeFileError::Io { path, source } => {
                write!(f, "failed to read {}: {}", path.display(), source)
            }
            ComposeFileError::Parse { path, source } => {
                write!(f, "failed to parse {}: {}", path.display(), source)
            }
        }
    }
}

impl std::error::Error for ComposeFileError {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_minimal() {
        let toml = r#"
[mount]
point = "/firefly/turnkey"
repo_root = "/home/user/src/turnkey"
"#;
        let config: ComposeFile = toml::from_str(toml).unwrap();
        assert_eq!(config.mount.point, PathBuf::from("/firefly/turnkey"));
        assert_eq!(config.mount.repo_root, PathBuf::from("/home/user/src/turnkey"));
        assert!(config.cells.is_empty());
        assert_eq!(config.settings.layout, "buck2");
    }

    #[test]
    fn test_parse_with_cells() {
        let toml = r#"
[mount]
point = "/firefly/turnkey"
repo_root = "/home/user/src/turnkey"

[cells]
godeps = "/nix/store/abc123-godeps-cell"
rustdeps = { path = "/nix/store/def456-rustdeps-cell", editable = true }
"#;
        let config: ComposeFile = toml::from_str(toml).unwrap();
        assert_eq!(config.cells.len(), 2);
        assert_eq!(
            config.cells["godeps"].path(),
            Path::new("/nix/store/abc123-godeps-cell")
        );
        assert!(!config.cells["godeps"].editable());
        assert!(config.cells["rustdeps"].editable());
    }

    #[test]
    fn test_into_composition_config() {
        let toml = r#"
[mount]
point = "/firefly/turnkey"
repo_root = "/home/user/src/turnkey"

[cells]
godeps = "/nix/store/abc123-godeps-cell"

[settings]
source_dir = "src"
cell_prefix = "deps"
"#;
        let compose: ComposeFile = toml::from_str(toml).unwrap();
        let config = compose.into_composition_config();
        assert_eq!(config.mount_point, PathBuf::from("/firefly/turnkey"));
        assert_eq!(config.source_dir_name, "src");
        assert_eq!(config.cell_prefix, "deps");
        assert_eq!(config.cells.len(), 1);
        assert_eq!(config.cells[0].name, "godeps");
    }
}
