//! Transparent VCS wrapper generation
//!
//! Generates shell wrapper scripts for VCS tools (jj, git) that detect
//! when running from a FUSE mount and redirect to the real repository.
//!
//! When `$PWD` is under a known mount point, the wrapper:
//! 1. Resolves the corresponding real repo root
//! 2. Maps the relative path from mount → repo
//! 3. Runs the real tool from the repo directory

use std::collections::HashMap;
use std::path::PathBuf;

use log::info;

/// Default directory for generated wrappers
pub fn wrappers_dir() -> PathBuf {
    dirs::data_local_dir()
        .unwrap_or_else(|| PathBuf::from("~/.local/share"))
        .join("turnkey")
        .join("bin")
}

/// Generate a wrapper script for a VCS tool.
///
/// The script checks if PWD is under any known mount point and redirects
/// to the real repo. Falls through to the real binary if not in a mount.
fn generate_wrapper(
    tool: &str,
    mounts: &HashMap<PathBuf, PathBuf>, // mount_point → repo_root
    source_dir_name: &str,
) -> String {
    let mut script = String::new();
    script.push_str("#!/usr/bin/env bash\n");
    script.push_str("# Generated by turnkey-composed — transparent VCS wrapper\n");
    script.push_str(&format!("# Redirects {} to the real repo when running from a FUSE mount\n\n", tool));

    // Find the real binary (skip ourselves)
    script.push_str(&format!(
        "REAL=$(PATH=\"$(echo \"$PATH\" | sed \"s|$(dirname \"$0\"):\\?||g\")\" command -v {} 2>/dev/null)\n",
        tool
    ));
    script.push_str("if [ -z \"$REAL\" ]; then\n");
    script.push_str(&format!("  echo \"turnkey: {} not found in PATH (excluding wrapper dir)\" >&2\n", tool));
    script.push_str("  exit 127\n");
    script.push_str("fi\n\n");

    // Check each mount point
    for (mount_point, repo_root) in mounts {
        let mp = mount_point.display();
        let rr = repo_root.display();
        // The source files are under <mount>/<source_dir_name>/
        // Map <mount>/<source_dir_name>/foo → <repo>/foo
        script.push_str(&format!(
            "if [[ \"$PWD\" == \"{mp}/{sdn}\"* ]]; then\n\
             \x20 REL=\"${{PWD#{mp}/{sdn}}}\"\n\
             \x20 REL=\"${{REL#/}}\"\n\
             \x20 REPO=\"{rr}\"\n\
             \x20 if [ -n \"$REL\" ]; then\n\
             \x20   cd \"$REPO/$REL\" 2>/dev/null || cd \"$REPO\"\n\
             \x20 else\n\
             \x20   cd \"$REPO\"\n\
             \x20 fi\n\
             \x20 exec \"$REAL\" \"$@\"\n\
             fi\n\n",
            mp = mp,
            rr = rr,
            sdn = source_dir_name,
        ));

        // Also handle being at the mount root itself
        script.push_str(&format!(
            "if [[ \"$PWD\" == \"{mp}\" || \"$PWD\" == \"{mp}/\"* ]]; then\n\
             \x20 cd \"{rr}\"\n\
             \x20 exec \"$REAL\" \"$@\"\n\
             fi\n\n",
            mp = mp,
            rr = rr,
        ));
    }

    // Not in any mount — run normally
    script.push_str("exec \"$REAL\" \"$@\"\n");
    script
}

/// Generate and write wrapper scripts for the given tools.
///
/// Returns the directory containing the wrappers (should be prepended to PATH).
pub fn generate_wrappers(
    tools: &[String],
    mounts: &HashMap<PathBuf, PathBuf>,
    source_dir_name: &str,
) -> Result<PathBuf, WrapperError> {
    let dir = wrappers_dir();
    std::fs::create_dir_all(&dir).map_err(|e| WrapperError::Io {
        message: format!("failed to create {}: {}", dir.display(), e),
    })?;

    for tool in tools {
        let script = generate_wrapper(tool, mounts, source_dir_name);
        let path = dir.join(tool);
        std::fs::write(&path, &script).map_err(|e| WrapperError::Io {
            message: format!("failed to write {}: {}", path.display(), e),
        })?;

        // Make executable
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perms = std::fs::metadata(&path)
                .map_err(|e| WrapperError::Io {
                    message: format!("failed to read permissions: {}", e),
                })?
                .permissions();
            perms.set_mode(0o755);
            std::fs::set_permissions(&path, perms).map_err(|e| WrapperError::Io {
                message: format!("failed to set permissions: {}", e),
            })?;
        }

        info!("Generated VCS wrapper: {}", path.display());
    }

    Ok(dir)
}

/// Clean up wrapper scripts
pub fn remove_wrappers(tools: &[String]) {
    let dir = wrappers_dir();
    for tool in tools {
        let path = dir.join(tool);
        std::fs::remove_file(&path).ok();
    }
}

#[derive(Debug)]
pub enum WrapperError {
    Io { message: String },
}

impl std::fmt::Display for WrapperError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            WrapperError::Io { message } => write!(f, "{}", message),
        }
    }
}

impl std::error::Error for WrapperError {}
