// Package pydepscell writes the rules.star files of the pydeps cell's
// vendored Python packages, with the dependencies between them.
//
// A package's dependencies come from python-deps.toml (pydeps-gen records
// them from uv.lock): its own, and those of the extras some package or
// workspace member asks it for. Each dependency's PEP 508 marker is
// evaluated on every platform turnkey builds for, for the Python
// toolchain's version: a dependency every platform gets is a plain dep,
// one some get is a select() keyed with the conditions core's rules, and
// one none gets (or that isn't vendored) is left out.
package pydepscell

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/firefly-engineering/turnkey/src/go/pkg/conditions"
	"github.com/firefly-engineering/turnkey/src/go/pkg/pep508"
	"github.com/firefly-engineering/turnkey/src/go/pkg/starlark"
	"github.com/pelletier/go-toml/v2"
)

// Config is what the cell is built for (pydeps-cell.json).
type Config struct {
	// Settings is the package of the combined config_settings.
	Settings string `json:"settings"`

	// Platforms are the platforms, in Buck2's names.
	Platforms []conditions.Platform `json:"platforms"`

	// PythonVersion is the Python toolchain's full version, e.g. "3.13.12".
	PythonVersion string `json:"python_version"`
}

// DepsFile is the part of python-deps.toml the cell reads.
type DepsFile struct {
	Deps map[string]Package `toml:"deps"`
}

// Package is a vendored package's entry.
type Package struct {
	Dependencies    []Edge            `toml:"dependencies"`
	Extras          map[string][]Edge `toml:"extras"`
	RequestedExtras []string          `toml:"requested_extras"`
}

// Edge is a dependency: a package's key, and when it applies.
type Edge struct {
	Name   string `toml:"name"`
	Marker string `toml:"marker"`
}

// LoadDeps reads python-deps.toml.
func LoadDeps(path string) (*DepsFile, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var deps DepsFile
	if err := toml.Unmarshal(content, &deps); err != nil {
		return nil, fmt.Errorf("parsing %s: %w", path, err)
	}
	return &deps, nil
}

// Render writes the rules.star of the package keyed name.
func Render(w io.Writer, name string, deps *DepsFile, cfg Config) error {
	pkg := deps.Deps[name]
	space := conditions.NewSpace(cfg.Platforms, cfg.Settings)

	// The edges, each with the extra it's evaluated with
	type edge struct {
		Edge
		extra  string
		marker *pep508.Marker
	}
	var edges []edge
	for _, e := range pkg.Dependencies {
		edges = append(edges, edge{Edge: e})
	}
	for _, extra := range pkg.RequestedExtras {
		for _, e := range pkg.Extras[extra] {
			edges = append(edges, edge{Edge: e, extra: extra})
		}
	}
	for i, e := range edges {
		if e.Marker == "" {
			continue
		}
		marker, err := pep508.ParseMarker(e.Marker)
		if err != nil {
			return fmt.Errorf("%s's dependency on %s: %w", name, e.Name, err)
		}
		edges[i].marker = marker
	}

	var failed error
	split := space.Split(func(config conditions.Configuration) []string {
		env, ok := pep508.PlatformEnv(config[conditions.OS], config[conditions.CPU], cfg.PythonVersion)
		if !ok && len(cfg.Platforms) > 0 {
			failed = fmt.Errorf("no marker environment for %s", config)
			return nil
		}
		seen := make(map[string]bool)
		var labels []string
		for _, e := range edges {
			if _, vendored := deps.Deps[e.Name]; !vendored || e.Name == name || seen[e.Name] {
				continue
			}
			if e.marker != nil {
				env := withExtra(env, e.extra)
				if !e.marker.Evaluate(env) {
					continue
				}
			}
			seen[e.Name] = true
			labels = append(labels, fmt.Sprintf("//vendor/%s:%s", e.Name, e.Name))
		}
		sort.Strings(labels)
		return labels
	})
	if failed != nil {
		return failed
	}

	fmt.Fprintln(w, "# Auto-generated by turnkey pydeps-cell")
	fmt.Fprintln(w, `load("@prelude//:rules.bzl", "python_library")`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, "python_library(")
	fmt.Fprintf(w, "    name = %q,\n", name)
	fmt.Fprintln(w, `    srcs = glob(["**/*.py"]),`)
	fmt.Fprintln(w, `    base_module = "",`)
	if len(split.Common) > 0 || split.IsConditional() {
		fmt.Fprintf(w, "    deps = %s,\n", starlark.RenderIndented(depsValue(split), "    "))
	}
	fmt.Fprintln(w, `    visibility = ["PUBLIC"],`)
	fmt.Fprintln(w, ")")
	return nil
}

// withExtra returns env with extra set.
func withExtra(env pep508.Env, extra string) pep508.Env {
	with := make(pep508.Env, len(env))
	for k, v := range env {
		with[k] = v
	}
	with["extra"] = extra
	return with
}

// depsValue returns a split as the deps attribute's value.
func depsValue(split conditions.Split) starlark.AttributeValue {
	common := starlark.StringListValue{Values: split.Common}
	if !split.IsConditional() {
		return common
	}
	sel := starlark.SelectValue{}
	if len(split.Common) > 0 {
		sel.Common = common
	}
	for _, b := range split.Branches {
		sel.Branches = append(sel.Branches, starlark.SelectBranch{Key: b.Key, Value: starlark.StringListValue{Values: b.Labels}})
	}
	return sel
}

// RenderCell writes the rules.star of every package in the cell's vendor
// directory that python-deps.toml has.
func RenderCell(cellDir string, deps *DepsFile, cfg Config) error {
	names := make([]string, 0, len(deps.Deps))
	for name := range deps.Deps {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		dir := filepath.Join(cellDir, "vendor", name)
		if _, err := os.Stat(dir); err != nil {
			continue
		}
		var b strings.Builder
		if err := Render(&b, name, deps, cfg); err != nil {
			return err
		}
		if err := os.WriteFile(filepath.Join(dir, "rules.star"), []byte(b.String()), 0o644); err != nil {
			return err
		}
	}
	return nil
}
