package godeps

import (
	"fmt"
	"io"
)

// OutputOptions configures the TOML output format.
type OutputOptions struct {
	// IncludeHeader adds the auto-generated header comment.
	IncludeHeader bool

	// IncludeHashWarning adds a warning when hashes are missing.
	IncludeHashWarning bool

	// IncludeRegenerateHint adds the regeneration command hint.
	IncludeRegenerateHint bool
}

// DefaultOutputOptions returns the default output options.
func DefaultOutputOptions() OutputOptions {
	return OutputOptions{
		IncludeHeader:         true,
		IncludeHashWarning:    true,
		IncludeRegenerateHint: true,
	}
}

// WriteTOML writes dependencies in go-deps.toml format to the given writer.
func WriteTOML(w io.Writer, deps []Dependency, opts OutputOptions) error {
	// Check if any deps are missing hashes
	hasMissingHashes := false
	for _, dep := range deps {
		if dep.NixHash == "" {
			hasMissingHashes = true
			break
		}
	}

	// Write header
	if opts.IncludeHeader {
		_, _ = fmt.Fprintln(w, "# Auto-generated by godeps-gen")
		_, _ = fmt.Fprintln(w, "# Source: go.mod + go.sum")
		_, _ = fmt.Fprintln(w, "#")
	}

	if opts.IncludeHashWarning && hasMissingHashes {
		_, _ = fmt.Fprintln(w, "# IMPORTANT: Nix hashes must be obtained separately.")
		_, _ = fmt.Fprintln(w, "# Run with --prefetch to automatically fetch hashes, or manually run:")
		_, _ = fmt.Fprintln(w, "# nix-prefetch-github --owner OWNER --repo REPO --rev VERSION")
		_, _ = fmt.Fprintln(w, "#")
	}

	if opts.IncludeRegenerateHint {
		_, _ = fmt.Fprintln(w, "# To regenerate: godeps-gen --prefetch -o go-deps.toml")
		_, _ = fmt.Fprintln(w)
	}

	// Write schema version for forward compatibility
	_, _ = fmt.Fprintln(w, "schema_version = 1")
	_, _ = fmt.Fprintln(w)

	// Write each dependency
	for _, dep := range deps {
		if err := writeDependency(w, dep); err != nil {
			return err
		}
	}

	return nil
}

// writeDependency writes a single dependency entry in TOML format.
func writeDependency(w io.Writer, dep Dependency) error {
	_, _ = fmt.Fprintf(w, "[deps.\"%s\"]\n", dep.ImportPath)
	_, _ = fmt.Fprintf(w, "version = \"%s\"\n", dep.Version)

	if dep.NixHash != "" {
		_, _ = fmt.Fprintf(w, "hash = \"%s\"\n", dep.NixHash)
	} else {
		// Empty hash with go.sum hash as comment for reference
		_, _ = fmt.Fprintf(w, "hash = \"\"%s\n", formatHashComment(dep.GoSumHash))
	}

	if dep.Indirect {
		_, _ = fmt.Fprintln(w, "indirect = true")
	}

	_, _ = fmt.Fprintln(w)
	return nil
}

// formatHashComment returns the go.sum hash as a reference comment.
func formatHashComment(goSumHash string) string {
	if goSumHash != "" {
		return fmt.Sprintf(" # go.sum %s - run nix-prefetch-github to get correct hash", goSumHash)
	}
	return ""
}
