//! A vendored Python package's rules.star, with its dependencies
//!
//! A package's dependencies come from python-deps.toml (pydeps-gen records
//! them from uv.lock): its own, and those of the extras some package or
//! workspace member asks it for. The Python adapter hands them over as the
//! package's slice, already narrowed to the packages the cell holds. Each
//! dependency's PEP 508 marker is evaluated on every platform turnkey
//! builds for, for the Python toolchain's version: a dependency every
//! platform gets is a plain dep, one some get is a select() keyed with the
//! conditions crate's rules, and one none gets is left out.

use anyhow::{Context, Result, anyhow};
use conditions::{Configuration, Platform, Space, conditional};
use deps_gen_kit::starlark::render_indented;
use gostd::strconv::quote;
use pep508::{Marker, env_for, parse_marker};
use serde::Deserialize;
use std::collections::{BTreeMap, HashSet};

/// What the distribution is built for: the platforms' conditions, and the
/// Python toolchain's version
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Config {
    /// The package of the combined config_settings
    pub settings: String,
    /// The platforms, in Buck2's names
    pub platforms: Vec<Platform>,
    /// The Python toolchain's full version, e.g. "3.13.12"
    pub python_version: String,
}

/// A distribution's package slice: its python-deps.toml entry, narrowed to
/// the distributions the cell holds and to the extras it is asked for
#[derive(Debug, Clone, Default, PartialEq, Eq, Deserialize)]
#[serde(default)]
pub struct Package {
    /// Its own dependencies
    pub dependencies: Vec<Edge>,
    /// The dependencies of each of its extras
    pub extras: BTreeMap<String, Vec<Edge>>,
    /// The extras some package or workspace member asks it for
    pub requested_extras: Vec<String>,
}

/// A dependency: a package's key, and when it applies
#[derive(Debug, Clone, Default, PartialEq, Eq, Deserialize)]
#[serde(default)]
pub struct Edge {
    /// The package's key
    pub name: String,
    /// The PEP 508 marker, "" when it always applies
    pub marker: String,
}

/// The rules.star of the package keyed `name`, from its slice
pub fn render(name: &str, pkg: &Package, cfg: &Config) -> Result<String> {
    let space = Space::new(&cfg.platforms, &cfg.settings);

    // The edges, each with the extra it's evaluated with and its marker
    let mut edges: Vec<(&Edge, &str, Option<Marker>)> = Vec::new();
    for e in &pkg.dependencies {
        edges.push((e, "", None));
    }
    for extra in &pkg.requested_extras {
        for e in pkg.extras.get(extra).into_iter().flatten() {
            edges.push((e, extra, None));
        }
    }
    for (e, _, marker) in &mut edges {
        if e.marker.is_empty() {
            continue;
        }
        *marker = Some(
            parse_marker(&e.marker)
                .with_context(|| format!("{name}'s dependency on {}", e.name))?,
        );
    }

    let mut failed = None;
    let value = conditional::labels_value(&space, |config: &Configuration| {
        if env_for(config, &cfg.python_version, "").is_none() {
            failed = Some(anyhow!("no marker environment for {config}"));
            return Vec::new();
        }
        let mut seen = HashSet::new();
        let mut labels = Vec::new();
        for (e, extra, marker) in &edges {
            if e.name == name || seen.contains(&e.name) {
                continue;
            }
            let env = env_for(config, &cfg.python_version, extra).expect("a known platform");
            if !pep508::holds(marker.as_ref(), &env) {
                continue;
            }
            seen.insert(e.name.clone());
            labels.push(format!("//vendor/{0}:{0}", e.name));
        }
        labels.sort();
        labels
    });
    if let Some(err) = failed {
        return Err(err);
    }

    let mut out = String::new();
    out.push_str("# Auto-generated by turnkey pydeps-cell\n");
    out.push_str("load(\"@prelude//:rules.bzl\", \"python_library\")\n");
    out.push('\n');
    out.push_str("python_library(\n");
    out.push_str(&format!("    name = {},\n", quote(name)));
    out.push_str("    srcs = glob([\"**/*.py\"]),\n");
    out.push_str("    base_module = \"\",\n");
    if let Some(value) = value {
        out.push_str(&format!(
            "    deps = {},\n",
            render_indented(&value, "    ")
        ));
    }
    out.push_str("    visibility = [\"PUBLIC\"],\n");
    out.push_str(")\n");
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn cfg() -> Config {
        Config {
            settings: "toolchains//conditions".into(),
            platforms: [
                ("linux", "x86_64"),
                ("linux", "arm64"),
                ("macos", "x86_64"),
                ("macos", "arm64"),
            ]
            .into_iter()
            .map(|(os, cpu)| Platform {
                os: os.into(),
                cpu: cpu.into(),
            })
            .collect(),
            python_version: "3.13.12".into(),
        }
    }

    const DEPS_TOML: &str = r#"
[deps.pytest]
dependencies = [
  { name = "iniconfig" },
  { name = "colorama", marker = "sys_platform == 'win32'" },
  { name = "exceptiongroup", marker = "python_version < '3.11'" },
  { name = "uvloop", marker = "sys_platform == 'linux'" },
  { name = "notvendored" },
]
requested_extras = ["testing"]

[deps.pytest.extras]
testing = [{ name = "hypothesis", marker = "extra == 'testing'" }]
other = [{ name = "xmlschema" }]

[deps.iniconfig]
[deps.colorama]
[deps.exceptiongroup]
[deps.uvloop]
[deps.hypothesis]
[deps.xmlschema]
"#;

    /// The slice of the package keyed `name` in DEPS_TOML, narrowed as the
    /// Python adapter narrows it: to the packages the file holds, and to the
    /// extras the package is asked for
    fn slice(name: &str) -> Package {
        let deps: toml::Table = toml::from_str(DEPS_TOML).unwrap();
        let deps = deps["deps"].as_table().unwrap();
        let entry = deps[name].as_table().unwrap();
        let edges = |list: Option<&toml::Value>| -> Vec<Edge> {
            list.and_then(|l| l.as_array())
                .into_iter()
                .flatten()
                .map(|e| Edge {
                    name: e["name"].as_str().unwrap().into(),
                    marker: e.get("marker").map_or("", |m| m.as_str().unwrap()).into(),
                })
                .filter(|e| deps.contains_key(&e.name))
                .collect()
        };
        let requested_extras: Vec<String> = entry
            .get("requested_extras")
            .and_then(|r| r.as_array())
            .into_iter()
            .flatten()
            .map(|x| x.as_str().unwrap().to_string())
            .collect();
        let extras = entry.get("extras").and_then(|x| x.as_table());
        Package {
            dependencies: edges(entry.get("dependencies")),
            extras: requested_extras
                .iter()
                .filter_map(|x| Some((x.clone(), edges(Some(extras?.get(x)?)))))
                .collect(),
            requested_extras,
        }
    }

    fn rendered(name: &str, cfg: &Config) -> Result<String> {
        render(name, &slice(name), cfg)
    }

    /// Markers are evaluated per platform and for the toolchain's Python: a
    /// Linux-only dependency is a config//os:linux branch, Windows-only and
    /// old-Python ones are dropped, and a requested extra's deps are in.
    #[test]
    fn render_evaluates_markers() {
        let got = rendered("pytest", &cfg()).unwrap();
        let want = r#"    deps = [
        "//vendor/hypothesis:hypothesis",
        "//vendor/iniconfig:iniconfig",
    ] + select({
        "config//os:linux": ["//vendor/uvloop:uvloop"],
        "config//os:macos": [],
    }),
"#;
        assert!(got.contains(want), "rules.star:\n{got}\nwant deps:\n{want}");
        for absent in [
            "colorama",
            "exceptiongroup",
            "notvendored",
            "xmlschema",
            "DEFAULT",
        ] {
            assert!(!got.contains(absent), "rules.star has {absent}:\n{got}");
        }
    }

    #[test]
    fn render_without_deps() {
        let got = rendered("iniconfig", &cfg()).unwrap();
        assert_eq!(
            got,
            r#"# Auto-generated by turnkey pydeps-cell
load("@prelude//:rules.bzl", "python_library")

python_library(
    name = "iniconfig",
    srcs = glob(["**/*.py"]),
    base_module = "",
    visibility = ["PUBLIC"],
)
"#
        );
    }

    /// A platform with no marker environment is an error, and so is a
    /// marker that doesn't parse
    #[test]
    fn render_errors() {
        let mut windows = cfg();
        windows.platforms.push(Platform {
            os: "windows".into(),
            cpu: "x86_64".into(),
        });
        assert!(rendered("iniconfig", &windows).is_err());

        let pkg = Package {
            dependencies: vec![Edge {
                name: "b".into(),
                marker: "nonsense".into(),
            }],
            ..Package::default()
        };
        assert!(render("a", &pkg, &cfg()).is_err());
    }

    /// Without platforms, markers are evaluated for the Python version
    /// alone, and every dependency that holds is a plain dep
    #[test]
    fn render_without_platforms() {
        let got = rendered(
            "pytest",
            &Config {
                python_version: "3.10.1".into(),
                ..Config::default()
            },
        )
        .unwrap();
        assert!(got.contains(
            "    deps = [\n        \"//vendor/exceptiongroup:exceptiongroup\",\n        \"//vendor/hypothesis:hypothesis\",\n        \"//vendor/iniconfig:iniconfig\",\n    ],\n"
        ), "{got}");
    }

    /// A slice is what the Python adapter writes with builtins.toJSON: a
    /// marker or a list it has none of is absent, and a dependency on the
    /// package itself is left out
    #[test]
    fn render_reads_the_adapters_slice() {
        let pkg: Package = serde_json::from_str(
            r#"{"dependencies": [{"name": "a"}, {"name": "b", "marker": "sys_platform == 'darwin'"}],
                "extras": {"x": [{"name": "c"}]}, "requested_extras": ["x"]}"#,
        )
        .unwrap();
        let got = render("a", &pkg, &cfg()).unwrap();
        let want = r#"    deps = ["//vendor/c:c"] + select({
        "config//os:linux": [],
        "config//os:macos": ["//vendor/b:b"],
    }),
"#;
        assert!(got.contains(want), "rules.star:\n{got}\nwant deps:\n{want}");
        assert!(!got.contains("//vendor/a:a"), "{got}");

        let empty: Package = serde_json::from_str("{}").unwrap();
        assert_eq!(empty, Package::default());
    }
}
