//! The rules.star files of the pydeps cell's vendored Python packages,
//! with the dependencies between them
//!
//! A package's dependencies come from python-deps.toml (pydeps-gen records
//! them from uv.lock): its own, and those of the extras some package or
//! workspace member asks it for. Each dependency's PEP 508 marker is
//! evaluated on every platform turnkey builds for, for the Python
//! toolchain's version: a dependency every platform gets is a plain dep,
//! one some get is a select() keyed with the conditions crate's rules, and
//! one none gets (or that isn't vendored) is left out.

use anyhow::{Context, Result, anyhow};
use conditions::{Configuration, Platform, Space, conditional};
use deps_gen_kit::starlark::render_indented;
use gostd::strconv::quote;
use pep508::{Marker, env_for, parse_marker};
use std::collections::{BTreeMap, HashSet};
use std::fs;
use std::io::Write;
use std::os::unix::fs::OpenOptionsExt;
use std::path::{Path, PathBuf};

/// What the cell is built for (pydeps-cell.json)
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Config {
    /// The package of the combined config_settings
    pub settings: String,
    /// The platforms, in Buck2's names
    pub platforms: Vec<Platform>,
    /// The Python toolchain's full version, e.g. "3.13.12"
    pub python_version: String,
}

/// The part of python-deps.toml the cell reads
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct DepsFile {
    /// The vendored packages, by key
    pub deps: BTreeMap<String, Package>,
}

/// A vendored package's entry
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Package {
    /// Its own dependencies
    pub dependencies: Vec<Edge>,
    /// The dependencies of each of its extras
    pub extras: BTreeMap<String, Vec<Edge>>,
    /// The extras some package or workspace member asks it for
    pub requested_extras: Vec<String>,
}

/// A dependency: a package's key, and when it applies
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Edge {
    /// The package's key
    pub name: String,
    /// The PEP 508 marker, "" when it always applies
    pub marker: String,
}

/// Reads python-deps.toml
pub fn load_deps(path: &Path) -> Result<DepsFile> {
    let content = fs::read(path).with_context(|| format!("open {}", path.display()))?;
    let content =
        std::str::from_utf8(&content).map_err(|e| anyhow!("parsing {}: {e}", path.display()))?;
    toml::from_str(content).map_err(|e| anyhow!("parsing {}: {e}", path.display()))
}

/// The rules.star of the package keyed `name`
pub fn render(name: &str, deps: &DepsFile, cfg: &Config) -> Result<String> {
    let empty = Package::default();
    let pkg = deps.deps.get(name).unwrap_or(&empty);
    let space = Space::new(&cfg.platforms, &cfg.settings);

    // The edges, each with the extra it's evaluated with and its marker
    let mut edges: Vec<(&Edge, &str, Option<Marker>)> = Vec::new();
    for e in &pkg.dependencies {
        edges.push((e, "", None));
    }
    for extra in &pkg.requested_extras {
        for e in pkg.extras.get(extra).into_iter().flatten() {
            edges.push((e, extra, None));
        }
    }
    for (e, _, marker) in &mut edges {
        if e.marker.is_empty() {
            continue;
        }
        *marker = Some(
            parse_marker(&e.marker)
                .with_context(|| format!("{name}'s dependency on {}", e.name))?,
        );
    }

    let mut failed = None;
    let value = conditional::labels_value(&space, |config: &Configuration| {
        if env_for(config, &cfg.python_version, "").is_none() {
            failed = Some(anyhow!("no marker environment for {config}"));
            return Vec::new();
        }
        let mut seen = HashSet::new();
        let mut labels = Vec::new();
        for (e, extra, marker) in &edges {
            if !deps.deps.contains_key(&e.name) || e.name == name || seen.contains(&e.name) {
                continue;
            }
            let env = env_for(config, &cfg.python_version, extra).expect("a known platform");
            if !pep508::holds(marker.as_ref(), &env) {
                continue;
            }
            seen.insert(e.name.clone());
            labels.push(format!("//vendor/{0}:{0}", e.name));
        }
        labels.sort();
        labels
    });
    if let Some(err) = failed {
        return Err(err);
    }

    let mut out = String::new();
    out.push_str("# Auto-generated by turnkey pydeps-cell\n");
    out.push_str("load(\"@prelude//:rules.bzl\", \"python_library\")\n");
    out.push('\n');
    out.push_str("python_library(\n");
    out.push_str(&format!("    name = {},\n", quote(name)));
    out.push_str("    srcs = glob([\"**/*.py\"]),\n");
    out.push_str("    base_module = \"\",\n");
    if let Some(value) = value {
        out.push_str(&format!(
            "    deps = {},\n",
            render_indented(&value, "    ")
        ));
    }
    out.push_str("    visibility = [\"PUBLIC\"],\n");
    out.push_str(")\n");
    Ok(out)
}

/// `cell_dir` joined with `elems`, cleaned as Go's filepath.Join cleans
/// it when the path is UTF-8
pub fn join(cell_dir: &Path, elems: &[&str]) -> PathBuf {
    match cell_dir.to_str() {
        Some(dir) => {
            let mut all = vec![dir];
            all.extend_from_slice(elems);
            PathBuf::from(gostd::path::join(&all))
        }
        None => elems.iter().fold(cell_dir.to_path_buf(), |p, e| p.join(e)),
    }
}

/// Writes the rules.star of every package in the cell's vendor directory
/// that python-deps.toml has
pub fn render_cell(cell_dir: &Path, deps: &DepsFile, cfg: &Config) -> Result<()> {
    for name in deps.deps.keys() {
        let dir = join(cell_dir, &["vendor", name]);
        if fs::metadata(&dir).is_err() {
            continue;
        }
        let rules = render(name, deps, cfg)?;
        let path = join(&dir, &["rules.star"]);
        let mut file = fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true)
            .mode(0o644)
            .open(&path)
            .with_context(|| format!("open {}", path.display()))?;
        file.write_all(rules.as_bytes())
            .with_context(|| format!("write {}", path.display()))?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn cfg() -> Config {
        Config {
            settings: "toolchains//conditions".into(),
            platforms: [
                ("linux", "x86_64"),
                ("linux", "arm64"),
                ("macos", "x86_64"),
                ("macos", "arm64"),
            ]
            .into_iter()
            .map(|(os, cpu)| Platform {
                os: os.into(),
                cpu: cpu.into(),
            })
            .collect(),
            python_version: "3.13.12".into(),
        }
    }

    const DEPS_TOML: &str = r#"
[deps.pytest]
dependencies = [
  { name = "iniconfig" },
  { name = "colorama", marker = "sys_platform == 'win32'" },
  { name = "exceptiongroup", marker = "python_version < '3.11'" },
  { name = "uvloop", marker = "sys_platform == 'linux'" },
  { name = "notvendored" },
]
requested_extras = ["testing"]

[deps.pytest.extras]
testing = [{ name = "hypothesis", marker = "extra == 'testing'" }]
other = [{ name = "xmlschema" }]

[deps.iniconfig]
[deps.colorama]
[deps.exceptiongroup]
[deps.uvloop]
[deps.hypothesis]
[deps.xmlschema]
"#;

    fn rendered(name: &str, cfg: &Config) -> Result<String> {
        let deps: DepsFile = toml::from_str(DEPS_TOML).unwrap();
        render(name, &deps, cfg)
    }

    /// Markers are evaluated per platform and for the toolchain's Python: a
    /// Linux-only dependency is a config//os:linux branch, Windows-only and
    /// old-Python ones are dropped, and a requested extra's deps are in.
    #[test]
    fn render_evaluates_markers() {
        let got = rendered("pytest", &cfg()).unwrap();
        let want = r#"    deps = [
        "//vendor/hypothesis:hypothesis",
        "//vendor/iniconfig:iniconfig",
    ] + select({
        "config//os:linux": ["//vendor/uvloop:uvloop"],
        "config//os:macos": [],
    }),
"#;
        assert!(got.contains(want), "rules.star:\n{got}\nwant deps:\n{want}");
        for absent in [
            "colorama",
            "exceptiongroup",
            "notvendored",
            "xmlschema",
            "DEFAULT",
        ] {
            assert!(!got.contains(absent), "rules.star has {absent}:\n{got}");
        }
    }

    #[test]
    fn render_without_deps() {
        let got = rendered("iniconfig", &cfg()).unwrap();
        assert_eq!(
            got,
            r#"# Auto-generated by turnkey pydeps-cell
load("@prelude//:rules.bzl", "python_library")

python_library(
    name = "iniconfig",
    srcs = glob(["**/*.py"]),
    base_module = "",
    visibility = ["PUBLIC"],
)
"#
        );
    }

    /// A platform with no marker environment is an error, and so is a
    /// marker that doesn't parse
    #[test]
    fn render_errors() {
        let mut windows = cfg();
        windows.platforms.push(Platform {
            os: "windows".into(),
            cpu: "x86_64".into(),
        });
        assert!(rendered("iniconfig", &windows).is_err());

        let deps: DepsFile =
            toml::from_str("[deps.a]\ndependencies = [{ name = \"b\", marker = \"nonsense\" }]\n")
                .unwrap();
        assert!(render("a", &deps, &cfg()).is_err());
    }

    /// Without platforms, markers are evaluated for the Python version
    /// alone, and every dependency that holds is a plain dep
    #[test]
    fn render_without_platforms() {
        let got = rendered(
            "pytest",
            &Config {
                python_version: "3.10.1".into(),
                ..Config::default()
            },
        )
        .unwrap();
        assert!(got.contains(
            "    deps = [\n        \"//vendor/exceptiongroup:exceptiongroup\",\n        \"//vendor/hypothesis:hypothesis\",\n        \"//vendor/iniconfig:iniconfig\",\n    ],\n"
        ), "{got}");
    }

    #[test]
    fn joins_as_go_does() {
        assert_eq!(
            join(Path::new("cell/"), &["vendor", "a/../b"]),
            Path::new("cell/vendor/b")
        );
        assert_eq!(
            join(Path::new("cell"), &["vendor", ""]),
            Path::new("cell/vendor")
        );
    }
}
