[package]
name = "buckgen"
version = "0.1.0"
edition.workspace = true
description = "Generate the rules.star files of a Go module in the Go deps cell"

[dependencies]
conditions.workspace = true
deps-gen-kit.workspace = true
goparse.workspace = true
gostd.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
