# Buck2 toolchain generation module for devenv
#
# Generates a Buck2 toolchains cell from toolchain.toml declarations.
# Creates a symlinked .buckconfig pointing to the Nix store.

{
  lib,
  config,
  pkgs,
  ...
}:

let
  cfg = config.turnkey.buck2;
  turnkeyCfg = config.turnkey;

  # Load the toolchain mappings
  mappings = import ../../buck2/mappings.nix { inherit lib; };

  # Get toolchain names from the declaration file
  toolchainNames =
    if turnkeyCfg.declarationFile != null then
      let
        decl = builtins.fromTOML (builtins.readFile turnkeyCfg.declarationFile);
      in
      if decl ? toolchains then builtins.attrNames decl.toolchains else [ ]
    else
      [ ];

  # Filter to only Buck2-relevant toolchains (those with mappings and not skipped)
  buck2Toolchains = builtins.filter (
    name: mappings ? ${name} && !(mappings.${name}.skip or false)
  ) toolchainNames;

  # Collect all implicit dependencies transitively
  collectDeps =
    toolchains:
    let
      directDeps = builtins.concatMap (
        name: mappings.${name}.implicitDependencies or [ ]
      ) toolchains;
      # Only include deps that have mappings and aren't skipped
      validDeps = builtins.filter (
        name: mappings ? ${name} && !(mappings.${name}.skip or false)
      ) directDeps;
      allDeps = lib.unique (toolchains ++ validDeps);
    in
    # Recurse until stable (handle transitive deps)
    if allDeps == toolchains then toolchains else collectDeps allDeps;

  # All toolchains including implicit dependencies
  allToolchains = collectDeps buck2Toolchains;

  # Add always-include toolchains (like genrule)
  alwaysIncluded = builtins.filter (name: mappings.${name}.alwaysInclude or false) (
    builtins.attrNames mappings
  );

  finalToolchains = lib.unique (allToolchains ++ alwaysIncluded);

  # Collect runtime dependencies from all active toolchains
  # These are packages that must be in PATH for Buck2 actions (e.g., clang for cxx)
  runtimeDeps = lib.unique (
    builtins.concatMap (
      name: mappings.${name}.runtimeDependencies or [ ]
    ) finalToolchains
  );

  # Resolve runtime dependencies to actual packages from registry
  runtimePackages = builtins.filter (p: p != null) (
    map (name: turnkeyCfg.registry.${name} or null) runtimeDeps
  );

  # Generate load statements for BUCK file
  generateLoads =
    toolchains:
    let
      # Collect all unique load statements
      loads = lib.unique (
        builtins.concatMap (
          name:
          map (t: {
            path = t.load;
            rule = t.rule;
          }) (mappings.${name}.targets or [ ])
        ) toolchains
      );
      # Group by load path for cleaner output
      byPath = lib.groupBy (l: l.path) loads;
      loadStmts = lib.mapAttrsToList (
        path: rules: ''load("${path}", ${lib.concatMapStringsSep ", " (r: ''"${r.rule}"'') rules})''
      ) byPath;
    in
    lib.concatStringsSep "\n" loadStmts;

  # Generate target instantiations for BUCK file
  generateTargets =
    toolchains:
    let
      targets = builtins.concatMap (
        name:
        map (
          t:
          let
            # Static attrs defined in the mapping
            staticAttrs = t.attrs or { };
            # Dynamic attrs resolved from registry (e.g., absolute paths to compilers)
            dynamicAttrs =
              if t ? dynamicAttrs then t.dynamicAttrs turnkeyCfg.registry else { };
            # Merge: dynamic attrs override static attrs
            attrs = staticAttrs // dynamicAttrs;
            attrLines =
              [ "    name = \"${t.name}\"," ]
              ++ [ "    visibility = ${builtins.toJSON t.visibility}," ]
              ++ (lib.mapAttrsToList (k: v: "    ${k} = ${builtins.toJSON v},") attrs);
          in
          "${t.rule}(\n${lib.concatStringsSep "\n" attrLines}\n)"
        ) (mappings.${name}.targets or [ ])
      ) toolchains;
    in
    lib.concatStringsSep "\n\n" targets;

  # Generate the complete BUCK file content
  buckFileContent = ''
# Generated by turnkey - do not edit manually
# Toolchains: ${lib.concatStringsSep ", " finalToolchains}

${generateLoads finalToolchains}

${generateTargets finalToolchains}
'';

  # Toolchains cell derivation
  toolchainsCell = pkgs.runCommand "turnkey-toolchains-cell" { } ''
    mkdir -p $out

    # Create BUCK file
    cat > $out/BUCK <<'BUCK'
    ${buckFileContent}
    BUCK

    # Create cell identity .buckconfig
    cat > $out/.buckconfig <<'BUCKCONFIG'
    [cells]
        toolchains = .
        prelude = ${preludeCellPath}
    BUCKCONFIG
  '';

  # Generate external_cells section based on prelude strategy
  externalCellsSection =
    if cfg.prelude.strategy == "bundled" then ''
      [external_cells]
          prelude = bundled
    ''
    else if cfg.prelude.strategy == "git" then ''
      [external_cells]
          prelude = git

      [external_cell_prelude]
          git_origin = ${cfg.prelude.gitOrigin}
          commit_hash = ${cfg.prelude.commitHash}
    ''
    else ""; # path and nix strategies use cells section directly

  # Prelude path in cells section
  preludeCellPath =
    if cfg.prelude.strategy == "bundled" then "prelude"
    else if cfg.prelude.strategy == "git" then "prelude"  # git uses external_cells
    else if cfg.prelude.strategy == "nix" then ".turnkey/prelude"  # symlinked derivation
    else cfg.prelude.path;  # path strategy uses direct path

  # Toolchains cell is accessed via a symlink at .turnkey/toolchains
  toolchainsCellPath = ".turnkey/toolchains";

  # ==========================================================================
  # Nix-backed cells registry
  # ==========================================================================
  # Define all Nix-backed cells here. Each cell needs:
  #   - name: Buck2 cell name (used in .buckconfig and targets)
  #   - path: Symlink path under .turnkey/
  #   - derivation: The Nix derivation containing the cell
  #   - description: Human-readable description for logging
  #
  # The registry automatically handles:
  #   - [cells] section in .buckconfig
  #   - Platform detector specs
  #   - Symlink creation in enterShell
  # ==========================================================================

  nixCells = lib.filterAttrs (_: cell: cell.derivation != null) ({
    godeps = {
      name = "godeps";
      path = ".turnkey/godeps";
      derivation = cfg.godeps;
      description = "Go deps";
    };
    # Future cells can be added here, e.g.:
    # rustdeps = {
    #   name = "rustdeps";
    #   path = ".turnkey/rustdeps";
    #   derivation = cfg.rustdeps;
    #   description = "Rust deps";
    # };
  } // lib.optionalAttrs (cfg.prelude.strategy == "nix") {
    # Prelude cell (only when using nix strategy)
    prelude = {
      name = "prelude";
      path = ".turnkey/prelude";
      derivation = cfg.prelude.path;
      description = "Prelude";
    };
  });

  # Generate [cells] config entries for all Nix-backed cells
  nixCellsConfig = lib.concatStringsSep "\n" (
    lib.mapAttrsToList (_: cell: "    ${cell.name} = ${cell.path}") nixCells
  );

  # Generate platform detector specs for all Nix-backed cells
  nixCellsPlatformDetectors = lib.concatMapStringsSep "" (
    cell: " target:${cell.name}//...->prelude//platforms:default"
  ) (lib.attrValues nixCells);

  # Generate symlink creation script for all Nix-backed cells
  nixCellsSymlinkScript = lib.concatStringsSep "\n" (
    lib.mapAttrsToList (_: cell: ''
      # Ensure ${cell.path} points to the ${cell.description} cell
      if [ -L ${cell.path} ]; then
        if [ "$(readlink ${cell.path})" != "${cell.derivation}" ]; then
          ln -sfn "${cell.derivation}" ${cell.path}
          echo "turnkey: Updated ${cell.name} cell symlink"
        fi
      elif [ -e ${cell.path} ]; then
        echo "turnkey: Warning: ${cell.path} exists and is not a symlink"
      else
        ln -s "${cell.derivation}" ${cell.path}
        echo "turnkey: Created ${cell.name} cell symlink"
      fi
    '') nixCells
  );

  # Generate info output for all Nix-backed cells
  nixCellsInfo = lib.concatStringsSep "\n" (
    lib.mapAttrsToList (_: cell: ''echo "  ${cell.description}: ${cell.derivation}"'') nixCells
  );

  # Generate env vars for all Nix-backed cells (for .envrc symlink sync)
  # Format: TURNKEY_CELL_<NAME> = "<path>:<derivation>"
  nixCellsEnvVars = lib.mapAttrs' (_: cell:
    lib.nameValuePair
      "TURNKEY_CELL_${lib.toUpper cell.name}"
      "${cell.path}:${cell.derivation}"
  ) nixCells;

  # For backward compatibility
  hasGodeps = cfg.godeps != null;

  # Generate buckconfig content
  buckconfigContent = ''
    # Generated by turnkey - do not edit manually
    [cells]
        root = .
        toolchains = ${toolchainsCellPath}
        prelude = ${preludeCellPath}
        none = none
    ${nixCellsConfig}

    [cell_aliases]
        config = prelude
        ovr_config = prelude
        fbcode = none
        fbsource = none
        fbcode_macros = none
        buck = none

    ${externalCellsSection}
    [parser]
        target_platform_detector_spec = target:root//...->prelude//platforms:default target:toolchains//...->prelude//platforms:default${nixCellsPlatformDetectors}

    [buildfile]
        name = BUCK

    [build]
        execution_platforms = prelude//platforms:default
  '';

  # Buckconfig file derivation
  buckconfig = pkgs.writeText "turnkey.buckconfig" buckconfigContent;

in
{
  options.turnkey.buck2 = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Enable Buck2 toolchain generation from toolchain.toml.

        When enabled, this module:
        1. Generates a toolchains cell with Buck2 toolchain rules
        2. Creates a .buckconfig symlink pointing to Nix-managed configuration
        3. Adds environment variables for debugging/inspection
      '';
    };

    prelude = {
      strategy = lib.mkOption {
        type = lib.types.enum [
          "bundled"
          "git"
          "nix"
          "path"
        ];
        default = "bundled";
        description = ''
          How to provide the Buck2 prelude cell:
          - bundled: Use Buck2's built-in bundled prelude (simplest)
          - git: Use a git external cell (requires gitOrigin and commitHash)
          - nix: Use a Nix derivation (requires path to be a derivation)
          - path: Use an explicit filesystem path
        '';
      };

      path = lib.mkOption {
        type = lib.types.either lib.types.path lib.types.str;
        default = "bundled://";
        description = ''
          Path to the prelude cell.
          - For bundled: use "bundled://" to use Buck2's built-in prelude
          - For git: the local checkout path
          - For nix: a Nix derivation or store path
          - For path: an absolute or relative filesystem path
        '';
      };

      gitOrigin = lib.mkOption {
        type = lib.types.str;
        default = "https://github.com/facebook/buck2-prelude.git";
        description = "Git origin URL for the prelude (when strategy = git)";
      };

      commitHash = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "Git commit hash for the prelude (required when strategy = git)";
      };
    };

    godeps = lib.mkOption {
      type = lib.types.nullOr lib.types.package;
      default = null;
      description = ''
        Nix derivation containing the Go dependencies cell.
        When set, a 'godeps' cell will be added to .buckconfig
        and symlinked to .turnkey/godeps.
      '';
    };

    goDepsFile = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = "go-deps.toml";
      description = ''
        Relative path to go-deps.toml file (for staleness checking).
        Used to warn when go-deps.toml needs regeneration.
      '';
    };

    goModFile = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = "go.mod";
      description = ''
        Relative path to go.mod file (for staleness checking).
        Used to warn when go-deps.toml needs regeneration.
      '';
    };

    goSumFile = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = "go.sum";
      description = ''
        Relative path to go.sum file (for staleness checking).
        Used to warn when go-deps.toml needs regeneration.
      '';
    };

    autoRegenerate = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Enable automatic go-deps.toml regeneration via pre-commit hook.
        When enabled, go-deps.toml will be regenerated when go.mod or go.sum
        are staged for commit.

        Note: Requires godeps-gen in the shell's packages and nix-prefetch-github
        available for hash fetching.
      '';
    };

    generateOnShellEntry = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Automatically generate/regenerate go-deps.toml when entering the shell
        if it's missing or stale (older than go.mod or go.sum).

        This enables a workflow where go-deps.toml is generated on-demand:
        1. First shell entry: go-deps.toml is generated (godeps cell skipped)
        2. Subsequent entries: Nix uses the generated file

        Requires godeps-gen to be available in PATH (add to registry or packages).
      '';
    };
  };

  config = lib.mkIf (cfg.enable && turnkeyCfg.enable) {
    # Add runtime dependencies to shell (e.g., clang for cxx toolchain)
    packages = runtimePackages;

    # Export paths for debugging and inspection
    env = {
      TURNKEY_BUCK2_TOOLCHAINS_CELL = "${toolchainsCell}";
      TURNKEY_BUCK2_CONFIG = "${buckconfig}";
      TURNKEY_BUCK2_TOOLCHAINS = lib.concatStringsSep "," finalToolchains;
      TURNKEY_BUCK2_RUNTIME_DEPS = lib.concatStringsSep "," runtimeDeps;
    } // nixCellsEnvVars;

    # Create symlinks on shell entry
    enterShell = ''
      # Create .turnkey directory for turnkey-managed symlinks
      mkdir -p .turnkey

      # Ensure .buckconfig points to the turnkey-generated config
      if [ -L .buckconfig ]; then
        # Already a symlink - update it if needed
        if [ "$(readlink .buckconfig)" != "${buckconfig}" ]; then
          ln -sf "${buckconfig}" .buckconfig
          echo "turnkey: Updated .buckconfig symlink"
        fi
      elif [ -e .buckconfig ]; then
        echo "turnkey: Warning: .buckconfig exists and is not a symlink"
        echo "         Remove it to let turnkey manage Buck2 configuration"
      else
        ln -s "${buckconfig}" .buckconfig
        echo "turnkey: Created .buckconfig symlink"
      fi

      # Ensure .buckroot exists (marks project boundary for Buck2)
      if [ ! -e .buckroot ]; then
        touch .buckroot
        echo "turnkey: Created .buckroot file"
      fi

      # Ensure .turnkey/toolchains points to the generated toolchains cell
      if [ -L .turnkey/toolchains ]; then
        if [ "$(readlink .turnkey/toolchains)" != "${toolchainsCell}" ]; then
          ln -sfn "${toolchainsCell}" .turnkey/toolchains
          echo "turnkey: Updated toolchains cell symlink"
        fi
      elif [ -e .turnkey/toolchains ]; then
        echo "turnkey: Warning: .turnkey/toolchains exists and is not a symlink"
      else
        ln -s "${toolchainsCell}" .turnkey/toolchains
        echo "turnkey: Created toolchains cell symlink"
      fi

      # Create symlinks for all Nix-backed cells
      ${nixCellsSymlinkScript}

      # Auto-generate or check staleness of go-deps.toml
      _go_deps_file="${cfg.goDepsFile}"
      _go_mod_file="${cfg.goModFile}"
      _go_sum_file="${cfg.goSumFile}"
      _should_generate=0
      _generate_enabled=${if cfg.generateOnShellEntry then "1" else "0"}

      if [ -f "$_go_mod_file" ]; then
        if [ ! -f "$_go_deps_file" ]; then
          # go-deps.toml doesn't exist
          if [ "$_generate_enabled" = "1" ]; then
            _should_generate=1
            echo "turnkey: go-deps.toml not found, will generate..."
          else
            echo ""
            echo "⚠️  turnkey: go-deps.toml not found!"
            echo "   Generate with: godeps-gen --go-mod $_go_mod_file --go-sum $_go_sum_file --prefetch > $_go_deps_file"
            echo ""
          fi
        else
          # Check if stale
          _stale=0
          if [ "$_go_mod_file" -nt "$_go_deps_file" ]; then
            _stale=1
          fi
          if [ -f "$_go_sum_file" ] && [ "$_go_sum_file" -nt "$_go_deps_file" ]; then
            _stale=1
          fi
          if [ "$_stale" = "1" ]; then
            if [ "$_generate_enabled" = "1" ]; then
              _should_generate=1
              echo "turnkey: go-deps.toml is stale, will regenerate..."
            else
              echo ""
              echo "⚠️  turnkey: go-deps.toml may be stale!"
              echo "   go.mod or go.sum is newer than go-deps.toml"
              echo "   Regenerate with: godeps-gen --go-mod $_go_mod_file --go-sum $_go_sum_file --prefetch > $_go_deps_file"
              echo ""
            fi
          fi
        fi

        # Generate if needed
        if [ "$_should_generate" = "1" ]; then
          if command -v godeps-gen >/dev/null 2>&1; then
            echo "turnkey: Running godeps-gen --prefetch..."
            if godeps-gen --go-mod "$_go_mod_file" --go-sum "$_go_sum_file" --prefetch > "$_go_deps_file.tmp"; then
              mv "$_go_deps_file.tmp" "$_go_deps_file"
              echo "turnkey: Generated $_go_deps_file"
              echo ""
              echo "ℹ️  Note: The godeps cell will be available on next shell entry."
              echo "   Run 'exit' and 'nix develop' again to use the new dependencies."
              echo ""
            else
              rm -f "$_go_deps_file.tmp"
              echo ""
              echo "❌ turnkey: Failed to generate go-deps.toml"
              echo "   Check the error above and try manually:"
              echo "   godeps-gen --go-mod $_go_mod_file --go-sum $_go_sum_file --prefetch > $_go_deps_file"
              echo ""
            fi
          else
            echo ""
            echo "⚠️  turnkey: godeps-gen not found in PATH"
            echo "   Add 'godeps-gen' to your toolchain.toml or packages to enable auto-generation"
            echo "   Or generate manually: nix run .#godeps-gen -- --go-mod $_go_mod_file --go-sum $_go_sum_file --prefetch > $_go_deps_file"
            echo ""
          fi
        fi
      fi

      echo "Buck2 configured by turnkey"
      echo "  Toolchains: ${lib.concatStringsSep ", " finalToolchains}"
      echo "  Runtime deps: ${lib.concatStringsSep ", " runtimeDeps}"
      ${nixCellsInfo}
      echo "  Cell: $TURNKEY_BUCK2_TOOLCHAINS_CELL"
    '';

    # Pre-commit hook for automatic go-deps.toml regeneration
    git-hooks.hooks = lib.mkIf (hasGodeps && cfg.autoRegenerate) {
      godeps-gen = {
        enable = true;
        name = "godeps-gen";
        description = "Regenerate go-deps.toml when go.mod or go.sum changes";
        files = "(go\\.mod|go\\.sum)$";
        pass_filenames = false;
        entry = ''
          sh -c '
            if command -v godeps-gen >/dev/null 2>&1; then
              echo "Regenerating ${cfg.goDepsFile}..."
              godeps-gen --go-mod "${cfg.goModFile}" --go-sum "${cfg.goSumFile}" --prefetch > "${cfg.goDepsFile}"
              git add "${cfg.goDepsFile}"
            else
              echo "Warning: godeps-gen not found in PATH, skipping regeneration"
            fi
          '
        '';
      };
    };
  };
}
