# Buck2 toolchain generation module for devenv
#
# Generates a Buck2 toolchains cell from toolchain.toml declarations.
# Creates a wrapper script that injects Nix-managed cell paths via --config-file.

{
  lib,
  config,
  pkgs,
  ...
}:

let
  cfg = config.turnkey.buck2;
  turnkeyCfg = config.turnkey;

  # Load the toolchain mappings
  mappings = import ../../buck2/mappings.nix { inherit lib; };

  # Get toolchain names from the declaration file
  toolchainNames =
    if turnkeyCfg.declarationFile != null then
      let
        decl = builtins.fromTOML (builtins.readFile turnkeyCfg.declarationFile);
      in
      if decl ? toolchains then builtins.attrNames decl.toolchains else [ ]
    else
      [ ];

  # Filter to only Buck2-relevant toolchains (those with mappings and not skipped)
  buck2Toolchains = builtins.filter (
    name: mappings ? ${name} && !(mappings.${name}.skip or false)
  ) toolchainNames;

  # Collect all implicit dependencies transitively
  collectDeps =
    toolchains:
    let
      directDeps = builtins.concatMap (
        name: mappings.${name}.implicitDependencies or [ ]
      ) toolchains;
      # Only include deps that have mappings and aren't skipped
      validDeps = builtins.filter (
        name: mappings ? ${name} && !(mappings.${name}.skip or false)
      ) directDeps;
      allDeps = lib.unique (toolchains ++ validDeps);
    in
    # Recurse until stable (handle transitive deps)
    if allDeps == toolchains then toolchains else collectDeps allDeps;

  # All toolchains including implicit dependencies
  allToolchains = collectDeps buck2Toolchains;

  # Add always-include toolchains (like genrule)
  alwaysIncluded = builtins.filter (name: mappings.${name}.alwaysInclude or false) (
    builtins.attrNames mappings
  );

  finalToolchains = lib.unique (allToolchains ++ alwaysIncluded);

  # Generate load statements for BUCK file
  generateLoads =
    toolchains:
    let
      # Collect all unique load statements
      loads = lib.unique (
        builtins.concatMap (
          name:
          map (t: {
            path = t.load;
            rule = t.rule;
          }) (mappings.${name}.targets or [ ])
        ) toolchains
      );
      # Group by load path for cleaner output
      byPath = lib.groupBy (l: l.path) loads;
      loadStmts = lib.mapAttrsToList (
        path: rules: ''load("${path}", ${lib.concatMapStringsSep ", " (r: ''"${r.rule}"'') rules})''
      ) byPath;
    in
    lib.concatStringsSep "\n" loadStmts;

  # Generate target instantiations for BUCK file
  generateTargets =
    toolchains:
    let
      targets = builtins.concatMap (
        name:
        map (
          t:
          let
            attrs = t.attrs or { };
            attrLines =
              [ ''    name = "${t.name}",'' ]
              ++ [ ''    visibility = ${builtins.toJSON t.visibility},'' ]
              ++ (lib.mapAttrsToList (k: v: ''    ${k} = ${builtins.toJSON v},'') attrs);
          in
          ''
            ${t.rule}(
            ${lib.concatStringsSep "\n" attrLines}
            )
          ''
        ) (mappings.${name}.targets or [ ])
      ) toolchains;
    in
    lib.concatStringsSep "\n" targets;

  # Generate the complete BUCK file content
  buckFileContent = ''
    # Generated by turnkey - do not edit manually
    # Toolchains: ${lib.concatStringsSep ", " finalToolchains}

    ${generateLoads finalToolchains}

    ${generateTargets finalToolchains}
  '';

  # Toolchains cell derivation
  toolchainsCell = pkgs.runCommand "turnkey-toolchains-cell" { } ''
    mkdir -p $out

    # Create BUCK file
    cat > $out/BUCK <<'BUCK'
    ${buckFileContent}
    BUCK

    # Create cell identity .buckconfig
    cat > $out/.buckconfig <<'BUCKCONFIG'
    [cells]
        toolchains = .
        prelude = ${cfg.prelude.path}
    BUCKCONFIG
  '';

  # Generate buckconfig content
  buckconfigContent = ''
    # Generated by turnkey - do not edit manually
    [cells]
        root = .
        toolchains = ${toolchainsCell}
        prelude = ${cfg.prelude.path}

    [cell_aliases]
        config = prelude
        buck = none
        fbcode = none
        fbsource = none

    [parser]
        target_platform_detector_spec = target:root//...->prelude//platforms:default
  '';

  # Buckconfig file derivation
  buckconfig = pkgs.writeText "turnkey.buckconfig" buckconfigContent;

  # Get the actual buck2 package from the registry
  buck2Pkg =
    if turnkeyCfg.registry ? buck2 then
      turnkeyCfg.registry.buck2
    else
      throw "turnkey.buck2.enable requires 'buck2' in the registry";

  # Subcommands that support --config-file option
  configFileCommands = [
    "build"
    "test"
    "run"
    "install"
    "targets"
    "utargets"
    "ctargets"
    "query"
    "uquery"
    "cquery"
    "aquery"
    "bxl"
  ];

  # Wrapper script that injects --config-file after the subcommand
  # Note: --config-file is a subcommand option, only supported by certain commands
  buck2Wrapper = pkgs.writeShellScriptBin "buck2" ''
    set -euo pipefail

    # Turnkey-generated Buck2 wrapper
    # Toolchains cell: ${toolchainsCell}
    # Base config: ${buckconfig}

    # Subcommands that support --config-file
    CONFIG_FILE_COMMANDS=(${lib.concatStringsSep " " configFileCommands})

    # Extract the subcommand (first non-flag argument)
    args=("$@")
    subcommand=""
    pre_args=()
    post_args=()

    for i in "''${!args[@]}"; do
      arg="''${args[$i]}"
      if [[ -z "$subcommand" ]]; then
        if [[ "$arg" != -* ]]; then
          subcommand="$arg"
        else
          pre_args+=("$arg")
        fi
      else
        post_args+=("$arg")
      fi
    done

    # If no subcommand, just pass through (e.g., --help, --version)
    if [[ -z "$subcommand" ]]; then
      exec "${buck2Pkg}/bin/buck2" "$@"
    fi

    # Check if subcommand supports --config-file
    supports_config_file=false
    for cmd in "''${CONFIG_FILE_COMMANDS[@]}"; do
      if [[ "$subcommand" == "$cmd" ]]; then
        supports_config_file=true
        break
      fi
    done

    if [[ "$supports_config_file" == "true" ]]; then
      # Create temp config and inject --config-file
      TEMP_CONFIG=$(mktemp)
      trap "rm -f $TEMP_CONFIG" EXIT

      cat "${buckconfig}" > "$TEMP_CONFIG"

      if [[ -f .buckconfig ]]; then
        echo "" >> "$TEMP_CONFIG"
        echo "# Including project .buckconfig" >> "$TEMP_CONFIG"
        cat .buckconfig >> "$TEMP_CONFIG"
      fi

      exec "${buck2Pkg}/bin/buck2" "''${pre_args[@]}" "$subcommand" --config-file "$TEMP_CONFIG" "''${post_args[@]}"
    else
      # Pass through without --config-file
      exec "${buck2Pkg}/bin/buck2" "$@"
    fi
  '';

in
{
  options.turnkey.buck2 = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Enable Buck2 toolchain generation from toolchain.toml.

        When enabled, this module:
        1. Generates a toolchains cell with Buck2 toolchain rules
        2. Creates a wrapper script that injects Nix-managed cell paths
        3. Adds environment variables for debugging/inspection
      '';
    };

    prelude = {
      strategy = lib.mkOption {
        type = lib.types.enum [
          "bundled"
          "git"
          "nix"
          "path"
        ];
        default = "bundled";
        description = ''
          How to provide the Buck2 prelude cell:
          - bundled: Use Buck2's built-in bundled prelude (simplest)
          - git: Use a git external cell (requires gitOrigin and commitHash)
          - nix: Use a Nix derivation (requires path to be a derivation)
          - path: Use an explicit filesystem path
        '';
      };

      path = lib.mkOption {
        type = lib.types.either lib.types.path lib.types.str;
        default = "prelude";
        description = ''
          Path to the prelude cell.
          - For bundled: typically "prelude" (relative to project root)
          - For git: the local checkout path
          - For nix: a Nix derivation or store path
          - For path: an absolute or relative filesystem path
        '';
      };

      gitOrigin = lib.mkOption {
        type = lib.types.str;
        default = "https://github.com/facebook/buck2-prelude.git";
        description = "Git origin URL for the prelude (when strategy = git)";
      };

      commitHash = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "Git commit hash for the prelude (required when strategy = git)";
      };
    };
  };

  config = lib.mkIf (cfg.enable && turnkeyCfg.enable) {
    # Add the wrapper script to the shell (replaces buck2 in PATH)
    packages = [ buck2Wrapper ];

    # Export paths for debugging and inspection
    env = {
      TURNKEY_BUCK2_TOOLCHAINS_CELL = "${toolchainsCell}";
      TURNKEY_BUCK2_CONFIG = "${buckconfig}";
      TURNKEY_BUCK2_TOOLCHAINS = lib.concatStringsSep "," finalToolchains;
    };

    # Informational message on shell entry
    enterShell = ''
      echo "Buck2 configured by turnkey"
      echo "  Toolchains: ${lib.concatStringsSep ", " finalToolchains}"
      echo "  Cell: $TURNKEY_BUCK2_TOOLCHAINS_CELL"
    '';
  };
}
