# Whether the shell's dependency cells still match the deps files on disk,
# and the shell routine that re-evaluates the flake when they don't.
#
# nix-direnv decides whether its cached dev shell is fresh inside `use
# flake`, from the files watched at that point. The deps files are watched
# only later, by use_turnkey (the list comes from the flake), so a deps file
# regenerated by tk sync or tw never made nix-direnv re-evaluate: the shell
# kept the cells built from the old file. Instead, the flake records the
# content hash of each deps file a cell was built from, and use_turnkey
# compares them with the files on disk after `use flake`. Content, not
# mtime, decides, as it does for tw.
{ lib, pkgs }:

{
  # The deps files the cells were built from, with their content hashes:
  # [ { file, hash } ], file relative to the project root. A language gets
  # a cell from its deps file when the file exists in the flake
  # (nix/flake-parts/turnkey's languageCells); one the flake can't see, such
  # as a gitignored file, would never match, so it is left out.
  entries =
    {
      # nix/buck2/languages.nix
      languages,
      # The shell's Buck2 options, with each language's options
      buck2,
    }:
    lib.optionals buck2.enable (
      builtins.concatMap (
        language:
        let
          langCfg = buck2.${language.name};
        in
        lib.optional
          (langCfg.enable && builtins.isPath langCfg.depsFile && builtins.pathExists langCfg.depsFile)
          {
            file = language.depsFile langCfg;
            hash = builtins.hashFile "sha256" langCfg.depsFile;
          }
      ) languages
    );

  # Shell code defining _turnkey_refresh_cells, for use_turnkey to call
  # after regenerating the deps files. When a deps file differs from the one
  # its cell was built from, it invalidates nix-direnv's cached dev shell and
  # loads the calling .envrc again, which evaluates the flake and links the
  # new cells; it then succeeds, and the caller returns. It re-evaluates at
  # most once per load: a file still different after that is reported.
  refresh =
    entries:
    let
      sha256sum = "${pkgs.coreutils}/bin/sha256sum";
      touch = "${pkgs.coreutils}/bin/touch";
    in
    ''
      # Whether a file's content no longer has the given hash (or it is gone)
      _turnkey_deps_file_changed() {
        local file="$1" hash="$2" actual
        [ -f "$file" ] || return 0
        actual=$(${sha256sum} < "$file") || return 0
        [ "''${actual%% *}" != "$hash" ]
      }

      # The deps files that differ from the ones the cells were built from
      _turnkey_changed_deps_files() {
        :
        ${lib.concatMapStringsSep "\n  " (
          entry:
          "_turnkey_deps_file_changed ${lib.escapeShellArg entry.file} ${lib.escapeShellArg entry.hash} && echo ${lib.escapeShellArg entry.file}"
        ) entries}
      }

      _turnkey_refresh_cells() {
        local changed
        changed=$(_turnkey_changed_deps_files)
        [ -n "$changed" ] || return 1

        if [ -n "''${_turnkey_reevaluating:-}" ]; then
          log_status "turnkey: the dev shell's cells still don't match" $changed
          log_status "turnkey: run nix-direnv-reload, or check that the flake sees these files"
          return 1
        fi

        # The .envrc being loaded: the innermost sourced file
        local i envrc=""
        for ((i = 0; i < ''${#FUNCNAME[@]}; i++)); do
          if [ "''${FUNCNAME[$i]}" = source ]; then
            envrc="''${BASH_SOURCE[$i]}"
            break
          fi
        done
        [ -n "$envrc" ] || return 1

        log_status "turnkey: re-evaluating the flake for" $changed

        # Backdate nix-direnv's cached dev shells, so every watched file is
        # newer and `use flake` evaluates again. The cache stays in place for
        # nix-direnv to fall back to if evaluation fails.
        local rc
        for rc in "$(direnv_layout_dir)"/flake-profile*.rc; do
          [ -e "$rc" ] && ${touch} -t 197001010000 "$rc"
        done

        _turnkey_reevaluating=1
        source_env "$envrc"
        unset _turnkey_reevaluating
        return 0
      }
    '';
}
