# Whether the shell still matches the files it was built from on disk, and
# the shell routine that re-evaluates the flake when it doesn't: the deps
# files its dependency cells were built from, and, in turnkey's own
# repository, turnkey's Nix sources.
#
# nix-direnv decides whether its cached dev shell is fresh inside `use
# flake`, from the files watched at that point. These files are watched only
# later, by use_turnkey (the list comes from the flake), so a deps file
# regenerated by tk sync or tw, or an edit to turnkey's Nix code, never made
# nix-direnv re-evaluate: the shell kept the cells, tools and direnv library
# built from the old files. Instead, the flake records the content hash of
# each such file, and use_turnkey compares them with the files on disk after
# `use flake`. Content, not mtime, decides, as it does for tw.
{ lib, pkgs }:

{
  # The deps files the cells were built from, with their content hashes:
  # [ { file, hash } ], file relative to the project root. A language gets
  # a cell from its deps file when the file exists in the flake
  # (nix/flake-parts/turnkey's languageCells); one the flake can't see, such
  # as a gitignored file, would never match, so it is left out.
  entries =
    {
      # nix/buck2/languages.nix
      languages,
      # The shell's Buck2 options, with each language's options
      buck2,
    }:
    lib.optionals buck2.enable (
      builtins.concatMap (
        language:
        let
          langCfg = buck2.${language.name};
        in
        lib.optional
          (langCfg.enable && builtins.isPath langCfg.depsFile && builtins.pathExists langCfg.depsFile)
          {
            file = language.depsFile langCfg;
            hash = builtins.hashFile "sha256" langCfg.depsFile;
          }
      ) languages
    );

  # turnkey's Nix sources the shell was built from, as entries like the deps
  # files': every .nix and .patch file under turnkey's nix/, the files
  # use_turnkey watches for turnkey's own code. They are the project's files
  # only in turnkey's own repository, where the project's flake is turnkey's;
  # in a consumer project turnkey comes from the flake input, its sources
  # aren't on disk, and there are none.
  sourceEntries =
    {
      # The flake being loaded (flake-parts' self)
      project,
      # turnkey's flake
      turnkey,
    }:
    let
      root = turnkey.outPath;
      isSource = name: lib.hasSuffix ".nix" name || lib.hasSuffix ".patch" name;
      # The source files under a directory, relative to the root. Names
      # come from readDir, so they don't carry the flake source along.
      sourcesUnder =
        dir:
        lib.concatLists (
          lib.mapAttrsToList (
            name: type:
            let
              file = "${dir}/${name}";
            in
            if type == "directory" then sourcesUnder file else lib.optional (isSource name) file
          ) (builtins.readDir "${root}/${dir}")
        );
    in
    lib.optionals (project.outPath == root) (
      map (file: {
        inherit file;
        hash = builtins.hashFile "sha256" "${root}/${file}";
      }) (sourcesUnder "nix")
    );

  # Shell code defining _turnkey_refresh_shell, for use_turnkey to call
  # after regenerating the deps files. When a recorded file differs from the
  # one the shell was built from, it invalidates nix-direnv's cached dev shell
  # and loads the calling .envrc again, which evaluates the flake and links
  # the new cells; it then succeeds, and the caller returns. It re-evaluates
  # at most once per load: a file still different after that is reported.
  refresh =
    entries:
    let
      sha256sum = "${pkgs.coreutils}/bin/sha256sum";
      touch = "${pkgs.coreutils}/bin/touch";
      # sha256sum's output for the recorded files, as it is when none changed
      expectedSums = lib.concatMapStrings (entry: "${entry.hash}  ${entry.file}\n") entries;
    in
    ''
      # Whether a file's content no longer has the given hash (or it is gone)
      _turnkey_file_changed() {
        local file="$1" hash="$2" actual
        [ -f "$file" ] || return 0
        actual=$(${sha256sum} < "$file") || return 0
        [ "''${actual%% *}" != "$hash" ]
      }

      # The recorded files that differ from the ones the shell was built from
      _turnkey_changed_files() {
        :
        ${lib.optionalString (entries != [ ]) ''
          # The common case, nothing changed, costs one sha256sum over every
          # file; any difference, a missing file included, is then looked
          # at file by file
          local expected=${lib.escapeShellArg expectedSums}
          local actual
          if actual=$(${sha256sum} -- ${
            lib.escapeShellArgs (map (entry: entry.file) entries)
          } 2>/dev/null) && [ "$actual"$'\n' = "$expected" ]; then
            return 0
          fi
          ${lib.concatMapStringsSep "\n  " (
            entry:
            "_turnkey_file_changed ${lib.escapeShellArg entry.file} ${lib.escapeShellArg entry.hash} && echo ${lib.escapeShellArg entry.file}"
          ) entries}
        ''}
      }

      _turnkey_refresh_shell() {
        local changed
        changed=$(_turnkey_changed_files)
        [ -n "$changed" ] || return 1

        if [ -n "''${_turnkey_reevaluating:-}" ]; then
          log_status "turnkey: the dev shell still doesn't match" $changed
          log_status "turnkey: run nix-direnv-reload, or check that the flake sees these files"
          return 1
        fi

        # The .envrc being loaded: the innermost sourced file
        local i envrc=""
        for ((i = 0; i < ''${#FUNCNAME[@]}; i++)); do
          if [ "''${FUNCNAME[$i]}" = source ]; then
            envrc="''${BASH_SOURCE[$i]}"
            break
          fi
        done
        [ -n "$envrc" ] || return 1

        log_status "turnkey: re-evaluating the flake for" $changed

        # Backdate nix-direnv's cached dev shells, so every watched file is
        # newer and `use flake` evaluates again. The cache stays in place for
        # nix-direnv to fall back to if evaluation fails.
        local rc
        for rc in "$(direnv_layout_dir)"/flake-profile*.rc; do
          [ -e "$rc" ] && ${touch} -t 197001010000 "$rc"
        done

        _turnkey_reevaluating=1
        source_env "$envrc"
        unset _turnkey_reevaluating
        return 0
      }
    '';
}
