# Generate turnkey-direnv-lib.sh for use in .envrc
#
# This module creates a shell script containing the `use_turnkey` function
# that handles dependency regeneration (tk sync), symlink syncing, and
# watch_file declarations for the shell's deps rules.

{ lib, pkgs, config }:

let
  cfg = config.turnkey;
  buck2Cfg = cfg.buck2;

  # Teller lib for registry resolution (injected via flake-parts module)
  turnkeyLib = cfg.tellerLib;

  # The deps rules tk sync runs, as buck2.nix writes them into
  # .turnkey/sync.toml (nix/buck2/sync-config.nix); a shell without Buck2
  # has none
  syncRules = lib.optionals buck2Cfg.enable
    (import ../../buck2/sync-config.nix { inherit lib; } {
      languages = import ../../buck2/languages.nix { inherit pkgs lib; };
      buck2 = buck2Cfg;
    }).rules;
  ruleNames = map (rule: rule.name) syncRules;

  # turnkey's tk, from the registry (it is built in), or whatever tk is on PATH
  tk =
    if cfg.registry ? tk then "${turnkeyLib.resolveTool cfg.registry "tk" { }}/bin/tk" else "tk";

  # Helper functions (always included)
  helperFunctions = ''
    # === Turnkey direnv library ===
    # Generated by Nix - do not edit manually

    # Add devenv profile's fish completions to fish_complete_path
    # DEVENV_PROFILE is set by devenv before this runs
    if [ -n "$DEVENV_PROFILE" ]; then
      path_add fish_complete_path "$DEVENV_PROFILE/share/fish/vendor_completions.d"
    fi
  '';

  # Regenerate stale deps files: tk sync, for the rules passed as arguments
  # or all of them. tk decides what is stale, from .turnkey/sync.toml.
  regenFunction = ''
    _turnkey_regen() {
      if [ ! -e .turnkey/sync.toml ]; then return 0; fi
      if [ -n "''${TURNKEY_VERBOSE:-}" ]; then
        "${tk}" sync "$@" || echo "turnkey: tk sync failed (continuing anyway)"
      else
        "${tk}" --quiet sync "$@" || echo "turnkey: tk sync failed (continuing anyway)"
      fi
    }
  '';

  # Symlink sync function
  symlinkSyncFunction = ''
    _turnkey_sync_symlinks() {
      # .buckconfig
      if [ -n "''${TURNKEY_BUCK2_CONFIG:-}" ]; then
        if [ "$(readlink .buckconfig 2>/dev/null)" != "$TURNKEY_BUCK2_CONFIG" ]; then
          ln -sf "$TURNKEY_BUCK2_CONFIG" .buckconfig
          echo "turnkey: Synced .buckconfig"
        fi
      fi

      # Toolchains cell
      if [ -n "''${TURNKEY_BUCK2_TOOLCHAINS_CELL:-}" ]; then
        mkdir -p .turnkey
        if [ "$(readlink .turnkey/toolchains 2>/dev/null)" != "$TURNKEY_BUCK2_TOOLCHAINS_CELL" ]; then
          ln -sfn "$TURNKEY_BUCK2_TOOLCHAINS_CELL" .turnkey/toolchains
          echo "turnkey: Synced toolchains cell"
        fi
      fi

      # Dynamic cells (TURNKEY_CELL_*)
      for var in $(env | grep '^TURNKEY_CELL_' | cut -d= -f1); do
        local value="''${!var}"
        local cell_path="''${value%%:*}"
        local cell_deriv="''${value#*:}"
        if [ "$(readlink "$cell_path" 2>/dev/null)" != "$cell_deriv" ]; then
          mkdir -p "$(dirname "$cell_path")"
          ln -sfn "$cell_deriv" "$cell_path"
          echo "turnkey: Synced $cell_path"
        fi
      done
    }
  '';

  # Watch file declarations: turnkey's Nix, and each rule's sources and
  # target, so a regenerated deps file reloads the shell with its new cell
  watchFileDeclarations = ''
    _turnkey_watch_files() {
      watch_file nix/**/*.nix
      watch_file nix/**/*.patch
      ${lib.concatMapStringsSep "\n  " (file: "watch_file ${lib.escapeShellArg file}") (
        lib.unique (builtins.concatMap (rule: rule.sources ++ [ rule.target ]) syncRules)
      )}
    }
  '';

  # Main use_turnkey function. --only-<rule> and --skip-<rule> (and the
  # TURNKEY_ENABLE_<RULE> / TURNKEY_SKIP_<RULE> variables) name deps rules.
  useTurnkeyFunction = ''
    use_turnkey() {
      local skip_regen=0 skip_sync=0 skip_watch=0
      local only_rules="" skip_rules=""

      # Parse flags
      while [[ $# -gt 0 ]]; do
        case "$1" in
          --skip-regen) skip_regen=1 ;;
          --skip-sync)  skip_sync=1 ;;
          --skip-watch) skip_watch=1 ;;
          --only-*)     only_rules="$only_rules ''${1#--only-}" ;;
          --skip-*)     skip_rules="$skip_rules ''${1#--skip-}" ;;
          *) echo "turnkey: Unknown flag: $1" >&2 ;;
        esac
        shift
      done

      # Check env vars (flags take precedence)
      [[ -n "''${TURNKEY_SKIP_REGEN:-}" ]] && skip_regen=1

      # Build the list of rules to sync
      local rules=""
      if [[ -n "$only_rules" ]]; then
        # Flags: --only-<rule> take highest precedence
        rules="$only_rules"
      elif [[ -n "''${TURNKEY_SKIP_ALL:-}" ]]; then
        # SKIP_ALL mode: start empty, add ENABLE_* rules
        ${lib.concatMapStringsSep "\n    " (
          name:
          ''[[ -n "''${TURNKEY_ENABLE_${lib.toUpper name}:-}" ]] && rules="$rules ${name}"''
        ) ruleNames}
      else
        # Default mode: every rule, minus SKIP_* rules
        rules="${lib.concatStringsSep " " ruleNames}"
        ${lib.concatMapStringsSep "\n    " (
          name:
          ''[[ -n "''${TURNKEY_SKIP_${lib.toUpper name}:-}" ]] && skip_rules="$skip_rules ${name}"''
        ) ruleNames}
      fi

      # Regenerate deps
      if [[ "$skip_regen" != "1" ]]; then
        local selected=""
        for rule in $rules; do
          if [[ ! " $skip_rules " =~ " $rule " ]]; then
            selected="$selected $rule"
          fi
        done
        if [[ -n "$selected" ]]; then
          _turnkey_regen $selected
        fi
      fi

      # Sync symlinks
      if [[ "$skip_sync" != "1" ]]; then
        _turnkey_sync_symlinks
      fi

      # Watch files
      if [[ "$skip_watch" != "1" ]]; then
        _turnkey_watch_files
      fi
    }
  '';

  # Complete script
  scriptContent = lib.concatStringsSep "\n\n" [
    helperFunctions
    regenFunction
    symlinkSyncFunction
    watchFileDeclarations
    useTurnkeyFunction
  ];

in
pkgs.writeShellScript "turnkey-direnv-lib.sh" scriptContent
