# Ring symbol lists for prefix headers
#
# These symbols are extracted from ring's build.rs SYMBOLS_TO_PREFIX and
# SYMBOLS_TO_RENAME arrays. They need to be prefixed to avoid symbol
# conflicts when linking multiple versions of ring.
#
# Reference: https://github.com/briansmith/ring/blob/main/build.rs

{ lib }:

{
  # SYMBOLS_TO_RENAME: symbols that get renamed without prefix
  # These map old OpenSSL-style names to ring's new names
  symbolRenames = [
    { old = "ecp_nistz256_point_double"; new = "p256_point_double"; }
    { old = "ecp_nistz256_point_add"; new = "p256_point_add"; }
    { old = "ecp_nistz256_point_add_affine"; new = "p256_point_add_affine"; }
    { old = "ecp_nistz256_ord_mul_mont"; new = "p256_scalar_mul_mont"; }
    { old = "ecp_nistz256_ord_sqr_mont"; new = "p256_scalar_sqr_rep_mont"; }
    { old = "ecp_nistz256_mul_mont"; new = "p256_mul_mont"; }
    { old = "ecp_nistz256_sqr_mont"; new = "p256_sqr_mont"; }
  ];

  # SYMBOLS_TO_PREFIX: symbols that get prefixed with ring_core_0_17_<patch>__
  symbolsToPrefix = [
    "adx_bmi2_available"
    "avx2_available"
    "CRYPTO_memcmp"
    "CRYPTO_poly1305_finish"
    "CRYPTO_poly1305_finish_neon"
    "CRYPTO_poly1305_init"
    "CRYPTO_poly1305_init_neon"
    "CRYPTO_poly1305_update"
    "CRYPTO_poly1305_update_neon"
    "ChaCha20_ctr32"
    "ChaCha20_ctr32_avx2"
    "ChaCha20_ctr32_neon"
    "ChaCha20_ctr32_nohw"
    "ChaCha20_ctr32_ssse3"
    "ChaCha20_ctr32_ssse3_4x"
    "LIMB_is_zero"
    "LIMBS_add_mod"
    "LIMBS_are_zero"
    "LIMBS_equal"
    "LIMBS_less_than"
    "LIMBS_reduce_once"
    "LIMBS_select_512_32"
    "LIMBS_shl_mod"
    "LIMBS_sub_mod"
    "LIMBS_window5_split_window"
    "LIMBS_window5_unsplit_window"
    "LIMB_shr"
    "OPENSSL_cpuid_setup"
    "aes_gcm_dec_kernel"
    "aes_gcm_dec_update_vaes_avx2"
    "aes_gcm_enc_kernel"
    "aes_gcm_enc_update_vaes_avx2"
    "aes_hw_ctr32_encrypt_blocks"
    "aes_hw_set_encrypt_key"
    "aes_hw_set_encrypt_key_alt"
    "aes_hw_set_encrypt_key_base"
    "aes_nohw_ctr32_encrypt_blocks"
    "aes_nohw_encrypt"
    "aes_nohw_set_encrypt_key"
    "aesni_gcm_decrypt"
    "aesni_gcm_encrypt"
    "bn_from_montgomery_in_place"
    "bn_gather5"
    "bn_mul_mont"
    "bn_mul_mont_nohw"
    "bn_mul4x_mont"
    "bn_mulx4x_mont"
    "bn_mul8x_mont_neon"
    "bn_mul4x_mont_gather5"
    "bn_mulx4x_mont_gather5"
    "bn_neg_inv_mod_r_u64"
    "bn_power5_nohw"
    "bn_powerx5"
    "bn_scatter5"
    "bn_sqr8x_internal"
    "bn_sqr8x_mont"
    "bn_sqrx8x_internal"
    "bsaes_ctr32_encrypt_blocks"
    "bssl_constant_time_test_conditional_memcpy"
    "bssl_constant_time_test_conditional_memxor"
    "bssl_constant_time_test_main"
    "chacha20_poly1305_open"
    "chacha20_poly1305_open_avx2"
    "chacha20_poly1305_open_sse41"
    "chacha20_poly1305_seal"
    "chacha20_poly1305_seal_avx2"
    "chacha20_poly1305_seal_sse41"
    "ecp_nistz256_mul_mont_adx"
    "ecp_nistz256_mul_mont_nohw"
    "ecp_nistz256_ord_mul_mont_adx"
    "ecp_nistz256_ord_mul_mont_nohw"
    "ecp_nistz256_ord_sqr_mont_adx"
    "ecp_nistz256_ord_sqr_mont_nohw"
    "ecp_nistz256_point_add_adx"
    "ecp_nistz256_point_add_nohw"
    "ecp_nistz256_point_add_affine_adx"
    "ecp_nistz256_point_add_affine_nohw"
    "ecp_nistz256_point_double_adx"
    "ecp_nistz256_point_double_nohw"
    "ecp_nistz256_select_w5_avx2"
    "ecp_nistz256_select_w5_nohw"
    "ecp_nistz256_select_w7_avx2"
    "ecp_nistz256_select_w7_nohw"
    "ecp_nistz256_sqr_mont_adx"
    "ecp_nistz256_sqr_mont_nohw"
    "fiat_curve25519_adx_mul"
    "fiat_curve25519_adx_square"
    "gcm_ghash_avx"
    "gcm_ghash_clmul"
    "gcm_ghash_neon"
    "gcm_ghash_vpclmulqdq_avx2_1"
    "gcm_gmult_clmul"
    "gcm_gmult_neon"
    "gcm_init_avx"
    "gcm_init_clmul"
    "gcm_init_neon"
    "gcm_init_nohw"
    "gcm_ghash_nohw"
    "gcm_init_vpclmulqdq_avx2"
    "k25519Precomp"
    "limbs_mul_add_limb"
    "little_endian_bytes_from_scalar"
    "ecp_nistz256_neg"
    "ecp_nistz256_select_w5"
    "ecp_nistz256_select_w7"
    "neon_available"
    "p256_mul_mont"
    "p256_point_add"
    "p256_point_add_affine"
    "p256_point_double"
    "p256_point_mul"
    "p256_point_mul_base"
    "p256_point_mul_base_vartime"
    "p256_scalar_mul_mont"
    "p256_scalar_sqr_rep_mont"
    "p256_sqr_mont"
    "p384_elem_div_by_2"
    "p384_elem_mul_mont"
    "p384_elem_neg"
    "p384_elem_sub"
    "p384_point_add"
    "p384_point_double"
    "p384_point_mul"
    "p384_scalar_mul_mont"
    "openssl_poly1305_neon2_addmulmod"
    "openssl_poly1305_neon2_blocks"
    "sha256_block_data_order"
    "sha256_block_data_order_avx"
    "sha256_block_data_order_ssse3"
    "sha256_block_data_order_hw"
    "sha256_block_data_order_neon"
    "sha256_block_data_order_nohw"
    "sha256_block_data_order_avx2"
    "sha512_block_data_order"
    "sha512_block_data_order_avx"
    "sha512_block_data_order_hw"
    "sha512_block_data_order_neon"
    "sha512_block_data_order_nohw"
    "sha512_block_data_order_avx2"
    "vpaes_ctr32_encrypt_blocks"
    "vpaes_encrypt"
    "vpaes_encrypt_key_to_bsaes"
    "vpaes_set_encrypt_key"
    "x25519_NEON"
    "x25519_fe_invert"
    "x25519_fe_isnegative"
    "x25519_fe_mul_ttt"
    "x25519_fe_neg"
    "x25519_fe_tobytes"
    "x25519_ge_double_scalarmult_vartime"
    "x25519_ge_frombytes_vartime"
    "x25519_ge_scalarmult_base"
    "x25519_ge_scalarmult_base_adx"
    "x25519_public_from_private_generic_masked"
    "x25519_sc_mask"
    "x25519_sc_muladd"
    "x25519_sc_reduce"
    "x25519_scalar_mult_adx"
    "x25519_scalar_mult_generic_masked"
    "OPENSSL_ia32cap_P"
  ];

  # C source files to compile for x86_64-linux
  cSources = [
    "crypto/curve25519/curve25519.c"
    "crypto/fipsmodule/aes/aes_nohw.c"
    "crypto/fipsmodule/bn/montgomery.c"
    "crypto/fipsmodule/bn/montgomery_inv.c"
    "crypto/fipsmodule/ec/ecp_nistz.c"
    "crypto/fipsmodule/ec/gfp_p256.c"
    "crypto/fipsmodule/ec/gfp_p384.c"
    "crypto/fipsmodule/ec/p256.c"
    "crypto/fipsmodule/ec/p256-nistz.c"
    "crypto/limbs/limbs.c"
    "crypto/mem.c"
    "crypto/poly1305/poly1305.c"
    "crypto/crypto.c"
    "crypto/cpu_intel.c"
    "crypto/curve25519/curve25519_64_adx.c"
  ];

  # Assembly files for x86_64-linux (ELF format)
  asmSources = [
    "pregenerated/chacha-x86_64-elf.S"
    "pregenerated/aesni-gcm-x86_64-elf.S"
    "pregenerated/aesni-x86_64-elf.S"
    "pregenerated/ghash-x86_64-elf.S"
    "pregenerated/vpaes-x86_64-elf.S"
    "pregenerated/x86_64-mont-elf.S"
    "pregenerated/x86_64-mont5-elf.S"
    "pregenerated/p256-x86_64-asm-elf.S"
    "pregenerated/sha256-x86_64-elf.S"
    "pregenerated/sha512-x86_64-elf.S"
    "pregenerated/chacha20_poly1305_x86_64-elf.S"
    "pregenerated/aes-gcm-avx2-x86_64-elf.S"
    "third_party/fiat/asm/fiat_curve25519_adx_mul.S"
    "third_party/fiat/asm/fiat_curve25519_adx_square.S"
  ];
}
