//! `.turnkey/sync.toml`: what a turnkey project syncs, and how
//!
//! The file is generated by turnkey's shell from its language records
//! (`nix/buck2/languages.nix`), and defines:
//!
//! - dependency staleness rules (`go.mod` → `go-deps.toml`), `[[deps]]`;
//! - tool wrapper rules, for `tw`, `[[wrappers]]`;
//! - rules sync's settings, conditions and languages.
//!
//! ```toml
//! [[deps]]
//! name = "go"
//! sources = ["go.mod", "go.sum"]
//! target = "go-deps.toml"
//! generator = ["godeps-gen", "--go-mod", "go.mod", "--go-sum", "go.sum"]
//!
//! [[languages]]
//! name = "go"
//! cell = "godeps"
//! deps_file = "go-deps.toml"
//!
//! [conditions]
//! settings = "toolchains//conditions"
//!
//! [[conditions.platforms]]
//! os = "linux"
//! cpu = "x86_64"
//! ```
//!
//! Keys are read as the Go version of this module read them (go-toml v2):
//! an unknown key is ignored, and a key matches a field whatever its case
//! (`Name` sets `name`).

use anyhow::{Context, Result, bail};
use conditions::{Platform, Space};
use serde::Deserialize;
use std::path::{Path, PathBuf};

use gostd::filepath;

/// Where the sync config is, relative to the project root
pub const DEFAULT_CONFIG_PATH: &str = ".turnkey/sync.toml";

/// The whole sync configuration
#[derive(Debug, Clone, Default, PartialEq, Eq, Deserialize)]
#[serde(default)]
pub struct Config {
    /// Dependency staleness rules: when dependency files (go.mod,
    /// Cargo.toml) change, which dependency declarations to regenerate
    pub deps: Vec<DepsRule>,

    /// Tool wrapper rules: which native tools (go, cargo, uv) trigger a
    /// sync when they modify dependency files
    pub wrappers: Vec<WrapperRule>,

    /// Automatic `rules.star` synchronization
    pub rules: RulesConfig,

    /// The build configurations rules sync evaluates, for deps that differ
    /// between them
    pub conditions: ConditionsConfig,

    /// The languages turnkey manages dependencies for, one per language
    /// record (turnkey's nix/buck2/languages.nix)
    pub languages: Vec<Language>,
}

/// What rules sync knows of a language from its record: where the
/// language's external deps are
#[derive(Debug, Clone, Default, PartialEq, Eq, Deserialize)]
#[serde(default)]
pub struct Language {
    /// The record's name, e.g. "go" or "javascript"
    pub name: String,

    /// The Buck2 cell holding the language's external deps (e.g. "godeps")
    pub cell: String,

    /// The deps file the cell is built from, relative to the project root
    /// (e.g. "go-deps.toml")
    pub deps_file: String,
}

/// The build configurations rules sync evaluates, from turnkey's Nix
/// options
#[derive(Debug, Clone, Default, PartialEq, Eq, Deserialize)]
#[serde(default)]
pub struct ConditionsConfig {
    /// The Buck2 package holding turnkey's combined config_settings, one
    /// per platform, named "<os>-<cpu>" (e.g. "toolchains//conditions")
    pub settings: String,

    /// The platforms turnkey builds for (buck2.platforms)
    pub platforms: Vec<Platform>,

    /// The Go build tags allowed to vary per configuration
    /// (buck2.go.allowedBuildTags, .buckconfig's go.allowed_build_tags)
    pub go_tags: Vec<String>,
}

/// Automatic `rules.star` synchronization
#[derive(Debug, Clone, Default, PartialEq, Eq, Deserialize)]
#[serde(default)]
pub struct RulesConfig {
    /// Whether rules.star sync is active: tk checks and syncs rules.star
    /// files before build commands
    pub enabled: bool,

    /// Whether stale rules.star files are updated (the default) or only
    /// warned about
    pub auto_sync: Option<bool>,

    /// Fail when rules.star files would change, for CI to check they are
    /// committed up to date
    pub strict: bool,
}

impl ConditionsConfig {
    /// The configuration space of the configured platforms
    pub fn space(&self) -> Space {
        Space::new(&self.platforms, &self.settings)
    }
}

impl RulesConfig {
    /// Whether auto-sync is enabled (defaults to true)
    pub fn is_auto_sync(&self) -> bool {
        self.auto_sync.unwrap_or(true)
    }
}

/// A staleness rule for dependency generation
#[derive(Debug, Clone, Default, PartialEq, Eq, Deserialize)]
#[serde(default)]
pub struct DepsRule {
    /// A human-readable identifier for this rule
    pub name: String,

    /// The files to watch for changes (globs supported), e.g.
    /// `["go.mod", "go.sum"]`, `["**/Cargo.toml", "**/Cargo.lock"]`
    pub sources: Vec<String>,

    /// The file to generate when sources change
    pub target: String,

    /// When set, a top-level key of the target (a TOML file) whose array
    /// lists more sources, relative to the project root: files only the
    /// generator can find, such as a Cargo workspace's member manifests. A
    /// target without that key is stale.
    pub target_sources: String,

    /// The command that regenerates the target, run from the project root;
    /// its stdout is the target
    pub generator: Vec<String>,
}

/// A tool wrapper rule: when the wrapped tool modifies dependency files,
/// its deps rule is regenerated
#[derive(Debug, Clone, Default, PartialEq, Eq, Deserialize)]
#[serde(default)]
pub struct WrapperRule {
    /// A human-readable identifier for this wrapper (e.g. "go", "cargo")
    pub name: String,

    /// The underlying tool to wrap (e.g. "go", "cargo", "uv")
    pub command: String,

    /// The subcommands that may modify dependency files, e.g.
    /// `["get", "mod"]` for go, `["add", "remove", "update"]` for cargo
    pub mutating_subcommands: Vec<String>,

    /// The files to monitor for changes, relative to the project root
    pub watch_files: Vec<String>,

    /// The name of the `[[deps]]` rule to run when the files change
    pub deps_rule: String,

    /// Commands run, in order, after the tool when the files changed and
    /// before the sync, e.g. `["go mod tidy"]`
    pub post_commands: Vec<String>,
}

impl WrapperRule {
    /// Whether subcommand may modify dependency files
    pub fn is_mutating_subcommand(&self, subcommand: &str) -> bool {
        self.mutating_subcommands.iter().any(|m| m == subcommand)
    }
}

impl Config {
    /// Reads the config file at path
    pub fn load(path: &Path) -> Result<Config> {
        let data = std::fs::read(path).context("failed to read config")?;
        Config::parse(&data)
    }

    /// Loads the config from [`DEFAULT_CONFIG_PATH`] under root; a project
    /// without one has an empty config
    pub fn load_default_from(root: &Path) -> Result<Config> {
        let path = filepath::join(&[root, Path::new(DEFAULT_CONFIG_PATH)]);
        if let Err(e) = std::fs::metadata(&path)
            && e.kind() == std::io::ErrorKind::NotFound
        {
            return Ok(Config::default());
        }
        Config::load(&path)
    }

    /// Parses the config from TOML
    pub fn parse(data: &[u8]) -> Result<Config> {
        let parsed = std::str::from_utf8(data)
            .map_err(anyhow::Error::from)
            .and_then(|text| Ok(toml::from_str::<Folded>(text)?))
            .and_then(|Folded(value)| Ok(value.try_into::<Config>()?));
        parsed.context("failed to parse config")
    }

    /// The wrapper rule for command, if any
    pub fn find_wrapper(&self, command: &str) -> Option<&WrapperRule> {
        self.wrappers.iter().find(|w| w.command == command)
    }

    /// The deps rule named name, if any
    pub fn find_deps_rule(&self, name: &str) -> Option<&DepsRule> {
        self.deps.iter().find(|r| r.name == name)
    }

    /// Checks the config for common errors
    pub fn validate(&self) -> Result<()> {
        for (i, r) in self.deps.iter().enumerate() {
            if r.name.is_empty() {
                bail!("deps rule {i}: name is required");
            }
            if r.sources.is_empty() {
                bail!("deps rule {:?}: at least one source is required", r.name);
            }
            if r.target.is_empty() {
                bail!("deps rule {:?}: target is required", r.name);
            }
            if r.generator.is_empty() {
                bail!("deps rule {:?}: generator command is required", r.name);
            }
        }

        let mut seen = std::collections::HashSet::new();
        for (i, l) in self.languages.iter().enumerate() {
            if l.name.is_empty() {
                bail!("language {i}: name is required");
            }
            if !seen.insert(&l.name) {
                bail!("language {:?}: listed twice", l.name);
            }
            if l.cell.is_empty() {
                bail!("language {:?}: cell is required", l.name);
            }
            if l.deps_file.is_empty() {
                bail!("language {:?}: deps_file is required", l.name);
            }
        }

        for (i, r) in self.wrappers.iter().enumerate() {
            if r.name.is_empty() {
                bail!("wrapper rule {i}: name is required");
            }
            if r.command.is_empty() {
                bail!("wrapper rule {:?}: command is required", r.name);
            }
            if r.mutating_subcommands.is_empty() {
                bail!(
                    "wrapper rule {:?}: at least one mutating_subcommands is required",
                    r.name
                );
            }
            if r.watch_files.is_empty() {
                bail!(
                    "wrapper rule {:?}: at least one watch_files is required",
                    r.name
                );
            }
            if r.deps_rule.is_empty() {
                bail!("wrapper rule {:?}: deps_rule is required", r.name);
            }
            // The referenced deps rule must exist
            if self.find_deps_rule(&r.deps_rule).is_none() {
                bail!(
                    "wrapper rule {:?}: deps_rule {:?} not found",
                    r.name,
                    r.deps_rule
                );
            }
        }

        Ok(())
    }
}

/// A TOML document with every table key lowercased, which is how go-toml
/// v2 matches a key to a struct field when the exact key doesn't match:
/// every field of the config is lowercase, and the config holds no map of
/// its own keys, so a lowercased key reaches the field go-toml would set.
/// Two keys of a table that fold to the same field set it in document
/// order, so the later one wins, as with go-toml.
struct Folded(toml::Value);

impl<'de> Deserialize<'de> for Folded {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        d.deserialize_any(FoldVisitor)
    }
}

struct FoldVisitor;

impl<'de> serde::de::Visitor<'de> for FoldVisitor {
    type Value = Folded;

    fn expecting(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("a TOML value")
    }

    fn visit_bool<E>(self, v: bool) -> Result<Folded, E> {
        Ok(Folded(toml::Value::Boolean(v)))
    }

    fn visit_i64<E>(self, v: i64) -> Result<Folded, E> {
        Ok(Folded(toml::Value::Integer(v)))
    }

    fn visit_u64<E: serde::de::Error>(self, v: u64) -> Result<Folded, E> {
        i64::try_from(v)
            .map(|v| Folded(toml::Value::Integer(v)))
            .map_err(|_| E::custom("integer out of range"))
    }

    fn visit_f64<E>(self, v: f64) -> Result<Folded, E> {
        Ok(Folded(toml::Value::Float(v)))
    }

    fn visit_str<E>(self, v: &str) -> Result<Folded, E> {
        Ok(Folded(toml::Value::String(v.to_owned())))
    }

    fn visit_string<E>(self, v: String) -> Result<Folded, E> {
        Ok(Folded(toml::Value::String(v)))
    }

    fn visit_seq<A: serde::de::SeqAccess<'de>>(self, mut seq: A) -> Result<Folded, A::Error> {
        let mut items = Vec::new();
        while let Some(Folded(item)) = seq.next_element()? {
            items.push(item);
        }
        Ok(Folded(toml::Value::Array(items)))
    }

    fn visit_map<A: serde::de::MapAccess<'de>>(self, mut map: A) -> Result<Folded, A::Error> {
        let mut table = toml::Table::new();
        while let Some(key) = map.next_key::<String>()? {
            let Folded(value) = map.next_value()?;
            table.insert(key.to_lowercase(), value);
        }
        Ok(Folded(toml::Value::Table(table)))
    }
}

/// The project root dir is in: the nearest of dir and its ancestors
/// holding a `.buckconfig` or a `.turnkey/sync.toml`. None when there is
/// none, dir being outside any project; what to do then is the caller's
/// (tk runs from dir, tw runs the tool untouched).
///
/// Either file marks a root: tk needs .buckconfig to run buck2, tw needs
/// sync.toml to know what to sync, and a turnkey shell writes both at the
/// project's top, so the nearest of either is the same directory for both.
pub fn find_root(dir: &Path) -> Option<PathBuf> {
    let mut dir = filepath::clean(dir);
    loop {
        for marker in [".buckconfig", DEFAULT_CONFIG_PATH] {
            if std::fs::metadata(filepath::join(&[dir.as_path(), Path::new(marker)])).is_ok() {
                return Some(dir);
            }
        }
        let parent = filepath::dir(&dir);
        if parent == dir {
            return None;
        }
        dir = parent;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse() {
        let cfg = Config::parse(
            br#"
[[deps]]
name = "go"
sources = ["go.mod", "go.sum"]
target = "go-deps.toml"
generator = ["godeps-gen", "--go-mod", "go.mod", "--go-sum", "go.sum"]

[[deps]]
name = "rust"
sources = ["Cargo.toml", "Cargo.lock"]
target = "rust-deps.toml"
generator = ["cargo-deps-gen"]
"#,
        )
        .unwrap();

        assert_eq!(cfg.deps.len(), 2);
        assert_eq!(cfg.deps[0].name, "go");
        assert_eq!(cfg.deps[0].sources.len(), 2);
        assert_eq!(cfg.deps[0].target, "go-deps.toml");
        assert_eq!(cfg.deps[0].generator.len(), 5);
    }

    #[test]
    fn validate() {
        for (name, config, want_err) in [
            (
                "valid",
                r#"
[[deps]]
name = "go"
sources = ["go.mod"]
target = "go-deps.toml"
generator = ["godeps-gen"]
"#,
                false,
            ),
            (
                "missing name",
                r#"
[[deps]]
sources = ["go.mod"]
target = "go-deps.toml"
generator = ["godeps-gen"]
"#,
                true,
            ),
            (
                "missing sources",
                r#"
[[deps]]
name = "go"
target = "go-deps.toml"
generator = ["godeps-gen"]
"#,
                true,
            ),
            (
                "missing target",
                r#"
[[deps]]
name = "go"
sources = ["go.mod"]
generator = ["godeps-gen"]
"#,
                true,
            ),
            (
                "missing generator",
                r#"
[[deps]]
name = "go"
sources = ["go.mod"]
target = "go-deps.toml"
"#,
                true,
            ),
            (
                "language without a cell",
                r#"
[[languages]]
name = "go"
deps_file = "go-deps.toml"
"#,
                true,
            ),
            (
                "language without a deps file",
                r#"
[[languages]]
name = "go"
cell = "godeps"
"#,
                true,
            ),
            (
                "language listed twice",
                r#"
[[languages]]
name = "go"
cell = "godeps"
deps_file = "go-deps.toml"

[[languages]]
name = "go"
cell = "otherdeps"
deps_file = "go-deps.toml"
"#,
                true,
            ),
            ("empty config", "", false),
        ] {
            let cfg = Config::parse(config.as_bytes()).unwrap_or_else(|e| panic!("{name}: {e:#}"));
            assert_eq!(cfg.validate().is_err(), want_err, "{name}");
        }
    }

    #[test]
    fn load_default() {
        // A directory without a config file
        let cfg = Config::load_default_from(Path::new("/nonexistent")).unwrap();
        assert!(cfg.deps.is_empty());

        let dir = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(dir.path().join(".turnkey")).unwrap();
        std::fs::write(
            dir.path().join(".turnkey/sync.toml"),
            r#"
[[deps]]
name = "test"
sources = ["test.txt"]
target = "out.txt"
generator = ["cat"]
"#,
        )
        .unwrap();

        let cfg = Config::load_default_from(dir.path()).unwrap();
        assert_eq!(cfg.deps.len(), 1);
        assert_eq!(cfg.deps[0].name, "test");
    }

    // A sync.toml generated before the [rules.go] settings were removed
    // still loads: its section is ignored.
    #[test]
    fn load_ignores_removed_rules_go() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("sync.toml");
        std::fs::write(
            &path,
            r#"[rules]
enabled = true
auto_sync = false

[rules.go]
internal_prefix = "//src/go"
external_cell = "godeps"
"#,
        )
        .unwrap();
        let cfg = Config::load(&path).unwrap();
        assert!(
            cfg.rules.enabled && !cfg.rules.is_auto_sync(),
            "{:?}",
            cfg.rules
        );
    }

    // The platforms (buck2.platforms) and the combined config_settings'
    // package are read from [conditions].
    #[test]
    fn load_conditions() {
        let cfg = Config::parse(
            br#"[conditions]
settings = "toolchains//conditions"

[[conditions.platforms]]
os = "linux"
cpu = "x86_64"

[[conditions.platforms]]
os = "macos"
cpu = "arm64"
"#,
        )
        .unwrap();
        let platform = |os: &str, cpu: &str| Platform {
            os: os.into(),
            cpu: cpu.into(),
        };
        assert_eq!(
            cfg.conditions.platforms,
            [platform("linux", "x86_64"), platform("macos", "arm64")]
        );
        assert_eq!(cfg.conditions.settings, "toolchains//conditions");
        assert_eq!(cfg.conditions.space().configurations.len(), 2);
    }

    // Each language's cell and deps file are read from [[languages]], in
    // order.
    #[test]
    fn load_languages() {
        let cfg = Config::parse(
            br#"[[languages]]
name = "go"
cell = "godeps"
deps_file = "go-deps.toml"

[[languages]]
name = "javascript"
cell = "jsdeps"
deps_file = "web/js-deps.toml"
"#,
        )
        .unwrap();
        let language = |name: &str, cell: &str, deps_file: &str| Language {
            name: name.into(),
            cell: cell.into(),
            deps_file: deps_file.into(),
        };
        assert_eq!(
            cfg.languages,
            [
                language("go", "godeps", "go-deps.toml"),
                language("javascript", "jsdeps", "web/js-deps.toml"),
            ]
        );
        cfg.validate().unwrap();
    }

    // go-toml v2 matches a key to a field whatever its case, and ignores
    // keys it has no field for
    #[test]
    fn keys_match_fields_whatever_their_case() {
        let cfg = Config::parse(
            br#"[[Deps]]
Name = "go"
SOURCES = ["go.mod"]
target = "go-deps.toml"
Generator = ["godeps-gen"]
unknown = 1
"#,
        )
        .unwrap();
        assert_eq!(cfg.deps.len(), 1);
        assert_eq!(cfg.deps[0].name, "go");
        assert_eq!(cfg.deps[0].sources, ["go.mod"]);
        assert_eq!(cfg.deps[0].generator, ["godeps-gen"]);

        // Two keys for one field: the later one wins
        let cfg = Config::parse(b"[[deps]]\nname = \"a\"\nNAME = \"b\"\n").unwrap();
        assert_eq!(cfg.deps[0].name, "b");
        let cfg = Config::parse(b"[[deps]]\nNAME = \"a\"\nname = \"b\"\n").unwrap();
        assert_eq!(cfg.deps[0].name, "b");
    }

    #[test]
    fn a_mistyped_value_does_not_parse() {
        assert!(Config::parse(b"[[deps]]\nname = 1\n").is_err());
        assert!(Config::parse(b"[rules]\nenabled = \"yes\"\n").is_err());
        assert!(Config::parse(b"deps = 3\n").is_err());
    }

    fn touch(path: &Path) {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(path, "").unwrap();
    }

    fn mkdir(path: PathBuf) -> PathBuf {
        std::fs::create_dir_all(&path).unwrap();
        path
    }

    #[test]
    fn find_root_buckconfig() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path();
        touch(&root.join(".buckconfig"));
        let dir = mkdir(root.join("src/cmd"));
        assert_eq!(find_root(&dir).as_deref(), Some(root));
    }

    #[test]
    fn find_root_sync_toml() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path();
        touch(&root.join(DEFAULT_CONFIG_PATH));
        let dir = mkdir(root.join("src"));
        assert_eq!(find_root(&dir).as_deref(), Some(root));
    }

    #[test]
    fn find_root_nearest_wins() {
        let tmp = tempfile::tempdir().unwrap();
        let outer = tmp.path();
        touch(&outer.join(".buckconfig"));
        let inner = outer.join("examples/app");
        touch(&inner.join(DEFAULT_CONFIG_PATH));
        let dir = mkdir(inner.join("src"));
        assert_eq!(find_root(&dir), Some(inner));
    }

    #[test]
    fn find_root_a_bare_turnkey_dir_is_not_a_root() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = mkdir(tmp.path().join(".turnkey"));
        // The temporary directory may itself be inside a project
        if find_root(&tmp.path().join("..")).is_none() {
            assert_eq!(find_root(dir.parent().unwrap()), None);
        }
    }
}
