# Python example with external package dependencies
#
# NOTE: External Python packages require third-party setup.
# Buck2 doesn't have built-in pip integration - you need to either:
# 1. Vendor packages in a third-party directory
# 2. Use prebuilt wheel targets
# 3. Use a pip-to-buck tool to generate targets
#
# Meta's internal tooling for this isn't fully open-sourced.
# Community options include rules_python patterns or custom pip integration.

load("@prelude//:rules.bzl", "python_binary")

# This target will fail until third-party packages are available
python_binary(
    name = "python-hello-deps",
    main = "hello.py",
    # Uncomment when third-party packages are available:
    # deps = [
    #     "//third-party/python:click",
    # ],
    visibility = ["PUBLIC"],
)
