// Package cellfresh detects when Buck2 cell symlinks change and kills the
// daemon so it picks up the new store paths.
//
// When Nix rebuilds a dependency cell (e.g. due to a fixup change or
// nix flake update), the .turnkey/<cell> symlink changes to point to a
// new Nix store path. Buck2's daemon doesn't detect this — it caches
// the resolved cell contents from the old path. This package compares
// current symlink targets against a saved state file and runs "buck2 kill"
// when any target has changed.
package cellfresh

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

const (
	turnkeyDir    = ".turnkey"
	stateFileName = ".cell-targets"
	nixStoreDir   = "/nix/store/"
)

// Check compares current cell symlink targets against saved state.
// If any have changed, it kills the Buck2 daemon and writes updated state.
// On first run (no state file), it writes state without killing.
//
// verbose and quiet control output on w. Errors are returned only for
// I/O failures, not for missing state or kill failure.
func Check(root string, verbose, quiet bool, w io.Writer) error {
	current := readSymlinkTargets(root)
	if len(current) == 0 {
		if verbose {
			fmt.Fprintln(w, "tk: no Nix store symlinks found, skipping cell freshness check")
		}
		return nil
	}

	stateFile := filepath.Join(root, turnkeyDir, stateFileName)
	saved, err := readStateFile(stateFile)
	if err != nil {
		if os.IsNotExist(err) {
			// First run — write state, no kill needed.
			if verbose {
				fmt.Fprintln(w, "tk: recording cell symlink targets (first run)")
			}
			return writeStateFile(stateFile, current)
		}
		return fmt.Errorf("reading cell state: %w", err)
	}

	// Compare targets.
	changed := diffTargets(saved, current)
	if len(changed) == 0 {
		if verbose {
			fmt.Fprintln(w, "tk: cell symlinks unchanged")
		}
		return nil
	}

	// Something changed — kill daemon and update state.
	if !quiet {
		fmt.Fprintf(w, "tk: cell symlink changed, restarting buck2 daemon\n")
		if verbose {
			for _, c := range changed {
				fmt.Fprintf(w, "  %s\n", c)
			}
		}
	}

	_ = killDaemon() // best-effort

	return writeStateFile(stateFile, current)
}

// readSymlinkTargets scans .turnkey/ dir entries and .buckconfig for
// symlinks pointing into /nix/store/. Returns a map of relative path
// to resolved symlink target.
func readSymlinkTargets(root string) map[string]string {
	targets := make(map[string]string)

	// Check .buckconfig
	bcPath := filepath.Join(root, ".buckconfig")
	if t, err := os.Readlink(bcPath); err == nil && strings.HasPrefix(t, nixStoreDir) {
		targets[".buckconfig"] = t
	}

	// Scan .turnkey/ entries
	tkDir := filepath.Join(root, turnkeyDir)
	entries, err := os.ReadDir(tkDir)
	if err != nil {
		return targets
	}

	for _, e := range entries {
		name := e.Name()
		if name == stateFileName {
			continue
		}
		full := filepath.Join(tkDir, name)
		t, err := os.Readlink(full)
		if err != nil {
			continue
		}
		if strings.HasPrefix(t, nixStoreDir) {
			targets[filepath.Join(turnkeyDir, name)] = t
		}
	}

	return targets
}

// readStateFile parses the tab-separated state file.
func readStateFile(path string) (map[string]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer func() { _ = f.Close() }()

	targets := make(map[string]string)
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, "#") || line == "" {
			continue
		}
		parts := strings.SplitN(line, "\t", 2)
		if len(parts) == 2 {
			targets[parts[0]] = parts[1]
		}
	}
	return targets, scanner.Err()
}

// writeStateFile writes the tab-separated state file atomically.
func writeStateFile(path string, targets map[string]string) error {
	// Sort keys for deterministic output.
	keys := make([]string, 0, len(targets))
	for k := range targets {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var buf strings.Builder
	buf.WriteString("# Auto-generated by tk. Do not edit.\n")
	for _, k := range keys {
		buf.WriteString(k)
		buf.WriteByte('\t')
		buf.WriteString(targets[k])
		buf.WriteByte('\n')
	}

	return os.WriteFile(path, []byte(buf.String()), 0o644)
}

// diffTargets returns a human-readable list of changes between saved
// and current symlink targets. Returns nil if identical.
func diffTargets(saved, current map[string]string) []string {
	var changes []string

	for k, cur := range current {
		old, ok := saved[k]
		if !ok {
			changes = append(changes, fmt.Sprintf("+ %s -> %s", k, cur))
		} else if old != cur {
			changes = append(changes, fmt.Sprintf("~ %s -> %s (was %s)", k, cur, old))
		}
	}
	for k := range saved {
		if _, ok := current[k]; !ok {
			changes = append(changes, fmt.Sprintf("- %s (removed)", k))
		}
	}

	sort.Strings(changes)
	return changes
}

// KillCommand is the function used to kill the buck2 daemon.
// Tests can override this to avoid killing the real daemon.
var KillCommand = func() error {
	cmd := exec.Command("buck2", "kill")
	cmd.Stdout = os.Stderr
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

// killDaemon runs the kill command. Errors are ignored (best-effort).
func killDaemon() error {
	return KillCommand()
}
