# godeps-gen Nix package
#
# Builds the godeps-gen tool that generates go-deps.toml from go.mod/go.sum.
# This tool is used to create declarative Go dependency files for Buck2 integration.
#
# Uses per-module fetching (not vendorHash) to avoid buildGoModule's hash instability.
# Dependencies are fetched individually and assembled into a vendor directory.
{ pkgs, lib }:

let
  # godeps-gen's own dependencies (bootstrap - these are stable)
  # Hashes obtained via: nix run nixpkgs#nix-prefetch-github -- OWNER REPO --rev VERSION --json
  deps = {
    "github.com/google/uuid" = {
      version = "v1.6.0";
      owner = "google";
      repo = "uuid";
      hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw=";
    };
    "github.com/pelletier/go-toml/v2" = {
      version = "v2.2.4";
      owner = "pelletier";
      repo = "go-toml";
      hash = "sha256-VKUrpSaGzkewNSyE0sB6PWVIQiraY7UxE5Wve+76UFk=";
    };
    "golang.org/x/mod" = {
      version = "v0.31.0";
      owner = "golang";
      repo = "mod";
      hash = "sha256-eOvJXcF3QYztJxlBzHXPweJYG08YsLzPXXM8Px3IXA4=";
    };
    "golang.org/x/sync" = {
      version = "v0.18.0";
      owner = "golang";
      repo = "sync";
      hash = "sha256-S8o6y7GOaYWeq+TzT8BB6T+1mg82Mu08V0TL3ukJprg=";
    };
    "golang.org/x/tools" = {
      version = "v0.39.0";
      owner = "golang";
      repo = "tools";
      hash = "sha256-00jwWlUXABA3sz58ZnasNW2eyGKEzwuujnfwJiYaNzg=";
    };
  };

  # Fetch each dependency
  fetchDep = importPath: dep:
    pkgs.fetchFromGitHub {
      inherit (dep) owner repo hash;
      rev = dep.version;
    };

  # Copy commands for each dependency
  copyDep = importPath: dep:
    let
      src = fetchDep importPath dep;
      # Handle v2+ module paths (github.com/pelletier/go-toml/v2 -> vendor/github.com/pelletier/go-toml/v2)
      vendorPath = importPath;
    in
    ''
      mkdir -p $TMPDIR/vendor/${vendorPath}
      cp -r ${src}/* $TMPDIR/vendor/${vendorPath}/
    '';

  allCopyCommands = lib.concatStringsSep "\n" (lib.mapAttrsToList copyDep deps);

  # Generate modules.txt for vendor directory
  # Content generated by `go mod vendor` - lists all packages needed by godeps-gen
  modulesTxt = ''
# github.com/google/uuid v1.6.0
## explicit
github.com/google/uuid
# github.com/pelletier/go-toml/v2 v2.2.4
## explicit; go 1.21.0
github.com/pelletier/go-toml/v2
github.com/pelletier/go-toml/v2/internal/characters
github.com/pelletier/go-toml/v2/internal/danger
github.com/pelletier/go-toml/v2/internal/tracker
github.com/pelletier/go-toml/v2/unstable
# golang.org/x/mod v0.31.0
## explicit; go 1.24.0
golang.org/x/mod/internal/lazyregexp
golang.org/x/mod/modfile
golang.org/x/mod/module
golang.org/x/mod/semver
# golang.org/x/sync v0.18.0
## explicit; go 1.24.0
golang.org/x/sync/errgroup
# golang.org/x/tools v0.39.0
## explicit; go 1.24.0
golang.org/x/tools/go/ast/edge
golang.org/x/tools/go/ast/inspector
golang.org/x/tools/go/gcexportdata
golang.org/x/tools/go/packages
golang.org/x/tools/go/types/objectpath
golang.org/x/tools/go/types/typeutil
golang.org/x/tools/internal/aliases
golang.org/x/tools/internal/event
golang.org/x/tools/internal/event/core
golang.org/x/tools/internal/event/keys
golang.org/x/tools/internal/event/label
golang.org/x/tools/internal/gcimporter
golang.org/x/tools/internal/gocommand
golang.org/x/tools/internal/packagesinternal
golang.org/x/tools/internal/pkgbits
golang.org/x/tools/internal/stdlib
golang.org/x/tools/internal/typeparams
golang.org/x/tools/internal/typesinternal
golang.org/x/tools/internal/versions
'';

in
pkgs.stdenv.mkDerivation {
  pname = "godeps-gen";
  version = "0.1.0";

  src = ../..;

  nativeBuildInputs = [ pkgs.go pkgs.makeWrapper ];

  # Go needs writable directories
  HOME = "/tmp";
  GOCACHE = "/tmp/go-cache";

  buildPhase = ''
    runHook preBuild

    # Create vendor directory with all dependencies
    ${allCopyCommands}

    # Create modules.txt
    cat > $TMPDIR/vendor/modules.txt << 'EOF'
${modulesTxt}EOF

    # Copy vendor to source tree for go build
    cp -r $TMPDIR/vendor ./vendor

    # Build with vendored dependencies
    go build -mod=vendor -o godeps-gen ./cmd/godeps-gen

    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p $out/bin
    cp godeps-gen $out/bin/

    # Wrap the binary to include prefetcher tools in PATH
    wrapProgram $out/bin/godeps-gen \
      --prefix PATH : ${lib.makeBinPath [
        pkgs.nix-prefetch-github
        pkgs.nix
      ]}

    runHook postInstall
  '';

  meta = {
    description = "Generate go-deps.toml from go.mod and go.sum for Buck2 integration";
    homepage = "https://github.com/firefly-engineering/turnkey";
    license = lib.licenses.mit;
    maintainers = [ ];
    mainProgram = "godeps-gen";
  };
}
