package rustdeps

import (
	"fmt"
	"io"
)

// OutputOptions configures the TOML output format.
type OutputOptions struct {
	// IncludeHeader adds the auto-generated header comment.
	IncludeHeader bool

	// IncludeHashWarning adds a warning when hashes are missing.
	IncludeHashWarning bool

	// IncludeRegenerateHint adds the regeneration command hint.
	IncludeRegenerateHint bool
}

// DefaultOutputOptions returns the default output options.
func DefaultOutputOptions() OutputOptions {
	return OutputOptions{
		IncludeHeader:         true,
		IncludeHashWarning:    true,
		IncludeRegenerateHint: true,
	}
}

// WriteTOML writes crates in rust-deps.toml format to the given writer.
func WriteTOML(w io.Writer, crates []Crate, opts OutputOptions) error {
	// Check if any crates are missing hashes
	hasMissingHashes := false
	for _, crate := range crates {
		if crate.NixHash == "" {
			hasMissingHashes = true
			break
		}
	}

	// Write header
	if opts.IncludeHeader {
		fmt.Fprintln(w, "# Auto-generated by rustdeps-gen")
		fmt.Fprintln(w, "# Source: Cargo.lock")
		fmt.Fprintln(w, "#")
	}

	if opts.IncludeHashWarning && hasMissingHashes {
		fmt.Fprintln(w, "# WARNING: Some crates are missing hashes.")
		fmt.Fprintln(w, "# Ensure Cargo.lock has checksums (run: cargo update)")
		fmt.Fprintln(w, "#")
	}

	if opts.IncludeRegenerateHint {
		fmt.Fprintln(w, "# To regenerate: rustdeps-gen --cargo-lock Cargo.lock > rust-deps.toml")
		fmt.Fprintln(w)
	}

	// Write each crate
	for _, crate := range crates {
		if err := writeCrate(w, crate); err != nil {
			return err
		}
	}

	return nil
}

// writeCrate writes a single crate entry in TOML format.
func writeCrate(w io.Writer, crate Crate) error {
	fmt.Fprintf(w, "[deps.%s]\n", crate.Name)
	fmt.Fprintf(w, "version = \"%s\"\n", crate.Version)

	if crate.NixHash != "" {
		fmt.Fprintf(w, "hash = \"%s\"\n", crate.NixHash)
	} else if crate.Checksum != "" {
		// Include checksum as comment for debugging
		fmt.Fprintf(w, "hash = \"\" # checksum: %s\n", crate.Checksum)
	} else {
		fmt.Fprintln(w, "hash = \"\"")
	}

	// Write features if any
	if len(crate.Features) > 0 {
		fmt.Fprint(w, "features = [")
		for i, feat := range crate.Features {
			if i > 0 {
				fmt.Fprint(w, ", ")
			}
			fmt.Fprintf(w, "\"%s\"", feat)
		}
		fmt.Fprintln(w, "]")
	}

	fmt.Fprintln(w)
	return nil
}
