package rustdeps

import (
	"testing"
)

func TestParseCargoLock(t *testing.T) {
	cargoLock := []byte(`
# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "itoa"
version = "1.0.14"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "d75a2a4b1b190afb6f5425f10f6a8f959d2ea0b9c2b1d79553551850539e4674"

[[package]]
name = "serde"
version = "1.0.152"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "bb7d1f0d3021d347a83e556fc4683dea2ea09d87bccdf88ff5c12545d89d5efb"

[[package]]
name = "local-crate"
version = "0.1.0"
`)

	opts := DefaultParseOptions()
	crates, err := ParseCargoLock(cargoLock, opts)
	if err != nil {
		t.Fatalf("ParseCargoLock failed: %v", err)
	}

	// Should have 2 crates (local-crate filtered out)
	if len(crates) != 2 {
		t.Errorf("expected 2 crates, got %d", len(crates))
	}

	// Should be sorted alphabetically
	if crates[0].Name != "itoa" {
		t.Errorf("expected first crate to be itoa, got %s", crates[0].Name)
	}
	if crates[1].Name != "serde" {
		t.Errorf("expected second crate to be serde, got %s", crates[1].Name)
	}

	// Check version and checksum
	if crates[0].Version != "1.0.14" {
		t.Errorf("expected itoa version 1.0.14, got %s", crates[0].Version)
	}
	if crates[0].Checksum != "d75a2a4b1b190afb6f5425f10f6a8f959d2ea0b9c2b1d79553551850539e4674" {
		t.Errorf("unexpected checksum for itoa")
	}
}

func TestConvertChecksumToSRI(t *testing.T) {
	tests := []struct {
		name     string
		hex      string
		expected string
		wantErr  bool
	}{
		{
			name:     "valid checksum",
			hex:      "d75a2a4b1b190afb6f5425f10f6a8f959d2ea0b9c2b1d79553551850539e4674",
			expected: "sha256-11oqSxsZCvtvVCXxD2qPlZ0uoLnCsdeVU1UYUFOeRnQ=",
			wantErr:  false,
		},
		{
			name:     "empty checksum",
			hex:      "",
			expected: "",
			wantErr:  false,
		},
		{
			name:    "invalid length",
			hex:     "abc123",
			wantErr: true,
		},
		{
			name:    "invalid hex chars",
			hex:     "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := ConvertChecksumToSRI(tt.hex)
			if (err != nil) != tt.wantErr {
				t.Errorf("ConvertChecksumToSRI() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if got != tt.expected {
				t.Errorf("ConvertChecksumToSRI() = %v, expected %v", got, tt.expected)
			}
		})
	}
}

func TestPopulateNixHashes(t *testing.T) {
	crates := []Crate{
		{
			Name:     "itoa",
			Version:  "1.0.14",
			Checksum: "d75a2a4b1b190afb6f5425f10f6a8f959d2ea0b9c2b1d79553551850539e4674",
		},
		{
			Name:    "no-checksum",
			Version: "0.1.0",
		},
	}

	err := PopulateNixHashes(crates)
	if err != nil {
		t.Fatalf("PopulateNixHashes failed: %v", err)
	}

	if crates[0].NixHash != "sha256-11oqSxsZCvtvVCXxD2qPlZ0uoLnCsdeVU1UYUFOeRnQ=" {
		t.Errorf("unexpected NixHash for itoa: %s", crates[0].NixHash)
	}

	if crates[1].NixHash != "" {
		t.Errorf("expected empty NixHash for no-checksum crate, got %s", crates[1].NixHash)
	}
}
