//! go-deps.toml: the deps file the godeps cell is built from
//!
//! The file is written line by line, as Go's godeps-gen wrote it, rather
//! than serialized: its layout (comments, the go.sum hash comment after an
//! empty hash) is what turnkey's committed go-deps.toml files hold.

use crate::deps::Dependency;
use crate::workspace::Member;
use gostd::strconv::quote;
use std::fmt::Write;

/// Which comments the file starts with
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct OutputOptions {
    /// The auto-generated header
    pub include_header: bool,
    /// The warning that hashes are missing, when one is
    pub include_hash_warning: bool,
    /// How to regenerate the file
    pub include_regenerate_hint: bool,
}

impl OutputOptions {
    /// Every comment, as godeps-gen writes the file
    pub fn all() -> Self {
        Self {
            include_header: true,
            include_hash_warning: true,
            include_regenerate_hint: true,
        }
    }
}

/// What go-deps.toml holds
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct DepsFile {
    /// The third-party modules the godeps cell fetches
    pub deps: Vec<Dependency>,
    /// The files the deps were resolved from (the workspace's sources):
    /// the Go sync rule's target_sources, so a change to any of them makes
    /// go-deps.toml stale. Omitted when empty.
    pub sources: Vec<String>,
    /// The workspace's modules, the first-party ones rules sync maps
    /// imports to. Omitted when empty.
    pub members: Vec<Member>,
}

/// The go-deps.toml of `deps` alone
#[cfg_attr(not(test), allow(dead_code))]
pub fn render_toml(deps: &[Dependency], opts: OutputOptions) -> String {
    render(
        &DepsFile {
            deps: deps.to_vec(),
            ..Default::default()
        },
        opts,
    )
}

/// The go-deps.toml of `file`
pub fn render(file: &DepsFile, opts: OutputOptions) -> String {
    let mut w = String::new();
    let missing_hashes = file.deps.iter().any(|d| d.nix_hash.is_empty());

    if opts.include_header {
        w.push_str("# Auto-generated by godeps-gen\n");
        w.push_str("# Source: the files listed under sources\n");
        w.push_str("#\n");
        w.push_str("# Key format: deps.\"import-path@version\" to support multiple versions\n");
        w.push_str("#\n");
    }
    if opts.include_hash_warning && missing_hashes {
        w.push_str("# IMPORTANT: Nix hashes must be obtained separately.\n");
        w.push_str("# Prefetching (on unless --no-prefetch) fetches them; or manually run:\n");
        w.push_str(
            "# nix-prefetch-cached --unpack https://proxy.golang.org/MODULE/@v/VERSION.zip\n",
        );
        w.push_str("#\n");
    }
    if opts.include_regenerate_hint {
        w.push_str("# To regenerate: tk sync\n\n");
    }

    // v2: versioned keys like [deps."path@version"] with an import_path field
    w.push_str("schema_version = 2\n\n");

    if !file.sources.is_empty() {
        w.push_str("sources = [\n");
        for source in &file.sources {
            let _ = writeln!(w, "    {},", quote(source));
        }
        w.push_str("]\n\n");
    }

    for dep in &file.deps {
        write_dependency(&mut w, dep);
    }

    for m in &file.members {
        let _ = writeln!(w, "[members.{}]", quote(&m.path));
        let _ = writeln!(w, "dir = {}", quote(&m.dir));
        w.push('\n');
    }
    w
}

/// One dependency, under its versioned key `[deps."path@version"]`. Its
/// strings are written as they are, unescaped, as Go's godeps-gen wrote
/// them.
fn write_dependency(w: &mut String, dep: &Dependency) {
    let _ = writeln!(w, "[deps.\"{}@{}\"]", dep.import_path, dep.version);
    let _ = writeln!(w, "import_path = \"{}\"", dep.import_path);
    // fetch_path only when it differs: a replace by another module
    if !dep.fetch_path.is_empty() && dep.fetch_path != dep.import_path {
        let _ = writeln!(w, "fetch_path = \"{}\"", dep.fetch_path);
    }
    let _ = writeln!(w, "version = \"{}\"", dep.version);
    if dep.nix_hash.is_empty() {
        // An empty hash, with go.sum's for reference
        let _ = writeln!(w, "hash = \"\"{}", hash_comment(&dep.go_sum_hash));
    } else {
        let _ = writeln!(w, "hash = \"{}\"", dep.nix_hash);
    }
    if dep.indirect {
        w.push_str("indirect = true\n");
    }
    w.push('\n');
}

/// The go.sum hash as a comment after an empty hash
fn hash_comment(go_sum_hash: &str) -> String {
    if go_sum_hash.is_empty() {
        String::new()
    } else {
        format!(
            " # go.sum {go_sum_hash} - run godeps-gen without --no-prefetch to get correct hash"
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn dep(import_path: &str, version: &str, nix_hash: &str) -> Dependency {
        Dependency {
            import_path: import_path.into(),
            version: version.into(),
            nix_hash: nix_hash.into(),
            ..Default::default()
        }
    }

    const BARE: OutputOptions = OutputOptions {
        include_header: false,
        include_hash_warning: false,
        include_regenerate_hint: false,
    };

    #[test]
    fn basic_output() {
        let out = render_toml(
            &[dep("github.com/foo/bar", "v1.0.0", "sha256-abc123=")],
            BARE,
        );
        assert!(
            out.contains(r#"[deps."github.com/foo/bar@v1.0.0"]"#),
            "{out}"
        );
        assert!(out.contains(r#"import_path = "github.com/foo/bar""#));
        assert!(out.contains(r#"version = "v1.0.0""#));
        assert!(out.contains(r#"hash = "sha256-abc123=""#));
    }

    #[test]
    fn indirect_dependency() {
        let mut d = dep("github.com/foo/bar", "v1.0.0", "sha256-abc=");
        d.indirect = true;
        assert!(render_toml(&[d], OutputOptions::default()).contains("indirect = true"));
    }

    #[test]
    fn missing_hash() {
        let mut d = dep("github.com/foo/bar", "v1.0.0", "");
        d.go_sum_hash = "h1:somehash=".into();
        let out = render_toml(
            &[d],
            OutputOptions {
                include_hash_warning: true,
                ..BARE
            },
        );
        assert!(out.contains(r#"hash = """#));
        assert!(out.contains("go.sum h1:somehash="));
        assert!(out.contains("IMPORTANT"));
    }

    #[test]
    fn with_header() {
        let out = render_toml(
            &[],
            OutputOptions {
                include_header: true,
                include_regenerate_hint: true,
                ..BARE
            },
        );
        assert!(out.contains("Auto-generated by godeps-gen"));
        assert!(out.contains("To regenerate:"));
        assert!(out.contains("schema_version = 2"));
        assert!(out.contains("Key format: deps."));
    }

    #[test]
    fn no_hash_warning_when_all_hashed() {
        let out = render_toml(
            &[dep("github.com/foo/bar", "v1.0.0", "sha256-abc=")],
            OutputOptions {
                include_hash_warning: true,
                ..BARE
            },
        );
        assert!(!out.contains("IMPORTANT"));
    }

    #[test]
    fn multiple_dependencies() {
        let mut third = dep("github.com/ccc/third", "v1.2.0", "sha256-c=");
        third.indirect = true;
        let out = render_toml(
            &[
                dep("github.com/aaa/first", "v1.0.0", "sha256-a="),
                dep("github.com/bbb/second", "v1.1.0", "sha256-b="),
                third,
            ],
            OutputOptions::default(),
        );
        for path in [
            "github.com/aaa/first",
            "github.com/bbb/second",
            "github.com/ccc/third",
        ] {
            assert!(out.contains(path), "{path}");
        }
    }

    #[test]
    fn header_without_deps() {
        let out = render_toml(
            &[],
            OutputOptions {
                include_header: true,
                ..BARE
            },
        );
        assert!(out.contains("Auto-generated"));
    }

    #[test]
    fn hash_comments() {
        assert_eq!(
            hash_comment("h1:abc123="),
            " # go.sum h1:abc123= - run godeps-gen without --no-prefetch to get correct hash"
        );
        assert_eq!(hash_comment(""), "");
    }

    #[test]
    fn fetch_path_only_when_it_differs() {
        let mut fork = dep("github.com/original/pkg", "v1.0.0", "sha256-abc123=");
        fork.fetch_path = "github.com/fork/pkg".into();
        let out = render_toml(&[fork], BARE);
        assert!(
            out.contains(r#"[deps."github.com/original/pkg@v1.0.0"]"#),
            "{out}"
        );
        assert!(out.contains(r#"import_path = "github.com/original/pkg""#));
        assert!(
            out.contains(r#"fetch_path = "github.com/fork/pkg""#),
            "{out}"
        );

        let mut same = dep("github.com/foo/bar", "v1.0.0", "sha256-abc=");
        same.fetch_path = "github.com/foo/bar".into();
        assert!(!render_toml(&[same], BARE).contains("fetch_path"));
        assert!(
            !render_toml(&[dep("github.com/foo/bar", "v1.0.0", "sha256-abc=")], BARE)
                .contains("fetch_path")
        );
    }

    #[test]
    fn records_sources_and_members() {
        let file = DepsFile {
            deps: vec![dep("github.com/google/uuid", "v1.6.0", "sha256-x")],
            sources: vec!["go.work".into(), "a/go.mod".into()],
            members: vec![Member {
                path: "example.com/a".into(),
                dir: "a".into(),
                sum_file: String::new(),
            }],
        };
        let want = r#"schema_version = 2

sources = [
    "go.work",
    "a/go.mod",
]

[deps."github.com/google/uuid@v1.6.0"]
import_path = "github.com/google/uuid"
version = "v1.6.0"
hash = "sha256-x"

[members."example.com/a"]
dir = "a"

"#;
        assert_eq!(render(&file, OutputOptions::default()), want);
    }

    #[test]
    fn quotes_sources_and_members_as_go_does() {
        let file = DepsFile {
            sources: vec!["dir \"q\"/go.mod".into(), "tab\t/go.mod".into()],
            members: vec![Member {
                path: "example.com/é".into(),
                dir: "back\\slash".into(),
                sum_file: String::new(),
            }],
            ..Default::default()
        };
        let out = render(&file, OutputOptions::default());
        assert!(out.contains(r#"    "dir \"q\"/go.mod","#), "{out}");
        assert!(out.contains(r#"    "tab\t/go.mod","#), "{out}");
        assert!(
            out.contains("[members.\"example.com/é\"]\ndir = \"back\\\\slash\"\n"),
            "{out}"
        );
    }

    /// The Go tests' integration cases: src/testdata/godeps/*, whose
    /// go.mod and go.sum give expected.toml
    #[test]
    fn golden_files() {
        let cases = [
            (
                "simple",
                include_str!("../testdata/godeps/simple/go.mod"),
                include_bytes!("../testdata/godeps/simple/go.sum").as_slice(),
                include_str!("../testdata/godeps/simple/expected.toml"),
            ),
            (
                "medium",
                include_str!("../testdata/godeps/medium/go.mod"),
                include_bytes!("../testdata/godeps/medium/go.sum").as_slice(),
                include_str!("../testdata/godeps/medium/expected.toml"),
            ),
            (
                "edge-cases",
                include_str!("../testdata/godeps/edge-cases/go.mod"),
                include_bytes!("../testdata/godeps/edge-cases/go.sum").as_slice(),
                include_str!("../testdata/godeps/edge-cases/expected.toml"),
            ),
        ];
        for (name, go_mod, go_sum, expected) in cases {
            let mut deps = crate::deps::parse_go_mod(go_mod, Default::default()).unwrap();
            let hashes = crate::deps::parse_go_sum(go_sum).unwrap();
            crate::deps::merge_hashes(&mut deps, &hashes);
            let got = render_toml(&deps, BARE);
            assert_eq!(got.trim(), expected.trim(), "{name}");
        }
    }
}
