//! Platform-agnostic filesystem core logic
//!
//! This module contains all the filesystem state and logic that is independent
//! of any particular FUSE implementation (fuser, libfuse-t, etc.). Both the
//! Linux fuser backend and a future macOS libfuse-t backend delegate to `FsCore`.
//!
//! # Design
//!
//! `FsCore` uses plain `u64` inode numbers and its own `FsFileType` / `FsAttr`
//! types so that it has **zero dependency on the `fuser` crate**. Each backend
//! is responsible for converting between `FsCore` types and its own FUSE types.

use log::{debug, warn};
use std::collections::HashMap;
use std::ffi::OsStr;
use std::fs::{self, File};
use std::io::Read;
use std::os::unix::fs::MetadataExt;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, RwLock};
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use super::edit_overlay::EditOverlay;
use crate::layout::{default_layout, layout_by_name, BoxedLayout, CellInfo, LayoutContext};
use crate::performance::CacheConfig;
use crate::policy::{
    default_policy, BoxedPolicy, FileClass, OperationType, PolicyDecision,
    SystemState as PolicyState,
};
use crate::state::ConsistencyStateMachine;
use crate::{BackendStatus, CompositionConfig};

// ---------------------------------------------------------------------------
// Reserved inode numbers (plain u64, no fuser dependency)
// ---------------------------------------------------------------------------

pub(crate) const ROOT_INO: u64 = 1;
pub(crate) const SOURCE_INO: u64 = 2;
pub(crate) const CELL_PREFIX_INO: u64 = 3;
pub(crate) const BUCKCONFIG_INO: u64 = 4;
pub(crate) const BUCKROOT_INO: u64 = 5;
pub(crate) const FIRST_DYNAMIC_INO: u64 = 1000;

// ---------------------------------------------------------------------------
// Platform-neutral types
// ---------------------------------------------------------------------------

/// Virtual file types generated by the layout
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum VirtualFile {
    BuckConfig,
    BuckRoot,
    Envrc,
}

/// Represents the underlying path for an inode
#[derive(Debug, Clone)]
pub(crate) enum InodePath {
    /// Virtual root directory of the mount
    Root,
    /// Source directory - pass-through to repo root
    Source,
    /// Cell prefix directory - contains cells (e.g., ".turnkey")
    CellPrefix,
    /// A cell directory under cell prefix
    Cell { name: String },
    /// A virtual file (generated content)
    Virtual { file: VirtualFile },
    /// A real path on the filesystem
    Real { path: PathBuf },
}

/// Platform-neutral file type (no fuser dependency)
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum FsFileType {
    Directory,
    RegularFile,
    Symlink,
}

/// Platform-neutral file attributes (no fuser dependency)
#[derive(Debug, Clone)]
pub(crate) struct FsAttr {
    pub ino: u64,
    pub size: u64,
    pub blocks: u64,
    pub atime: SystemTime,
    pub mtime: SystemTime,
    pub ctime: SystemTime,
    pub kind: FsFileType,
    pub perm: u16,
    pub nlink: u32,
    pub uid: u32,
    pub gid: u32,
    pub rdev: u32,
    pub blksize: u32,
}

/// Result of resolving a FUSE path string to a logical location.
///
/// Used by the macOS high-level (path-based) FUSE API where operations
/// receive paths instead of inode numbers.
#[derive(Debug, Clone)]
pub(crate) enum ResolvedPath {
    Root,
    Source,
    SourceChild { real_path: PathBuf },
    CellPrefix,
    Cell { name: String, real_path: PathBuf },
    CellChild { cell_name: String, real_path: PathBuf },
    VirtualFile { file: VirtualFile },
    /// An output directory mounted at the root (e.g., "build" → /tmp/buck-out)
    OutputMount { real_path: PathBuf },
    /// A child path within an output mount
    OutputChild { real_path: PathBuf },
    NotFound,
}

// ---------------------------------------------------------------------------
// FsCore — the platform-agnostic filesystem engine
// ---------------------------------------------------------------------------

/// Platform-agnostic filesystem core.
///
/// Holds all state and helper logic that both the fuser backend (Linux) and a
/// future libfuse-t backend (macOS) need. Has **no** dependency on the `fuser`
/// crate.
pub(crate) struct FsCore {
    /// Configuration for this composition
    pub config: CompositionConfig,
    /// Path to the repository root (for source/ pass-through)
    pub repo_root: PathBuf,
    /// Inode to path mapping
    pub inode_map: RwLock<HashMap<u64, InodePath>>,
    /// Path to inode mapping (for lookups)
    pub path_map: RwLock<HashMap<PathBuf, u64>>,
    /// Next inode number to allocate
    pub next_inode: AtomicU64,
    /// Current user ID
    pub uid: u32,
    /// Current group ID
    pub gid: u32,
    /// State machine for consistency during updates
    pub state_machine: Arc<ConsistencyStateMachine>,
    /// Access policy for file operations
    pub policy: BoxedPolicy,
    /// Mutable cell source paths (can be updated atomically during transitions)
    pub cell_paths: RwLock<HashMap<String, PathBuf>>,
    /// Edit overlay for copy-on-write editing of cell files
    pub edit_overlay: Option<EditOverlay>,
    /// Layout for build system configuration
    pub layout: BoxedLayout,
    /// Cached layout context for efficient config generation
    pub layout_context: LayoutContext,
    /// Cached config files from the layout
    pub cached_configs: RwLock<HashMap<String, String>>,
    /// Cache configuration for performance tuning
    pub cache_config: CacheConfig,
}

impl FsCore {
    /// Create a new filesystem core
    pub fn new(
        config: CompositionConfig,
        repo_root: PathBuf,
        state_machine: Arc<ConsistencyStateMachine>,
    ) -> Self {
        Self::with_options(
            config,
            repo_root,
            state_machine,
            default_policy(),
            CacheConfig::default(),
        )
    }

    /// Create a new filesystem core with a custom policy
    pub fn with_policy(
        config: CompositionConfig,
        repo_root: PathBuf,
        state_machine: Arc<ConsistencyStateMachine>,
        policy: BoxedPolicy,
    ) -> Self {
        Self::with_options(config, repo_root, state_machine, policy, CacheConfig::default())
    }

    /// Create a new filesystem core with custom policy and cache configuration
    pub fn with_options(
        config: CompositionConfig,
        repo_root: PathBuf,
        state_machine: Arc<ConsistencyStateMachine>,
        policy: BoxedPolicy,
        cache_config: CacheConfig,
    ) -> Self {
        let mut inode_map = HashMap::new();
        inode_map.insert(ROOT_INO, InodePath::Root);
        inode_map.insert(SOURCE_INO, InodePath::Source);
        inode_map.insert(CELL_PREFIX_INO, InodePath::CellPrefix);
        inode_map.insert(
            BUCKCONFIG_INO,
            InodePath::Virtual {
                file: VirtualFile::BuckConfig,
            },
        );
        inode_map.insert(
            BUCKROOT_INO,
            InodePath::Virtual {
                file: VirtualFile::BuckRoot,
            },
        );

        // Pre-allocate inodes for configured cells and build cell_paths map
        let mut next_ino = FIRST_DYNAMIC_INO;
        let mut cell_paths = HashMap::new();
        let mut editable_cells = Vec::new();
        for cell in &config.cells {
            inode_map.insert(next_ino, InodePath::Cell { name: cell.name.clone() });
            cell_paths.insert(cell.name.clone(), cell.source_path.clone());
            if cell.editable {
                editable_cells.push(cell.name.clone());
            }
            next_ino += 1;
        }

        // Create edit overlay if editing is enabled
        let edit_overlay = if config.enable_editing {
            let edits_dir = repo_root.join(&config.edits_dir);
            Some(EditOverlay::new(edits_dir, editable_cells))
        } else {
            None
        };

        // Create layout based on config
        let layout = layout_by_name(&config.layout).unwrap_or_else(default_layout);

        // Build layout context
        let layout_context = LayoutContext {
            mount_point: config.mount_point.clone(),
            repo_root: repo_root.clone(),
            source_dir_name: config.source_dir_name.clone(),
            cell_prefix: config.cell_prefix.clone(),
            cells: config
                .cells
                .iter()
                .map(|c| CellInfo::new(&c.name, &c.source_path).with_editable(c.editable))
                .collect(),
        };

        // Generate and cache config files
        let configs: HashMap<String, String> = layout
            .generate_config(&layout_context)
            .into_iter()
            .map(|c| (c.name, c.content))
            .collect();

        // Add toolchain profile as a virtual bin/ output mount if available
        let mut config = config;
        if let Some(ref profile_path) = config.toolchain_profile {
            let bin_path = profile_path.join("bin");
            if bin_path.exists() {
                config.output_mounts.push(crate::config::OutputMount {
                    mount_as: "bin".to_string(),
                    real_path: bin_path,
                });
            }
        }

        Self {
            config,
            repo_root,
            inode_map: RwLock::new(inode_map),
            path_map: RwLock::new(HashMap::new()),
            next_inode: AtomicU64::new(next_ino),
            uid: unsafe { libc::getuid() },
            gid: unsafe { libc::getgid() },
            state_machine,
            policy,
            cell_paths: RwLock::new(cell_paths),
            edit_overlay,
            layout,
            layout_context,
            cached_configs: RwLock::new(configs),
            cache_config,
        }
    }

    // -----------------------------------------------------------------------
    // Attribute helpers
    // -----------------------------------------------------------------------

    /// Get the attribute TTL based on cache configuration
    #[inline]
    pub fn attr_ttl(&self) -> Duration {
        self.cache_config.attr_ttl()
    }

    /// Convert `std::fs::FileType` to platform-neutral `FsFileType`
    #[inline]
    pub fn to_fs_file_type(ft: std::fs::FileType) -> FsFileType {
        if ft.is_dir() {
            FsFileType::Directory
        } else if ft.is_symlink() {
            FsFileType::Symlink
        } else {
            FsFileType::RegularFile
        }
    }

    /// Create `FsAttr` from filesystem metadata
    pub fn metadata_to_attr(&self, ino: u64, meta: &fs::Metadata) -> FsAttr {
        let kind = if meta.is_dir() {
            FsFileType::Directory
        } else if meta.is_symlink() {
            FsFileType::Symlink
        } else {
            FsFileType::RegularFile
        };

        FsAttr {
            ino,
            size: meta.len(),
            blocks: meta.blocks(),
            atime: meta.accessed().unwrap_or(UNIX_EPOCH),
            mtime: meta.modified().unwrap_or(UNIX_EPOCH),
            ctime: SystemTime::UNIX_EPOCH + Duration::from_secs(meta.ctime() as u64),
            kind,
            perm: (meta.mode() & 0o7777) as u16,
            nlink: meta.nlink() as u32,
            uid: meta.uid(),
            gid: meta.gid(),
            rdev: meta.rdev() as u32,
            blksize: meta.blksize() as u32,
        }
    }

    /// Create a virtual directory attribute
    pub fn virtual_dir_attr(&self, ino: u64) -> FsAttr {
        FsAttr {
            ino,
            size: 0,
            blocks: 0,
            atime: UNIX_EPOCH,
            mtime: UNIX_EPOCH,
            ctime: UNIX_EPOCH,
            kind: FsFileType::Directory,
            perm: 0o755,
            nlink: 2,
            uid: self.uid,
            gid: self.gid,
            rdev: 0,
            blksize: 512,
        }
    }

    /// Create a virtual file attribute
    pub fn virtual_file_attr(&self, ino: u64, size: u64) -> FsAttr {
        FsAttr {
            ino,
            size,
            blocks: (size + 511) / 512,
            atime: UNIX_EPOCH,
            mtime: UNIX_EPOCH,
            ctime: UNIX_EPOCH,
            kind: FsFileType::RegularFile,
            perm: 0o644,
            nlink: 1,
            uid: self.uid,
            gid: self.gid,
            rdev: 0,
            blksize: 512,
        }
    }

    // -----------------------------------------------------------------------
    // Inode management
    // -----------------------------------------------------------------------

    /// Get or allocate an inode for a real path
    ///
    /// Optimized to minimize lock contention with a read-first, write-on-miss
    /// pattern and double-check after acquiring the write lock.
    pub fn get_or_alloc_inode(&self, path: &PathBuf) -> u64 {
        // Fast path: read-only lookup (most common case)
        {
            let path_map = self.path_map.read().unwrap();
            if let Some(&ino) = path_map.get(path) {
                return ino;
            }
        }

        // Slow path: need to insert
        let mut path_map = self.path_map.write().unwrap();
        let mut inode_map = self.inode_map.write().unwrap();

        // Double-check: another thread may have inserted while we waited
        if let Some(&ino) = path_map.get(path) {
            return ino;
        }

        let ino = self.next_inode.fetch_add(1, Ordering::SeqCst);
        inode_map.insert(ino, InodePath::Real { path: path.clone() });
        path_map.insert(path.clone(), ino);
        ino
    }

    /// Get the `InodePath` for an inode
    pub fn get_inode_path(&self, ino: u64) -> Option<InodePath> {
        let inode_map = self.inode_map.read().unwrap();
        inode_map.get(&ino).cloned()
    }

    /// Resolve an inode to a real filesystem path (if applicable)
    pub fn resolve_real_path(&self, ino: u64) -> Option<PathBuf> {
        match self.get_inode_path(ino)? {
            InodePath::Root | InodePath::CellPrefix | InodePath::Virtual { .. } => None,
            InodePath::Source => Some(self.repo_root.clone()),
            InodePath::Cell { name } => {
                let cell_paths = self.cell_paths.read().unwrap();
                cell_paths.get(&name).cloned()
            }
            InodePath::Real { path } => Some(path),
        }
    }

    // -----------------------------------------------------------------------
    // Virtual file content
    // -----------------------------------------------------------------------

    /// Get the content of a virtual file from the layout's cached configs
    pub fn get_virtual_file_content(&self, file: VirtualFile) -> String {
        let configs = self.cached_configs.read().unwrap();
        match file {
            VirtualFile::BuckConfig => configs.get(".buckconfig").cloned().unwrap_or_default(),
            VirtualFile::BuckRoot => configs.get(".buckroot").cloned().unwrap_or_default(),
            VirtualFile::Envrc => "# Generated by turnkey-composed\nPATH_add bin\nexport BUCK_ISOLATION_DIR=build\n".to_string(),
        }
    }

    /// Regenerate cached config files from the layout
    #[allow(dead_code)]
    pub fn regenerate_configs(&self) {
        let configs: HashMap<String, String> = self
            .layout
            .generate_config(&self.layout_context)
            .into_iter()
            .map(|c| (c.name, c.content))
            .collect();

        let mut cached = self.cached_configs.write().unwrap();
        *cached = configs;
    }

    /// Get the layout name
    #[allow(dead_code)]
    pub fn layout_name(&self) -> &'static str {
        self.layout.name()
    }

    // -----------------------------------------------------------------------
    // Cell management
    // -----------------------------------------------------------------------

    /// Find the inode for a cell by name
    pub fn find_cell_inode(&self, name: &str) -> Option<u64> {
        let inode_map = self.inode_map.read().unwrap();
        for (&ino, path) in inode_map.iter() {
            if let InodePath::Cell { name: cell_name } = path {
                if cell_name == name {
                    return Some(ino);
                }
            }
        }
        None
    }

    /// Get cell info for a path under a cell
    ///
    /// Returns `(cell_name, relative_path_within_cell)` if the path is under a cell.
    pub fn get_cell_info(&self, path: &PathBuf) -> Option<(String, PathBuf)> {
        let cell_paths = self.cell_paths.read().unwrap();
        for (cell_name, cell_source) in cell_paths.iter() {
            if let Ok(relative) = path.strip_prefix(cell_source) {
                return Some((cell_name.clone(), relative.to_path_buf()));
            }
        }
        None
    }

    // -----------------------------------------------------------------------
    // Edit overlay helpers
    // -----------------------------------------------------------------------

    /// Check if a file is in an editable cell and has been edited.
    ///
    /// Returns the overlay path if the file should be read from the overlay.
    pub fn get_edit_overlay_path(&self, path: &PathBuf) -> Option<PathBuf> {
        let overlay = self.edit_overlay.as_ref()?;
        let (cell_name, relative) = self.get_cell_info(path)?;
        overlay.get_read_path(&cell_name, &relative)
    }

    /// Check if editing is allowed for a given inode.
    ///
    /// Returns `(cell_name, relative_path, original_path)` if the inode is in an
    /// editable cell, otherwise returns `Err(errno)` as a raw `i32`.
    pub fn check_edit_allowed(&self, ino: u64) -> Result<(String, PathBuf, PathBuf), i32> {
        let overlay = self.edit_overlay.as_ref().ok_or(libc::EROFS)?;
        let original_path = self.resolve_real_path(ino).ok_or(libc::ENOENT)?;
        let (cell_name, relative) = self.get_cell_info(&original_path).ok_or(libc::EROFS)?;

        if !overlay.is_cell_editable(&cell_name) {
            return Err(libc::EROFS);
        }

        Ok((cell_name, relative, original_path))
    }

    // -----------------------------------------------------------------------
    // Policy helpers
    // -----------------------------------------------------------------------

    /// Classify an inode path into a `FileClass` for policy decisions
    pub fn classify_inode(&self, ino: u64) -> Option<FileClass> {
        match self.get_inode_path(ino)? {
            InodePath::Root | InodePath::CellPrefix => Some(FileClass::VirtualDirectory),
            InodePath::Source => Some(FileClass::SourcePassthrough),
            InodePath::Virtual { .. } => Some(FileClass::VirtualGenerated),
            InodePath::Cell { name } => Some(FileClass::CellContent { cell: name }),
            InodePath::Real { path } => {
                for cell in &self.config.cells {
                    if path.starts_with(&cell.source_path) {
                        return Some(FileClass::CellContent {
                            cell: cell.name.clone(),
                        });
                    }
                }
                Some(FileClass::SourcePassthrough)
            }
        }
    }

    /// Get the current system state for policy decisions
    pub fn get_policy_state(&self) -> PolicyState {
        match self.state_machine.status() {
            BackendStatus::Stopped => PolicyState::Settled,
            BackendStatus::Ready => PolicyState::Settled,
            BackendStatus::Updating { .. } => PolicyState::Syncing,
            BackendStatus::Building { .. } => PolicyState::Building,
            BackendStatus::Transitioning => PolicyState::Transitioning,
            BackendStatus::Error { .. } => PolicyState::Error,
        }
    }

    /// Check if an operation is allowed by the policy.
    ///
    /// Returns `Ok(())` if allowed (possibly after waiting).
    /// Returns `Err(errno)` as a raw `i32` if denied.
    pub fn check_policy(&self, class: &FileClass, op: OperationType) -> Result<(), i32> {
        let state = self.get_policy_state();
        let decision = self.policy.check(class, state, op);

        match decision {
            PolicyDecision::Allow => Ok(()),
            PolicyDecision::AllowStale => {
                if let Some(cell) = class.cell_name() {
                    warn!(
                        "Policy '{}': returning potentially stale data for cell '{}' during {:?}",
                        self.policy.name(),
                        cell,
                        state
                    );
                }
                Ok(())
            }
            PolicyDecision::Block { timeout } => {
                debug!(
                    "Policy '{}': blocking for up to {:?} until stable",
                    self.policy.name(),
                    timeout
                );
                if let Err(e) = self.state_machine.wait_ready(Some(timeout)) {
                    warn!("Timeout waiting for stable state: {:?}", e);
                    return Err(libc::EAGAIN);
                }
                Ok(())
            }
            PolicyDecision::Deny { errno } => {
                debug!(
                    "Policy '{}': denying {:?} on {:?} in state {:?}",
                    self.policy.name(),
                    op,
                    class,
                    state
                );
                Err(errno)
            }
        }
    }

    /// Check policy for an inode and operation
    pub fn check_inode_policy(&self, ino: u64, op: OperationType) -> Result<(), i32> {
        if let Some(class) = self.classify_inode(ino) {
            self.check_policy(&class, op)
        } else {
            Ok(())
        }
    }

    /// Check policy for a cell access
    pub fn check_cell_policy(&self, cell_name: &str, op: OperationType) -> Result<(), i32> {
        let class = FileClass::CellContent {
            cell: cell_name.to_string(),
        };
        self.check_policy(&class, op)
    }

    // -----------------------------------------------------------------------
    // Update / cache invalidation
    // -----------------------------------------------------------------------

    /// Apply pending cell updates from the state machine.
    ///
    /// Returns the number of cells updated, or `None` if there were no updates.
    pub fn apply_pending_updates(&self) -> Option<usize> {
        let updates = self.state_machine.take_pending_updates()?;

        if updates.is_empty() {
            return Some(0);
        }

        let affected_cells: Vec<String> = updates.keys().cloned().collect();

        {
            let mut cell_paths = self.cell_paths.write().unwrap();
            for (cell_name, update) in &updates {
                debug!(
                    "Updating cell '{}' path: {:?} -> {:?}",
                    cell_name, update.old_source_path, update.new_source_path
                );
                cell_paths.insert(cell_name.clone(), update.new_source_path.clone());
            }
        }

        self.invalidate_cell_caches(&affected_cells);
        Some(updates.len())
    }

    /// Invalidate cached inodes for the specified cells
    pub fn invalidate_cell_caches(&self, cell_names: &[String]) {
        let cell_paths = self.cell_paths.read().unwrap();
        let cell_source_paths: Vec<PathBuf> = cell_names
            .iter()
            .filter_map(|name| cell_paths.get(name).cloned())
            .collect();
        drop(cell_paths);

        let mut path_map = self.path_map.write().unwrap();
        let mut inode_map = self.inode_map.write().unwrap();

        let inodes_to_remove: Vec<u64> = path_map
            .iter()
            .filter_map(|(path, &ino)| {
                for cell_path in &cell_source_paths {
                    if path.starts_with(cell_path) {
                        return Some(ino);
                    }
                }
                None
            })
            .collect();

        let removed_count = inodes_to_remove.len();

        path_map.retain(|path, _| {
            !cell_source_paths.iter().any(|cp| path.starts_with(cp))
        });

        for ino in inodes_to_remove {
            if let Some(InodePath::Real { .. }) = inode_map.get(&ino) {
                inode_map.remove(&ino);
            }
        }

        debug!(
            "Invalidated caches for {} cells, removed {} inode mappings",
            cell_names.len(),
            removed_count
        );
    }

    /// Check if there are pending updates that need to be applied
    pub fn has_pending_updates(&self) -> bool {
        self.state_machine.has_pending_updates()
    }

    // -----------------------------------------------------------------------
    // Path-based resolution (for macOS high-level FUSE API)
    // -----------------------------------------------------------------------

    /// Resolve a FUSE path string to a `ResolvedPath`.
    ///
    /// This is the path-based equivalent of the inode lookup chain used in the
    /// `Filesystem` trait methods, intended for use by the macOS high-level
    /// (path-based) FUSE API.
    ///
    /// Paths are expected to start with "/" and use the configured
    /// `source_dir_name` and `cell_prefix`.
    /// Check if a filename matches any exclusion pattern.
    ///
    /// Patterns support:
    /// - Exact match: `.envrc` matches `.envrc`
    /// - Prefix glob: `.buck*` matches `.buckconfig`, `.buckroot`
    /// - Suffix glob: `*.toml` matches `go-deps.toml`
    /// - Contains glob: `*deps*` matches `go-deps.toml`, `rustdeps`
    pub fn is_excluded(&self, name: &str) -> bool {
        let name = name.trim_end_matches('/');
        self.config.exclude.iter().any(|pattern| {
            let pattern = pattern.trim_end_matches('/');
            if pattern.contains('*') {
                glob_match(pattern, name)
            } else {
                pattern == name
            }
        })
    }

    pub fn resolve_path(&self, path: &str) -> ResolvedPath {
        // Normalise: strip leading '/' and trailing '/'
        let path = path.trim_start_matches('/').trim_end_matches('/');

        if path.is_empty() {
            return ResolvedPath::Root;
        }

        // Split into first component and the rest
        let (first, rest) = match path.find('/') {
            Some(pos) => (&path[..pos], Some(&path[pos + 1..])),
            None => (path, None),
        };

        // --- virtual files at mount root ---
        if rest.is_none() {
            if first == ".buckconfig" {
                return ResolvedPath::VirtualFile {
                    file: VirtualFile::BuckConfig,
                };
            }
            if first == ".buckroot" {
                return ResolvedPath::VirtualFile {
                    file: VirtualFile::BuckRoot,
                };
            }
            if first == ".envrc" {
                return ResolvedPath::VirtualFile {
                    file: VirtualFile::Envrc,
                };
            }
        }

        // --- output mount branch ---
        for om in &self.config.output_mounts {
            if first == om.mount_as {
                return match rest {
                    None => ResolvedPath::OutputMount {
                        real_path: om.real_path.clone(),
                    },
                    Some(remainder) => ResolvedPath::OutputChild {
                        real_path: om.real_path.join(remainder),
                    },
                };
            }
        }

        // --- source directory branch ---
        if first == self.config.source_dir_name {
            return match rest {
                None => ResolvedPath::Source,
                Some(remainder) => {
                    // Check exclusion list against the first component under root/
                    let first_component = remainder.split('/').next().unwrap_or(remainder);
                    if self.is_excluded(first_component) {
                        return ResolvedPath::NotFound;
                    }
                    let real_path = self.repo_root.join(remainder);
                    ResolvedPath::SourceChild { real_path }
                }
            };
        }

        // --- cell prefix branch ---
        if first == self.config.cell_prefix {
            return match rest {
                None => ResolvedPath::CellPrefix,
                Some(remainder) => {
                    let (cell_name, child) = match remainder.find('/') {
                        Some(pos) => (&remainder[..pos], Some(&remainder[pos + 1..])),
                        None => (remainder, None),
                    };

                    let cell_paths = self.cell_paths.read().unwrap();
                    if let Some(cell_source) = cell_paths.get(cell_name) {
                        match child {
                            None => ResolvedPath::Cell {
                                name: cell_name.to_string(),
                                real_path: cell_source.clone(),
                            },
                            Some(child_path) => ResolvedPath::CellChild {
                                cell_name: cell_name.to_string(),
                                real_path: cell_source.join(child_path),
                            },
                        }
                    } else {
                        ResolvedPath::NotFound
                    }
                }
            };
        }

        ResolvedPath::NotFound
    }
}

/// Simple glob matching with `*` wildcard.
///
/// Supports: `*.ext`, `prefix*`, `*mid*`, `exact`, and `pre*suf`.
fn glob_match(pattern: &str, name: &str) -> bool {
    if !pattern.contains('*') {
        return pattern == name;
    }

    let parts: Vec<&str> = pattern.split('*').collect();

    if parts.len() == 2 {
        let (prefix, suffix) = (parts[0], parts[1]);
        if prefix.is_empty() && suffix.is_empty() {
            return true; // "*" matches everything
        }
        if prefix.is_empty() {
            return name.ends_with(suffix); // "*.ext"
        }
        if suffix.is_empty() {
            return name.starts_with(prefix); // "prefix*"
        }
        return name.starts_with(prefix) && name.ends_with(suffix)
            && name.len() >= prefix.len() + suffix.len(); // "pre*suf"
    }

    // Multi-wildcard: check each part appears in order
    let mut remaining = name;
    for (i, part) in parts.iter().enumerate() {
        if part.is_empty() {
            continue;
        }
        if i == 0 {
            // First part must be a prefix
            if !remaining.starts_with(part) {
                return false;
            }
            remaining = &remaining[part.len()..];
        } else if i == parts.len() - 1 {
            // Last part must be a suffix
            if !remaining.ends_with(part) {
                return false;
            }
        } else {
            // Middle parts must appear somewhere
            if let Some(pos) = remaining.find(part) {
                remaining = &remaining[pos + part.len()..];
            } else {
                return false;
            }
        }
    }
    true
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::CellConfig;

    #[test]
    fn test_glob_match() {
        // Exact match
        assert!(glob_match(".envrc", ".envrc"));
        assert!(!glob_match(".envrc", ".envrc2"));

        // Prefix glob
        assert!(glob_match(".buck*", ".buckconfig"));
        assert!(glob_match(".buck*", ".buckroot"));
        assert!(!glob_match(".buck*", ".git"));

        // Suffix glob
        assert!(glob_match("*.toml", "go-deps.toml"));
        assert!(glob_match("*.toml", "rust-deps.toml"));
        assert!(!glob_match("*.toml", "Cargo.lock"));

        // Contains glob
        assert!(glob_match("*deps*", "go-deps.toml"));
        assert!(glob_match("*deps*", "rustdeps"));
        assert!(!glob_match("*deps*", "flake.nix"));

        // Wildcard matches everything
        assert!(glob_match("*", "anything"));

        // Prefix+suffix
        assert!(glob_match(".git*e", ".gitignore"));
        assert!(!glob_match(".git*e", ".gitconfig"));

        // No wildcard = exact
        assert!(glob_match("exact", "exact"));
        assert!(!glob_match("exact", "inexact"));
    }

    fn test_core(config: CompositionConfig, repo_root: PathBuf) -> FsCore {
        let sm = Arc::new(ConsistencyStateMachine::new());
        FsCore::new(config, repo_root, sm)
    }

    #[test]
    fn test_resolve_path_root() {
        let config = CompositionConfig::new("/mnt", "/repo");
        let core = test_core(config, PathBuf::from("/repo"));
        assert!(matches!(core.resolve_path("/"), ResolvedPath::Root));
    }

    #[test]
    fn test_resolve_path_source() {
        let config = CompositionConfig::new("/mnt", "/repo");
        let core = test_core(config, PathBuf::from("/repo"));
        assert!(matches!(
            core.resolve_path("/root"),
            ResolvedPath::Source
        ));
    }

    #[test]
    fn test_resolve_path_source_child() {
        let config = CompositionConfig::new("/mnt", "/repo");
        let core = test_core(config, PathBuf::from("/repo"));
        match core.resolve_path("/root/src/main.rs") {
            ResolvedPath::SourceChild { real_path } => {
                assert_eq!(real_path, PathBuf::from("/repo/src/main.rs"));
            }
            other => panic!("expected SourceChild, got {:?}", other),
        }
    }

    #[test]
    fn test_resolve_path_virtual_buckconfig() {
        let config = CompositionConfig::new("/mnt", "/repo");
        let core = test_core(config, PathBuf::from("/repo"));
        assert!(matches!(
            core.resolve_path("/root/.buckconfig"),
            ResolvedPath::VirtualFile {
                file: VirtualFile::BuckConfig
            }
        ));
    }

    #[test]
    fn test_resolve_path_virtual_buckroot() {
        let config = CompositionConfig::new("/mnt", "/repo");
        let core = test_core(config, PathBuf::from("/repo"));
        assert!(matches!(
            core.resolve_path("/root/.buckroot"),
            ResolvedPath::VirtualFile {
                file: VirtualFile::BuckRoot
            }
        ));
    }

    #[test]
    fn test_resolve_path_cell_prefix() {
        let config = CompositionConfig::new("/mnt", "/repo");
        let core = test_core(config, PathBuf::from("/repo"));
        assert!(matches!(
            core.resolve_path("/external"),
            ResolvedPath::CellPrefix
        ));
    }

    #[test]
    fn test_resolve_path_cell() {
        let config = CompositionConfig::new("/mnt", "/repo")
            .with_cell(CellConfig::new("godeps", "/nix/store/godeps"));
        let core = test_core(config, PathBuf::from("/repo"));
        match core.resolve_path("/external/godeps") {
            ResolvedPath::Cell { name, real_path } => {
                assert_eq!(name, "godeps");
                assert_eq!(real_path, PathBuf::from("/nix/store/godeps"));
            }
            other => panic!("expected Cell, got {:?}", other),
        }
    }

    #[test]
    fn test_resolve_path_cell_child() {
        let config = CompositionConfig::new("/mnt", "/repo")
            .with_cell(CellConfig::new("godeps", "/nix/store/godeps"));
        let core = test_core(config, PathBuf::from("/repo"));
        match core.resolve_path("/external/godeps/vendor/foo/bar.go") {
            ResolvedPath::CellChild {
                cell_name,
                real_path,
            } => {
                assert_eq!(cell_name, "godeps");
                assert_eq!(
                    real_path,
                    PathBuf::from("/nix/store/godeps/vendor/foo/bar.go")
                );
            }
            other => panic!("expected CellChild, got {:?}", other),
        }
    }

    #[test]
    fn test_resolve_path_not_found() {
        let config = CompositionConfig::new("/mnt", "/repo");
        let core = test_core(config, PathBuf::from("/repo"));
        assert!(matches!(
            core.resolve_path("/nonexistent"),
            ResolvedPath::NotFound
        ));
    }
}
