//! `tk completion`: buck2's completion scripts, made tk's

/// What `tk completion` adds to bash's completion: the handlers of tk's own
/// subcommands
const BASH_TK_COMPLETIONS: &str = r#"
        tk__check)
            opts="-v -h --verbose --help"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            ;;
        tk__sync)
            opts="-v -n -h --verbose --dry-run --help"
            if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
                return 0
            fi
            ;;
"#;

/// What `tk completion` appends to fish's completion: tk's own flags and
/// subcommands
const FISH_TK_FLAGS: &str = r#"
# tk-specific flags
complete -c tk -n "__fish_tk_needs_command" -l no-sync -d 'Skip sync, run buck2 directly'
complete -c tk -n "__fish_tk_needs_command" -s n -l dry-run -d 'Show what would be synced'

# tk-specific subcommands
complete -c tk -n "__fish_tk_needs_command" -a sync -d 'Synchronize generated files'
complete -c tk -n "__fish_tk_needs_command" -a check -d 'Check if files are stale'

# sync subcommand options
complete -c tk -n "__fish_seen_subcommand_from sync" -s v -l verbose -d 'Show verbose output'
complete -c tk -n "__fish_seen_subcommand_from sync" -s n -l dry-run -d 'Show what would be synced'

# check subcommand options
complete -c tk -n "__fish_seen_subcommand_from check" -s v -l verbose -d 'Show verbose output'
"#;

/// A shell `tk completion` writes a script for
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Shell {
    /// bash
    Bash,
    /// zsh
    Zsh,
    /// fish
    Fish,
}

impl Shell {
    /// The shell's name, as buck2 completion takes it
    pub fn as_str(self) -> &'static str {
        match self {
            Shell::Bash => "bash",
            Shell::Zsh => "zsh",
            Shell::Fish => "fish",
        }
    }
}

/// The shell `tk completion` is asked for, or the message tk exits 1 with
pub fn parse_args<S: AsRef<str>>(args: &[S]) -> Result<Shell, String> {
    let Some(shell) = args.first() else {
        return Err("Usage: tk completion <bash|zsh|fish>".into());
    };
    match shell.as_ref() {
        "bash" => Ok(Shell::Bash),
        "zsh" => Ok(Shell::Zsh),
        "fish" => Ok(Shell::Fish),
        other => Err(format!(
            "tk: unsupported shell: {other} (use bash, zsh, or fish)"
        )),
    }
}

/// buck2's completion script for `shell`, made tk's
pub fn transform(script: &str, shell: Shell) -> String {
    match shell {
        Shell::Bash => transform_bash(script),
        Shell::Zsh => transform_zsh(script),
        Shell::Fish => transform_fish(script),
    }
}

fn transform_bash(script: &str) -> String {
    // The function's name and references
    let mut script = script
        .replace("_buck2()", "_tk()")
        .replace("_buck2 ", "_tk ")
        .replace("complete -F _buck2", "complete -F _tk")
        .replace("buck2__", "tk__")
        .replace("\"buck2\"", "\"tk\"")
        .replace("buck2,", "tk,")
        .replace(",buck2)", ",tk)");

    // tk's subcommands in the case statement: check before completion, and
    // sync after check
    script = script.replacen(
        "tk,completion)\n                cmd=\"tk__completion\"",
        "tk,check)\n                cmd=\"tk__check\"\n                ;;\n            tk,completion)\n                cmd=\"tk__completion\"",
        1,
    );
    script = script.replacen(
        "tk,check)\n                cmd=\"tk__check\"",
        "tk,check)\n                cmd=\"tk__check\"\n                ;;\n            tk,sync)\n                cmd=\"tk__sync\"",
        1,
    );

    // tk's flags among the main options, and its subcommands after
    // completion
    script = script.replacen(
        "opts=\"-v -h -V --isolation-dir",
        "opts=\"--no-sync --dry-run -v -h -V --isolation-dir",
        1,
    );
    script = script.replacen("completion docs", "completion sync check docs", 1);

    // The handlers of tk's subcommands, after tk__completion's case
    if let Some(idx) = script.find("tk__completion)") {
        let end = script[idx..]
            .find("\n        tk__")
            .or_else(|| script[idx..].find("\n    esac"));
        if let Some(end) = end {
            script.insert_str(idx + end, BASH_TK_COMPLETIONS);
        }
    }

    script.replacen(
        "# @generated by `buck2 completion bash`",
        "# @generated by `tk completion bash` (based on buck2 completion)",
        1,
    )
}

fn transform_zsh(script: &str) -> String {
    script
        .replace("_buck2", "_tk")
        .replace("#compdef buck2", "#compdef tk")
        .replace("'buck2'", "'tk'")
        .replace("\"buck2\"", "\"tk\"")
        .replace("buck2:", "tk:")
        // tk's flags among the global options
        .replacen(
            "'--isolation-dir",
            "'--no-sync[Skip sync, run buck2 directly]' '--dry-run[Show what would be synced]' '--isolation-dir",
            1,
        )
        // tk's subcommands
        .replacen(
            "'completion:Print completion configuration for shell'",
            "'completion:Print completion configuration for shell' 'sync:Synchronize generated files' 'check:Check if files are stale'",
            1,
        )
        .replacen(
            "# @generated by `buck2 completion zsh`",
            "# @generated by `tk completion zsh` (based on buck2 completion)",
            1,
        )
}

fn transform_fish(script: &str) -> String {
    let script = script
        .replace("complete -c buck2", "complete -c tk")
        .replace("__fish_buck2", "__fish_tk")
        .replace("'buck2'", "'tk'")
        .replace("\"buck2\"", "\"tk\"")
        + FISH_TK_FLAGS;
    script.replacen(
        "# @generated by `buck2 completion fish`",
        "# @generated by `tk completion fish` (based on buck2 completion)",
        1,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn args() {
        assert_eq!(parse_args(&["bash"]), Ok(Shell::Bash));
        assert_eq!(parse_args(&["zsh", "x"]), Ok(Shell::Zsh));
        assert_eq!(parse_args(&["fish"]), Ok(Shell::Fish));
        assert!(parse_args::<&str>(&[]).unwrap_err().starts_with("Usage"));
        assert!(
            parse_args(&["pwsh"])
                .unwrap_err()
                .contains("unsupported shell: pwsh")
        );
    }

    /// The parts of buck2's bash completion the transform rewrites
    const BASH: &str = "# @generated by `buck2 completion bash`
_buck2() {
    for i in ${COMP_WORDS[@]}
    do
        case \"${cmd},${i}\" in
            \",$1\")
                cmd=\"buck2\"
                ;;
            buck2,completion)
                cmd=\"buck2__completion\"
                ;;
            buck2,docs)
                cmd=\"buck2__docs\"
                ;;
        esac
    done

    case \"${cmd}\" in
        buck2)
            opts=\"-v -h -V --isolation-dir build completion docs\"
            ;;
        buck2__completion)
            opts=\"-h\"
            ;;
        buck2__docs)
            opts=\"-h\"
            ;;
    esac
}

complete -F _buck2 -o nosort -o bashdefault -o default buck2
";

    #[test]
    fn bash() {
        let got = transform(BASH, Shell::Bash);
        let want = format!(
            "# @generated by `tk completion bash` (based on buck2 completion)
_tk() {{
    for i in ${{COMP_WORDS[@]}}
    do
        case \"${{cmd}},${{i}}\" in
            \",$1\")
                cmd=\"tk\"
                ;;
            tk,check)
                cmd=\"tk__check\"
                ;;
            tk,sync)
                cmd=\"tk__sync\"
                ;;
            tk,completion)
                cmd=\"tk__completion\"
                ;;
            tk,docs)
                cmd=\"tk__docs\"
                ;;
        esac
    done

    case \"${{cmd}}\" in
        buck2)
            opts=\"--no-sync --dry-run -v -h -V --isolation-dir build completion sync check docs\"
            ;;
        tk__completion)
            opts=\"-h\"
            ;;{BASH_TK_COMPLETIONS}
        tk__docs)
            opts=\"-h\"
            ;;
    esac
}}

complete -F _tk -o nosort -o bashdefault -o default buck2
"
        );
        assert_eq!(got, want);
    }

    #[test]
    fn bash_handlers_go_before_esac_after_the_last_case() {
        let script = "        buck2__completion)\n            ;;\n    esac\n";
        assert_eq!(
            transform(script, Shell::Bash),
            format!("        tk__completion)\n            ;;{BASH_TK_COMPLETIONS}\n    esac\n")
        );
        // Nowhere to put them: left out
        assert_eq!(transform("no cases", Shell::Bash), "no cases");
    }

    #[test]
    fn zsh() {
        let script = "#compdef buck2
# @generated by `buck2 completion zsh`
_buck2() {
    _arguments '--isolation-dir=[dir]' '--isolation-dir=[again]'
    local commands; commands=('completion:Print completion configuration for shell' 'docs:Docs')
    _describe -t commands 'buck2 commands' commands \"buck2\" 'buck2'
}
";
        assert_eq!(
            transform(script, Shell::Zsh),
            "#compdef tk
# @generated by `tk completion zsh` (based on buck2 completion)
_tk() {
    _arguments '--no-sync[Skip sync, run buck2 directly]' '--dry-run[Show what would be synced]' '--isolation-dir=[dir]' '--isolation-dir=[again]'
    local commands; commands=('completion:Print completion configuration for shell' 'sync:Synchronize generated files' 'check:Check if files are stale' 'docs:Docs')
    _describe -t commands 'buck2 commands' commands \"tk\" 'tk'
}
"
        );
    }

    #[test]
    fn fish() {
        let script = "# @generated by `buck2 completion fish`
function __fish_buck2_needs_command
end
complete -c buck2 -n \"__fish_buck2_needs_command\" -a 'buck2'
";
        assert_eq!(
            transform(script, Shell::Fish),
            format!(
                "# @generated by `tk completion fish` (based on buck2 completion)
function __fish_tk_needs_command
end
complete -c tk -n \"__fish_tk_needs_command\" -a 'tk'
{FISH_TK_FLAGS}"
            )
        );
    }
}
