# The .buckconfig turnkey generates, as text.
#
# Pure: from the Nix-backed cells, the protocol code and the test cache's
# settings. buck2.nix writes it to the store and symlinks .buckconfig to it;
# checks.buck2-generators tests it.
#
# isolation_dir is set through BUCK_ISOLATION_DIR, not here: Buck2 ignores
# the config file setting for it.
{ lib }:

{
  # [ { name, path } ]: the cells whose content comes from Nix, symlinked
  # under .turnkey/
  cells,
  # Where the toolchains cell is symlinked
  toolchainsCellPath,
  # turnkey-test-runner's protocol code (nix/packages/test-runner-protocol.nix)
  testRunnerProtocol,
  # null, or { runner, path, address, tls }: turnkey's test runner, the PATH
  # cached tests get, and the cache endpoint buck2's RE client reads from
  testCache,
}:

let
  cellsConfig = lib.concatMapStringsSep "\n" (cell: "    ${cell.name} = ${cell.path}") cells;
  platformDetectors = lib.concatMapStringsSep "" (
    cell: " target:${cell.name}//...->prelude//platforms:default"
  ) cells;
in
''
  # Generated by turnkey - do not edit manually

  [cells]
      root = .
      toolchains = ${toolchainsCellPath}
      none = none
  ${cellsConfig}

  [cell_aliases]
      config = prelude
      ovr_config = prelude
      fbcode = none
      fbsource = none
      fbcode_macros = none
      buck = none

  [parser]
      target_platform_detector_spec = target:root//...->prelude//platforms:default target:toolchains//...->prelude//platforms:default${platformDetectors}

  [buildfile]
      name = rules.star

  [build]
      execution_platforms = prelude//platforms:default

  [turnkey]
      test_runner_protocol = ${testRunnerProtocol}
''
+ lib.optionalString (testCache != null) ''
      test_cache = true
      test_path = ${testCache.path}

  [test]
      v2_test_executor = ${testCache.runner}/bin/turnkey-test-runner

  [buck2_re_client]
      engine_address = ${testCache.address}
      action_cache_address = ${testCache.address}
      cas_address = ${testCache.address}
      tls = ${lib.boolToString testCache.tls}
''
