# Go dependencies cell builder
#
# Takes a Go deps registry and builds a Buck2 cell containing
# all dependencies with generated BUCK files.

{ pkgs, lib, registry }:

let
  # Convert import path to vendor directory path
  # "github.com/google/uuid" -> "vendor/github.com/google/uuid"
  importToVendorPath = importPath: "vendor/${importPath}";

  # Convert import path to Buck2 target name (last component)
  # "github.com/google/uuid" -> "uuid"
  importToTargetName = importPath:
    lib.last (lib.splitString "/" importPath);

  # Generate BUCK file content for a Go library
  generateBuckFile = importPath: dep:
    let
      targetName = importToTargetName importPath;
      # Convert dep import paths to Buck2 target references
      depTargets = map (d: "\"godeps//${importToVendorPath d}:${importToTargetName d}\"") (dep.deps or [ ]);
      depsAttr = if depTargets == [ ] then "" else ''
        deps = [
            ${lib.concatStringsSep ",\n            " depTargets},
        ],'';
    in
    ''
      # Auto-generated by turnkey
      go_library(
          name = "${targetName}",
          srcs = glob(["*.go"], exclude = ["*_test.go"]),
          package_name = "${importPath}",${lib.optionalString (depsAttr != "") "\n        ${depsAttr}"}
          visibility = ["PUBLIC"],
      )
    '';

  # Generate shell commands to set up one dependency
  setupDep = importPath: dep:
    let
      vendorPath = importToVendorPath importPath;
      buckContent = generateBuckFile importPath dep;
    in
    ''
      # Set up ${importPath}
      mkdir -p $out/${vendorPath}
      cp ${dep.src}/*.go $out/${vendorPath}/ 2>/dev/null || true

      # Generate BUCK file
      cat > $out/${vendorPath}/BUCK <<'BUCK'
      ${buckContent}
      BUCK
    '';

  # All setup commands
  allSetupCommands = lib.concatStringsSep "\n" (
    lib.mapAttrsToList setupDep registry
  );

in
pkgs.runCommand "go-deps-cell" { } ''
  mkdir -p $out/vendor

  ${allSetupCommands}

  # Generate root BUCK file (empty, just for cell validity)
  cat > $out/BUCK <<'BUCK'
  # Go dependencies cell - packages are in vendor/
  BUCK

  # Generate cell .buckconfig
  cat > $out/.buckconfig <<'BUCKCONFIG'
  [cells]
      godeps = .
      prelude = prelude

  [buildfile]
      name = BUCK
  BUCKCONFIG
''
