# Example Go dependencies cell
#
# This is a manual implementation for the simple case (uuid only).
# A proper implementation would parse go.mod/go.sum and generate this.

{ pkgs, lib }:

let
  # Fetch the uuid package source
  uuidSrc = pkgs.fetchFromGitHub {
    owner = "google";
    repo = "uuid";
    rev = "v1.6.0";
    sha256 = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw=";
  };

  # Generate BUCK file for the uuid package
  uuidBuck = ''
    # Auto-generated by turnkey
    load("@prelude//go:defs.bzl", "go_library")

    go_library(
        name = "uuid",
        srcs = glob(["*.go"], exclude = ["*_test.go"]),
        importpath = "github.com/google/uuid",
        visibility = ["PUBLIC"],
    )
  '';

in
pkgs.runCommand "go-deps-cell" { } ''
  mkdir -p $out/vendor/github.com/google/uuid

  # Copy uuid source files
  cp ${uuidSrc}/*.go $out/vendor/github.com/google/uuid/

  # Generate BUCK file for uuid
  cat > $out/vendor/github.com/google/uuid/BUCK <<'BUCK'
  ${uuidBuck}
  BUCK

  # Generate root BUCK file (empty, just for cell validity)
  cat > $out/BUCK <<'BUCK'
  # Go dependencies cell - packages are in vendor/
  BUCK

  # Generate cell .buckconfig
  cat > $out/.buckconfig <<'BUCKCONFIG'
  [cells]
      godeps = .
      prelude = prelude

  [buildfile]
      name = BUCK
  BUCKCONFIG
''
