# Go dependencies cell builder
#
# Reads a go-deps.toml file and builds a Buck2 cell containing
# all dependencies with BUCK files generated by gobuckify.
#
# The TOML file format:
#   [deps."github.com/foo/bar"]
#   version = "v1.0.0"
#   hash = "sha256-..."
#
# This allows downstream repos to declare deps in pure data files.

{ pkgs, lib, depsFile, gobuckify }:

let
  # Parse the TOML file
  depsToml = builtins.fromTOML (builtins.readFile depsFile);

  # Convert TOML deps to registry format
  registry = lib.mapAttrs (importPath: dep: {
    inherit (dep) version;
    deps = dep.deps or [ ];
    src = fetchSource importPath dep;
  }) (depsToml.deps or { });

  # Fetch source based on import path pattern
  fetchSource = importPath: dep:
    let
      parts = lib.splitString "/" importPath;
      host = lib.elemAt parts 0;
    in
    if host == "github.com" then
      pkgs.fetchFromGitHub {
        owner = dep.owner or (lib.elemAt parts 1);
        repo = dep.repo or (lib.elemAt parts 2);
        rev = dep.version;
        sha256 = dep.hash;
      }
    # golang.org/x/* -> github.com/golang/*
    else if host == "golang.org" && lib.elemAt parts 1 == "x" then
      pkgs.fetchFromGitHub {
        owner = "golang";
        repo = lib.elemAt parts 2;
        rev = dep.version;
        sha256 = dep.hash;
      }
    # gopkg.in/yaml.v3 -> github.com/go-yaml/yaml
    # gopkg.in/user/pkg.v2 -> github.com/user/pkg
    else if host == "gopkg.in" then
      let
        # Remove .vN suffix from package name
        stripVersion = name:
          let m = builtins.match "(.+)\\.v[0-9]+" name;
          in if m != null then lib.elemAt m 0 else name;
        # gopkg.in/yaml.v3 (single element) vs gopkg.in/user/pkg.v2 (two elements)
        isSingleElement = lib.length parts == 2;
        owner = if isSingleElement then "go-${stripVersion (lib.elemAt parts 1)}" else lib.elemAt parts 1;
        repo = if isSingleElement then stripVersion (lib.elemAt parts 1) else stripVersion (lib.elemAt parts 2);
      in
      pkgs.fetchFromGitHub {
        inherit owner repo;
        rev = dep.version;
        sha256 = dep.hash;
      }
    # go.uber.org/* -> github.com/uber-go/*
    else if host == "go.uber.org" then
      pkgs.fetchFromGitHub {
        owner = "uber-go";
        repo = lib.elemAt parts 1;
        rev = dep.version;
        sha256 = dep.hash;
      }
    else
      throw "Unsupported import path host: ${host}. Supported: github.com, golang.org/x, gopkg.in, go.uber.org";

  # Generate shell commands to copy one dependency (full source tree)
  copyDep = importPath: dep:
    let
      vendorPath = "vendor/${importPath}";
    in
    ''
      # Copy ${importPath}
      mkdir -p $out/${vendorPath}
      cp -r ${dep.src}/* $out/${vendorPath}/
      # Make writable so gobuckify can create BUCK files
      chmod -R u+w $out/${vendorPath}
    '';

  # All copy commands
  allCopyCommands = lib.concatStringsSep "\n" (
    lib.mapAttrsToList copyDep registry
  );

  # Generate go.mod content for gobuckify
  # Lists all deps as require directives
  goModContent =
    let
      requires = lib.mapAttrsToList (path: dep: "\t${path} ${dep.version}") registry;
    in
    ''
      module godeps

      go 1.21

      require (
      ${lib.concatStringsSep "\n" requires}
      )
    '';

  # Module version data for shell script
  moduleVersions = lib.mapAttrsToList (module: dep: {
    inherit module;
    version = dep.version;
  }) registry;

  # gobuckify configuration
  # Note: JSON field names are snake_case, matching Go struct tags
  gobuckifyConfig = builtins.toJSON {
    buck = {
      # Note: preambule (sic) must end with newline for valid BUCK syntax
      preambule = "# Auto-generated by turnkey gobuckify\n";
      go_library_rule = "go_library";
      deps_target_label_prefix = "godeps//vendor/";
      deps_attr = "deps";
    };
    platforms = [
      { go_os = "linux"; go_arch = "amd64"; buck_os = "linux"; buck_arch = "x86_64"; }
      { go_os = "linux"; go_arch = "arm64"; buck_os = "linux"; buck_arch = "aarch64"; }
      { go_os = "darwin"; go_arch = "amd64"; buck_os = "macos"; buck_arch = "x86_64"; }
      { go_os = "darwin"; go_arch = "arm64"; buck_os = "macos"; buck_arch = "arm64"; }
    ];
    default_tags = [ ];
  };

in
pkgs.runCommand "go-deps-cell" {
  nativeBuildInputs = [ pkgs.go pkgs.findutils gobuckify ];
  # Go needs a writable cache directory
  HOME = "/tmp";
  GOCACHE = "/tmp/go-cache";
} ''
  mkdir -p $out/vendor

  # Copy all dependency sources
  ${allCopyCommands}

  # Discover all Go packages by finding directories with .go files
  # Exclude testdata directories and test-only packages
  # Note: internal packages ARE included since they may be needed as deps
  echo "Discovering Go packages..."
  find $out/vendor -type f -name '*.go' ! -name '*_test.go' -printf '%h\n' | \
    sort -u | \
    grep -v '/testdata/' > /tmp/all_packages.txt || true

  # Convert absolute paths to import paths
  sed -i "s|$out/vendor/||g" /tmp/all_packages.txt

  echo "Found $(wc -l < /tmp/all_packages.txt) packages"

  # Generate vendor/modules.txt
  # Format: module header, ## explicit, then all packages belonging to that module
  {
    ${lib.concatStringsSep "\n    " (lib.mapAttrsToList (module: dep: ''
    echo "# ${module} ${dep.version}"
    echo "## explicit"
    grep -E "^${lib.escapeRegex module}(/|$)" /tmp/all_packages.txt || true
    '') registry)}
  } > $out/vendor/modules.txt

  echo "Generated modules.txt:"
  cat $out/vendor/modules.txt

  # Create go.mod for gobuckify
  cat > $out/go.mod << 'GOMOD'
  ${goModContent}
  GOMOD

  # Generate main.go that imports all discovered packages
  {
    echo "package main"
    echo ""
    echo "import ("
    while read import_path; do
      echo "	_ \"$import_path\""
    done < /tmp/all_packages.txt
    echo ")"
    echo ""
    echo "func main() {}"
  } > $out/main.go

  echo "Generated main.go with $(wc -l < /tmp/all_packages.txt) imports"

  # Create gobuckify config
  cat > $out/gobuckify.json << 'CONFIG'
  ${gobuckifyConfig}
  CONFIG

  # Run gobuckify to generate BUCK files
  cd $out
  gobuckify .

  # Generate cell .buckconfig
  cat > $out/.buckconfig << 'BUCKCONFIG'
  [cells]
      godeps = .
      prelude = prelude

  [buildfile]
      name = BUCK
  BUCKCONFIG
''
