# JavaScript dependencies cell builder
#
# Reads a js-deps.toml file and builds a Buck2 cell containing
# all npm dependencies with BUCK files.
#
# The TOML file format (generated by jsdeps-gen):
#   [meta]
#   generator = "jsdeps-gen 0.1.0"
#   lockfile_version = "9.0"
#
#   [[package]]
#   name = "lodash"
#   version = "4.17.21"
#   url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz"
#   integrity = "sha512-..."
#   dependencies = ["dep1", "dep2"]
#
# This is a thin wrapper around the deps-cell library.

{ pkgs, lib, depsFile }:

let
  depsCell = import ../lib/deps-cell { inherit pkgs lib; };
in
depsCell.mkJsDepsCell {
  inherit depsFile;
}
