# turnkey's Buck2 integration options, declared once.
#
# Both the flake-parts module (turnkey.toolchains.buck2) and the devenv
# module (turnkey.buck2) use this as their option type. The flake-parts
# module adds what is flake-level (which shells get Buck2) and builds the
# dependency cells; the devenv module adds the inputs the flake-parts module
# injects (the pinned buck2, turnkey's prelude, the built cells).
{ lib, version }:

let
  inherit (lib) mkOption types;

  # Removed options, kept hidden so that setting one is an error that says
  # what to do. The modules read them to trigger it.
  removedOption =
    name: why:
    mkOption {
      type = types.nullOr types.unspecified;
      default = null;
      visible = false;
      apply = value: if value == null then null else throw "turnkey: buck2.${name} is removed: ${why}";
    };

  removed =
    name:
    removedOption "prelude.${name}" "turnkey always uses its own prelude, part of the pinned buck2 release (docs/adr/0002-turnkey-owns-the-buck2-version.md). Remove it; set buck2.prelude.path only to use a prelude of your own, which turns test result caching off.";

  # Deps files are regenerated only by tk sync, from the rules in
  # .turnkey/sync.toml
  # Rules sync derives internal targets from each language's manifest and
  # uses turnkey's fixed deps cell names; nothing ever read these
  removedRulesGo =
    name:
    removedOption "rules.go.${name}" "tk rules sync derives internal targets from each language's own manifest (go.mod, Cargo.toml, the uv workspace) and uses turnkey's fixed deps cell names (godeps, ...); nothing read it. Remove it.";

  removedFixups =
    name:
    removedOption "rust.${name}" "fixups are fixup sets now (docs/adr/0003-fixup-sets-are-modules.md). Write this repository's fixups in turnkey.toolchains.buck2.fixups, as rust.<crate>.buildScript.generate and rust.<crate>.rustcFlags, or import a published set; see docs/user-manual/src/workflows/fixups.md. Remove it.";

  removedRegeneration =
    name:
    removedOption "go.${name}" "go-deps.toml is regenerated by tk sync, like every deps file: on shell entry (buck2.tk.syncOnShellEntry), by direnv's use_turnkey, and before tk build and tk test. Remove it; the tk check pre-commit hook (buck2.tk.preCommitCheck) catches a stale go-deps.toml.";
in
{
  options = {
    version = mkOption {
      type = types.str;
      default = version;
      readOnly = true;
      description = ''
        The pinned buck2 release (a release date). Read-only: each turnkey
        revision ships exactly one buck2 release, and a consumer moves to
        another by moving to another turnkey revision
        (docs/adr/0002-turnkey-owns-the-buck2-version.md).
      '';
    };

    prelude.strategy = removed "strategy";
    prelude.gitOrigin = removed "gitOrigin";
    prelude.commitHash = removed "commitHash";

    enable = mkOption {
      type = types.bool;
      default = false;
      description = ''
        Enable the Buck2 integration: the pinned buck2, the prelude,
        toolchain generation from toolchain.toml and the dependency cells.
        Through the flake-parts module, only the shells listed in
        `buck2.shells` get it.
      '';
    };

    platforms = mkOption {
      type = types.listOf types.str;
      default = [
        "x86_64-linux"
        "aarch64-linux"
        "x86_64-darwin"
        "aarch64-darwin"
      ];
      defaultText = lib.literalMD "the flake's `systems`, through the flake-parts module; otherwise the four above";
      example = [
        "x86_64-linux"
        "aarch64-darwin"
      ];
      description = ''
        The platforms the project builds for, as Nix systems. Rules sync
        resolves each target's deps on every one of them, so what it
        writes doesn't depend on the machine it runs on, and writes deps
        that differ between them as a `select()` on `config//os:<os>`, or
        on the combined `toolchains//conditions:<os>-<cpu>` when they
        differ by CPU within one OS. With no branch for other platforms,
        building for one that isn't listed fails instead of silently
        missing deps.
      '';
    };

    ignore = mkOption {
      type = types.listOf types.str;
      default = [ ];
      example = [ "e2e/fixtures" ];
      description = ''
        Directories, relative to the project root, that buck2 doesn't see:
        written to `.buckconfig`'s `project.ignore`, so `//...` skips their
        `rules.star` files and buck2's file watcher drops their events. For
        trees that are projects of their own, such as test fixtures whose
        targets only build in their own checkout. They add to the
        directories turnkey always ignores: the VCS's metadata (`.git`,
        `.jj`, `.hg`, `.sl`) and the devenv/direnv state (`.devenv`,
        `.direnv`).
      '';
    };

    prelude.path = mkOption {
      type = types.nullOr (types.either types.package types.path);
      default = null;
      description = ''
        A prelude to use instead of turnkey's, as a derivation or a path.
        Off the supported path: turnkey's prelude is part of the pinned
        buck2 release (docs/adr/0002-turnkey-owns-the-buck2-version.md),
        and test result caching is turned off, since turnkey can't know
        which of this prelude's test rules are cache-safe.
      '';
    };

    testCache = {
      enable = mkOption {
        type = types.bool;
        default = true;
        description = ''
          Run tests through turnkey's test runner, which can reuse
          recorded results for unchanged tests
          (docs/specs/test-result-caching.md). When false, or with a
          custom prelude.path, tests run under buck2's bundled runner.
        '';
      };

      endpoint = mkOption {
        type = types.nullOr types.str;
        default = null;
        example = "grpc://cache.example.com:443";
        description = ''
          A remote Remote Execution API cache to reuse test results
          from, as grpc://host:port. When null (the default), tk manages
          a local cache on this machine. With a remote endpoint, tk
          starts no local cache and only reuses results from it, never
          recording: who may write to a shared cache is not decided yet.
        '';
      };

      tls = mkOption {
        type = types.bool;
        default = true;
        description = "Whether to connect to a remote `endpoint` over TLS. The local cache never uses TLS.";
      };
    };

    welcomeMessage = mkOption {
      type = types.nullOr types.str;
      default = null;
      example = "Welcome to MyProject turnkey shell";
      description = ''
        Custom welcome message to display when entering the shell.
        If null (default), no welcome message is shown.
      '';
    };

    quiet = mkOption {
      type = types.bool;
      default = true;
      description = ''
        Suppress verbose shell entry messages.
        Set TURNKEY_VERBOSE=1 in your environment to see verbose output.
      '';
    };

    # ==========================================================================
    # Go language support
    # ==========================================================================
    go = {
      enable = mkOption {
        type = types.bool;
        default = true;
        description = "Enable Go dependency management for Buck2";
      };

      cell = mkOption {
        type = types.nullOr types.package;
        default = null;
        description = ''
          Nix derivation containing the Go dependencies cell.
          When set, a 'godeps' cell will be added to .buckconfig
          and symlinked to .turnkey/godeps.

          Prefer using depsFile instead for declarative configuration.
        '';
      };

      depsFile = mkOption {
        type = types.nullOr (types.either types.path types.str);
        default = null;
        example = lib.literalExpression "./.turnkey/go-deps.toml";
        description = ''
          Path to go-deps.toml file declaring Go dependencies.
          When set, turnkey will build the godeps cell automatically.

          Recommended: use ./.turnkey/go-deps.toml with the turnkey .envrc
          pattern, which auto-generates the file to the Nix store before
          flake evaluation. The .turnkey/ directory should be gitignored.
        '';
      };

      modFile = mkOption {
        type = types.str;
        default = "go.mod";
        description = ''
          Relative path to go.mod file (for staleness checking and regeneration).
        '';
      };

      sumFile = mkOption {
        type = types.str;
        default = "go.sum";
        description = ''
          Relative path to go.sum file (for staleness checking and regeneration).
        '';
      };

      allowedBuildTags = mkOption {
        type = types.listOf (types.strMatching "[A-Za-z0-9_.]+");
        default = [ ];
        example = [ "integration" ];
        description = ''
          The Go build tags a target can be built with. It is the single
          source of `.buckconfig`'s `go.allowed_build_tags`, which the
          prelude requires for a `build_tags` attribute and turns into the
          `prelude//go/tags/constraints:<tag>` constraints, and of rules
          sync's list: a library's imports that depend on one of these tags
          are written as a `select()` on its constraint. The toolchains
          cell defines the settings combining them with the platform, one
          per combination, so keep the list short.
        '';
      };

      autoRegenerate = removedRegeneration "autoRegenerate";
      generateOnShellEntry = removedRegeneration "generateOnShellEntry";
    };

    # ==========================================================================
    # Rust language support
    # ==========================================================================
    rust = {
      enable = mkOption {
        type = types.bool;
        default = true;
        description = "Enable Rust dependency management for Buck2";
      };

      cell = mkOption {
        type = types.nullOr types.package;
        default = null;
        description = ''
          Nix derivation containing the Rust dependencies cell.
          When set, a 'rustdeps' cell will be added to .buckconfig
          and symlinked to .turnkey/rustdeps.

          Prefer using depsFile instead for declarative configuration.
        '';
      };

      depsFile = mkOption {
        type = types.nullOr (types.either types.path types.str);
        default = null;
        example = lib.literalExpression "./rust-deps.toml";
        description = ''
          Path to rust-deps.toml file declaring Rust crate dependencies.
          When set, turnkey builds the rustdeps cell from it: one package per
          crate, which tk materialize lays out in .turnkey/rustdeps
          (docs/adr/0004-deps-cells-are-write-once-directories.md).
        '';
      };

      cargoTomlFile = mkOption {
        type = types.str;
        default = "Cargo.toml";
        description = ''
          Relative path to Cargo.toml file (for staleness checking and regeneration).
        '';
      };

      cargoLockFile = mkOption {
        type = types.str;
        default = "Cargo.lock";
        description = ''
          Relative path to Cargo.lock file (for staleness checking and regeneration).
        '';
      };

      featuresFile = removedOption "rust.featuresFile" "rust-features.toml is retired: each crate's features are the ones cargo resolves for your Cargo.toml files (docs/adr/0005-rust-resolution-comes-from-cargo-metadata.md). Ask for a feature in the member's Cargo.toml instead, then remove the option and the file; see docs/user-manual/src/reference/upgrading.md.";

      rustcFlagsRegistry = removedFixups "rustcFlagsRegistry";
      buildScriptFixups = removedFixups "buildScriptFixups";
    };

    # ==========================================================================
    # Python language support
    # ==========================================================================
    python = {
      enable = mkOption {
        type = types.bool;
        default = true;
        description = "Enable Python dependency management for Buck2";
      };

      cell = mkOption {
        type = types.nullOr types.package;
        default = null;
        description = ''
          Nix derivation containing the Python dependencies cell.
          When set, a 'pydeps' cell will be added to .buckconfig
          and symlinked to .turnkey/pydeps.

          Prefer using depsFile instead for declarative configuration.
        '';
      };

      depsFile = mkOption {
        type = types.nullOr (types.either types.path types.str);
        default = null;
        example = lib.literalExpression "./python-deps.toml";
        description = ''
          Path to python-deps.toml file declaring Python package dependencies.
          When set, turnkey will build the pydeps cell automatically.
        '';
      };

      pyprojectFile = mkOption {
        type = types.str;
        default = "pyproject.toml";
        description = ''
          Relative path to pyproject.toml file (for staleness checking and regeneration).
        '';
      };

      lockFile = mkOption {
        type = types.nullOr types.str;
        default = null;
        example = "pylock.toml";
        description = ''
          Relative path to Python lock file (pylock.toml or requirements.txt).
          If set, this is used as the source for staleness checking.
          If null, pyproject.toml is used as the source.
        '';
      };

      uvLockFile = mkOption {
        type = types.nullOr types.str;
        default = null;
        example = "uv.lock";
        description = ''
          Relative path to the uv lock that `lockFile` is exported from.
          When set, `tk sync` first re-exports `lockFile` (a PEP 751
          pylock.toml) with `uv export --all-packages --no-dev` whenever
          the uv lock or pyproject.toml changes, then regenerates the deps
          file from it. Requires `lockFile`.
        '';
      };
    };

    # ==========================================================================
    # JavaScript/TypeScript language support
    # ==========================================================================
    javascript = {
      enable = mkOption {
        type = types.bool;
        default = true;
        description = "Enable JavaScript/TypeScript dependency management for Buck2";
      };

      cell = mkOption {
        type = types.nullOr types.package;
        default = null;
        description = ''
          Nix derivation containing the JavaScript dependencies cell: a
          cell index (ADR 0004), which tk materializes at .turnkey/jsdeps.
          When set, a 'jsdeps' cell will be added to .buckconfig.

          Prefer using depsFile instead for declarative configuration.
        '';
      };

      depsFile = mkOption {
        type = types.nullOr (types.either types.path types.str);
        default = null;
        example = lib.literalExpression "./js-deps.toml";
        description = ''
          Path to js-deps.toml file declaring JavaScript package dependencies.
          When set, turnkey will build the jsdeps cell automatically.
        '';
      };

      lockFile = mkOption {
        type = types.str;
        default = "pnpm-lock.yaml";
        description = ''
          Relative path to pnpm-lock.yaml file (for staleness checking and regeneration).
        '';
      };

      includeDevDependencies = mkOption {
        type = types.bool;
        default = false;
        description = ''
          Include dev dependencies when generating js-deps.toml.
          Passed as --include-dev to jsdeps-gen.
        '';
      };

      tarballs = mkOption {
        type = types.attrsOf types.path;
        default = { };
        example = lib.literalExpression ''
          {
            "http://localhost:4873/-/acme-utils-1.0.0.tgz" = ./registry/acme-utils-1.0.0.tgz;
          }
        '';
        description = ''
          npm tarballs kept in the project, by the URL pnpm-lock.yaml records
          for them. A locked package whose tarball URL is listed is read from
          the file instead of fetched, and the file must match the package's
          integrity. For packages from a registry Nix can't fetch from, such
          as a local one served only while locking.
        '';
      };
    };

    # ==========================================================================
    # Solidity language support
    # ==========================================================================
    solidity = {
      enable = mkOption {
        type = types.bool;
        default = true;
        description = "Enable Solidity dependency management for Buck2";
      };

      cell = mkOption {
        type = types.nullOr types.package;
        default = null;
        description = ''
          Nix derivation containing the Solidity dependencies cell.
          When set, a 'soldeps' cell will be added to .buckconfig
          and symlinked to .turnkey/soldeps.

          Prefer using depsFile instead for declarative configuration.
        '';
      };

      depsFile = mkOption {
        type = types.nullOr (types.either types.path types.str);
        default = null;
        example = lib.literalExpression "./solidity-deps.toml";
        description = ''
          Path to solidity-deps.toml file declaring Solidity dependencies.
          When set, turnkey will build the soldeps cell automatically.
        '';
      };

      foundryTomlFile = mkOption {
        type = types.str;
        default = "foundry.toml";
        description = ''
          Relative path to foundry.toml file (for staleness checking and regeneration).
          The Buck2 Solidity rules need it at the repository root, the single
          root foundry.toml layout; evaluation fails otherwise.
        '';
      };

      packageJsonFile = mkOption {
        type = types.str;
        default = "package.json";
        description = ''
          Relative path to the package.json declaring npm Solidity packages
          (e.g. @openzeppelin/contracts), for staleness checking and regeneration.
        '';
      };

      pnpmLockFile = mkOption {
        type = types.str;
        default = "pnpm-lock.yaml";
        description = ''
          Relative path to the pnpm-lock.yaml pinning the npm Solidity packages'
          versions and integrity hashes, for staleness checking and regeneration.
        '';
      };
    };

    # ==========================================================================
    # rules.star synchronization
    # ==========================================================================
    rules = {
      enabled = mkOption {
        type = types.bool;
        default = false;
        description = ''
          Enable automatic rules.star synchronization before Buck2 commands.

          When enabled, tk will check rules.star files for staleness and
          update them automatically (if auto_sync is true) or warn (if false).

          Use --no-rules-sync to skip this check, or --strict-rules for CI.
        '';
      };

      autoSync = mkOption {
        type = types.bool;
        default = true;
        description = ''
          Automatically update stale rules.star files.

          When true (default), stale rules.star files are updated before build.
          When false, tk only warns about stale files.
        '';
      };

      strict = mkOption {
        type = types.bool;
        default = false;
        description = ''
          Fail if rules.star files would change (CI mode).

          When true, tk will exit with error if any rules.star file needs updating.
          This is useful for CI to ensure rules.star files are committed up-to-date.

          Can also be enabled per-invocation with --strict-rules flag.
        '';
      };

      go.internalPrefix = removedRulesGo "internalPrefix";
      go.externalCell = removedRulesGo "externalCell";
    };

    # ==========================================================================
    # mdbook configuration
    # ==========================================================================
    mdbook = {
      preprocessors = mkOption {
        type = types.listOf types.package;
        default = [ ];
        example = lib.literalExpression "[ pkgs.mdbook-admonish pkgs.mdbook-mermaid ]";
        description = ''
          List of mdbook preprocessor packages to make available during
          mdbook builds. Their bin/ directories are added to PATH.
        '';
      };
    };

    # ==========================================================================
    # Pre-commit hook configuration (tk options)
    # ==========================================================================
    tk = {
      aliasBuck2 = mkOption {
        type = types.bool;
        default = true;
        description = ''
          Alias buck2 to tk in the devenv shell.
        '';
      };

      syncOnShellEntry = mkOption {
        type = types.bool;
        default = true;
        description = ''
          Run `tk sync` automatically when entering the devenv shell.
        '';
      };

      preCommitCheck = mkOption {
        type = types.bool;
        default = true;
        description = ''
          Add a pre-commit hook that runs `tk check` before commits.
        '';
      };

      rustEditionCheck = mkOption {
        type = types.bool;
        default = false;
        description = ''
          Add a pre-commit hook that verifies Rust edition alignment.
        '';
      };

      monorepoDepCheck = mkOption {
        type = types.bool;
        default = false;
        description = ''
          Add a pre-commit hook that verifies monorepo dependency rules.
        '';
      };

      jsTestConfigCheck = mkOption {
        type = types.bool;
        default = false;
        description = ''
          Add a pre-commit hook that verifies Jest/Vitest/Biome configs
          properly exclude buck-out directories.
        '';
      };

      userPatchesDir = mkOption {
        type = types.nullOr types.path;
        default = null;
        example = lib.literalExpression "./.turnkey/patches";
        description = ''
          Path to directory containing user patches from the FUSE edit layer.
          Patches in subdirectories named after cells (e.g., patches/rustdeps/,
          patches/godeps/) will be applied during cell builds.

          Patch files use unified diff format with paths like a/vendor/... and b/vendor/...
          Generated by `tk compose patch` from FUSE edit overlay. A patch that
          doesn't apply fails the cell's build.
        '';
      };

      foundryConfigCheck = mkOption {
        type = types.bool;
        default = false;
        description = ''
          Add a pre-commit hook that checks the repository's foundry.toml:
          there is at most one, at the root, and it sets no solc or
          solc_version (the compiler comes from the toolchain, through
          FOUNDRY_SOLC).
        '';
      };

      sourceCoverageCheck = mkOption {
        type = types.bool;
        default = false;
        description = ''
          Add a pre-commit hook that validates all source files are covered by
          Buck2 targets in rules.star files.
        '';
      };

      sourceScope = mkOption {
        type = types.str;
        default = ".";
        description = ''
          Directory scope for source coverage checking.
          Default is "." (entire repository).
        '';
      };
    };
  };
}
