# The platforms turnkey builds for (the buck2.platforms option), as Buck2
# sees them.
#
# Pure. A platform is a Nix system (e.g. "aarch64-darwin"); Buck2 names it by
# the values of its os and cpu constraints (config//os:macos,
# config//cpu:arm64). Rules sync (through .turnkey/sync.toml) and the cell
# generators get the platforms from here, and the toolchains cell defines
# one combined config_setting per platform (settingsBuckFile), which a
# select() uses when deps differ by CPU within one OS.
{ lib }:

let
  # Nix's names for the parts of a system, in Buck2's
  cpus = {
    x86_64 = "x86_64";
    aarch64 = "arm64";
  };
  oses = {
    linux = "linux";
    darwin = "macos";
  };

  # "aarch64-darwin" -> { system = "aarch64-darwin"; os = "macos"; cpu = "arm64"; }
  fromSystem =
    system:
    let
      parts = lib.splitString "-" system;
      cpu = builtins.head parts;
      os = lib.last parts;
    in
    if builtins.length parts != 2 || !(cpus ? ${cpu}) || !(oses ? ${os}) then
      throw "turnkey: buck2.platforms: ${system} is not a system turnkey knows how to name in Buck2 (${lib.concatStringsSep ", " (lib.attrNames cpus)} on ${lib.concatStringsSep ", " (lib.attrNames oses)})"
    else
      {
        inherit system;
        os = oses.${os};
        cpu = cpus.${cpu};
      };
in
{
  inherit fromSystem;

  # The Buck2 package of the combined config_settings, in the toolchains
  # cell, and the name of each: "<os>-<cpu>"
  settingsPackage = "toolchains//conditions";
  settingName = platform: "${platform.os}-${platform.cpu}";

  # The combined config_settings' BUCK file, for platforms (fromSystem's)
  settingsBuckFile =
    platforms:
    ''
      # Generated by turnkey - do not edit manually
      #
      # One config_setting per platform turnkey builds for (buck2.platforms),
      # combining its OS and CPU. A select() uses one when deps differ by CPU
      # within one OS; deps that differ only by OS use config//os:<os>.
    ''
    + lib.concatMapStrings (platform: ''

      config_setting(
          name = "${platform.os}-${platform.cpu}",
          constraint_values = [
              "prelude//os/constraints:os[${platform.os}]",
              "prelude//cpu/constraints:cpu[${platform.cpu}]",
          ],
          visibility = ["PUBLIC"],
      )
    '') platforms;
}
