# Python dependencies cell builder
#
# Reads a python-deps.toml file and builds a Buck2 cell containing
# all Python package dependencies with BUCK files for python_library targets.
#
# The TOML file format:
#   [deps.package-name]
#   version = "1.0.0"
#   hash = "sha256-..."
#   url = "https://files.pythonhosted.org/packages/.../package-1.0.0.tar.gz"
#
# This allows downstream repos to declare deps in pure data files.

{ pkgs, lib, depsFile }:

let
  # Parse the TOML file
  depsToml = builtins.fromTOML (builtins.readFile depsFile);

  # Convert TOML deps to registry format
  registry = lib.mapAttrs (pkgName: dep: {
    inherit (dep) version;
    src = fetchPackage pkgName dep;
  }) (depsToml.deps or {});

  # Fetch package from PyPI
  fetchPackage = pkgName: dep:
    pkgs.fetchzip {
      url = dep.url;
      sha256 = dep.hash;
      extension = "tar.gz";
    };

  # Generate BUCK file content for a Python package
  generateBuckFile = pkgName: dep:
    ''
      # Auto-generated by turnkey python-deps-cell
      load("@prelude//:rules.bzl", "python_library")

      python_library(
          name = "${pkgName}",
          srcs = glob(["**/*.py"]),
          base_module = "",
          visibility = ["PUBLIC"],
      )
    '';

  # Generate shell commands to set up one package
  setupPackage = pkgName: dep:
    let
      vendorPath = "vendor/${pkgName}";
    in
    ''
      # Set up ${pkgName}
      mkdir -p $out/${vendorPath}
      cp -r ${dep.src}/* $out/${vendorPath}/
      chmod -R u+w $out/${vendorPath}

      # Generate BUCK file
      cat > $out/${vendorPath}/BUCK << 'BUCK'
      ${generateBuckFile pkgName dep}
      BUCK
    '';

  # All setup commands
  allSetupCommands = lib.concatStringsSep "\n" (
    lib.mapAttrsToList setupPackage registry
  );

in
pkgs.runCommand "python-deps-cell" {} ''
  mkdir -p $out/vendor

  # Set up all package sources and generate BUCK files
  ${allSetupCommands}

  # Generate cell .buckconfig
  cat > $out/.buckconfig << 'BUCKCONFIG'
  [cells]
      pydeps = .
      prelude = prelude

  [buildfile]
      name = BUCK
  BUCKCONFIG

  echo "Generated pydeps cell with ${toString (lib.length (lib.attrNames registry))} packages"
''
