# Rust dependencies cell builder using reindeer
#
# Uses Facebook's reindeer tool to generate proper Buck2 build rules
# from Cargo.toml/Cargo.lock, handling all complex cases like:
# - Inter-crate dependencies
# - Build scripts (via fixups)
# - Features
# - proc-macro crates
#
# Inputs:
#   cargoLock: Path to Cargo.lock (used to extract dependencies)
#   cargoVendorHash: Hash of vendored dependencies (for reproducibility)
#
# The generated cell contains a single BUCK file with all crate rules.
# Crates are downloaded via http_archive at build time (not vendored).

{ pkgs, lib, cargoLock, cargoVendorHash ? lib.fakeHash }:

let
  # Parse Cargo.lock to extract all packages
  lockContent = builtins.readFile cargoLock;
  lockData = builtins.fromTOML lockContent;
  packages = lockData.package or [];

  # Filter to only crates.io packages (have a source field)
  # Local workspace packages don't have a source field
  cratesIoPackages = builtins.filter (p: p ? source) packages;

  # Deduplicate packages by name, keeping highest version
  # Cargo.lock can have multiple versions of the same crate
  packagesByName = lib.foldl' (acc: pkg:
    let
      name = pkg.name;
      existing = acc.${name} or null;
      # Simple version comparison - take higher version
      shouldReplace = existing == null ||
        (builtins.compareVersions pkg.version existing.version) > 0;
    in
    if shouldReplace then acc // { ${name} = pkg; } else acc
  ) {} cratesIoPackages;

  # Build a dependencies list for the synthetic Cargo.toml
  # Format: name = "version"
  depsToml = lib.concatMapStringsSep "\n" (name:
    let
      pkg = packagesByName.${name};
    in
    ''${name} = "=${pkg.version}"''
  ) (builtins.filter (n: n != "turnkey-deps") (lib.attrNames packagesByName));

  # Create synthetic Cargo.toml with all dependencies
  syntheticCargoToml = pkgs.writeText "Cargo.toml" ''
    # Synthetic Cargo.toml generated by rust-deps-cell-reindeer.nix
    # This is not a real project - just used to generate Buck2 rules

    [package]
    name = "turnkey-deps"
    version = "0.0.0"
    edition = "2021"

    [dependencies]
    ${depsToml}
  '';

  # Create a minimal lib.rs for the synthetic package
  dummyLibRs = pkgs.writeText "lib.rs" "// dummy";

  # Reindeer configuration
  reindeerConfig = pkgs.writeText "reindeer.toml" ''
    # Generated by turnkey rust-deps-cell-reindeer.nix

    # Use vendored sources
    vendor = true

    # Provide Cargo environment variables to crates
    cargo_env = true

    [buck]
    file_name = "BUCK"
  '';

  # Vendor dependencies as a fixed-output derivation (allows network access)
  vendoredDeps = pkgs.stdenv.mkDerivation {
    name = "rust-deps-vendored";

    nativeBuildInputs = [ pkgs.cargo pkgs.cacert ];

    dontUnpack = true;
    dontFixup = true;  # Don't patch shebangs - would add store references

    buildPhase = ''
      # Set up workspace
      mkdir -p $TMPDIR/work/src
      cp ${syntheticCargoToml} $TMPDIR/work/Cargo.toml
      cp ${dummyLibRs} $TMPDIR/work/src/lib.rs

      cd $TMPDIR/work

      # Vendor all dependencies (this will generate a Cargo.lock)
      export HOME=$TMPDIR
      export SSL_CERT_FILE=${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt
      cargo vendor vendor
    '';

    installPhase = ''
      mkdir -p $out
      cp -r $TMPDIR/work/vendor $out/
      cp $TMPDIR/work/Cargo.lock $out/
      cp $TMPDIR/work/Cargo.toml $out/
    '';

    # Fixed-output derivation - allows network access
    outputHashMode = "recursive";
    outputHashAlgo = "sha256";
    outputHash = cargoVendorHash;
  };

  # Common fixups for crates with build scripts
  # These tell reindeer to skip build scripts that just do version detection
  fixupsDir = pkgs.runCommand "reindeer-fixups" {} ''
    mkdir -p $out

    # serde - build script just does version detection
    mkdir -p $out/serde
    echo 'buildscript.run = false' > $out/serde/fixups.toml

    # serde_core - same as serde
    mkdir -p $out/serde_core
    echo 'buildscript.run = false' > $out/serde_core/fixups.toml

    # serde_json - build script just does version detection
    mkdir -p $out/serde_json
    echo 'buildscript.run = false' > $out/serde_json/fixups.toml

    # anyhow - build script for backtrace detection
    mkdir -p $out/anyhow
    echo 'buildscript.run = false' > $out/anyhow/fixups.toml

    # proc-macro2 - build script for feature detection
    mkdir -p $out/proc-macro2
    echo 'buildscript.run = false' > $out/proc-macro2/fixups.toml

    # quote - build script for feature detection
    mkdir -p $out/quote
    echo 'buildscript.run = false' > $out/quote/fixups.toml

    # libc - build script for cfg detection
    mkdir -p $out/libc
    echo 'buildscript.run = false' > $out/libc/fixups.toml

    # num-traits - build script for feature detection
    mkdir -p $out/num-traits
    echo 'buildscript.run = false' > $out/num-traits/fixups.toml

    # typenum - build script generates type definitions
    mkdir -p $out/typenum
    echo 'buildscript.run = false' > $out/typenum/fixups.toml

    # generic-array - build script
    mkdir -p $out/generic-array
    echo 'buildscript.run = false' > $out/generic-array/fixups.toml

    # getrandom - build script
    mkdir -p $out/getrandom
    echo 'buildscript.run = false' > $out/getrandom/fixups.toml

    # crc32fast - build script
    mkdir -p $out/crc32fast
    echo 'buildscript.run = false' > $out/crc32fast/fixups.toml

    # httparse - build script
    mkdir -p $out/httparse
    echo 'buildscript.run = false' > $out/httparse/fixups.toml

    # rustls - build script
    mkdir -p $out/rustls
    echo 'buildscript.run = false' > $out/rustls/fixups.toml

    # rustix - build script
    mkdir -p $out/rustix
    echo 'buildscript.run = false' > $out/rustix/fixups.toml

    # ring - complex build script (may need more work)
    mkdir -p $out/ring
    echo 'buildscript.run = false' > $out/ring/fixups.toml

    # zmij - build script
    mkdir -p $out/zmij
    echo 'buildscript.run = false' > $out/zmij/fixups.toml

    # icu_* data crates - build scripts
    mkdir -p $out/icu_normalizer_data
    echo 'buildscript.run = false' > $out/icu_normalizer_data/fixups.toml
    mkdir -p $out/icu_properties_data
    echo 'buildscript.run = false' > $out/icu_properties_data/fixups.toml

    # windows_* - build scripts (all variants)
    for crate in windows_x86_64_gnu windows_x86_64_msvc windows_x86_64_gnullvm \
                 windows_i686_gnu windows_i686_msvc windows_i686_gnullvm \
                 windows_aarch64_msvc windows_aarch64_gnullvm; do
      mkdir -p $out/$crate
      echo 'buildscript.run = false' > $out/$crate/fixups.toml
    done

    # More common crates with build scripts that just do version detection
    for crate in thiserror rustversion wasm-bindgen wasm-bindgen-shared \
                 wasm-encoder wasmparser wit-bindgen wit-bindgen-rust \
                 wit-bindgen-rust-macro crossbeam-utils prettyplease \
                 iana-time-zone-haiku aws-lc-rs aws-lc-sys; do
      mkdir -p $out/$crate
      echo 'buildscript.run = false' > $out/$crate/fixups.toml
    done
  '';

  # Build the rustdeps cell
  rustdepsCell = pkgs.stdenv.mkDerivation {
    name = "rust-deps-cell-reindeer";

    dontUnpack = true;

    nativeBuildInputs = [
      pkgs.cargo
      pkgs.rustc
      pkgs.reindeer
    ];

    buildPhase = ''
      # Store the build root directory
      BUILD_ROOT=$PWD
      WORK=$BUILD_ROOT/work

      # Set up working directory using vendored deps
      mkdir -p $WORK/src
      cp ${vendoredDeps}/Cargo.toml $WORK/
      cp ${vendoredDeps}/Cargo.lock $WORK/
      cp ${dummyLibRs} $WORK/src/lib.rs
      cp ${reindeerConfig} $WORK/reindeer.toml

      # Copy vendored deps
      cp -r ${vendoredDeps}/vendor $WORK/

      # Copy fixups
      cp -r ${fixupsDir} $WORK/fixups

      # Create .cargo/config.toml to use vendored sources
      mkdir -p $WORK/.cargo
      cat > $WORK/.cargo/config.toml << 'EOF'
      [source.crates-io]
      replace-with = "vendored-sources"

      [source.vendored-sources]
      directory = "vendor"
      EOF

      cd $WORK

      # Run reindeer to generate BUCK file (offline mode via vendored sources)
      echo "Generating BUCK rules with reindeer..."
      reindeer buckify 2>&1 || {
        echo "Warning: reindeer had warnings, continuing..."
      }

      # Check that BUCK file was generated
      if [ ! -f BUCK ]; then
        echo "ERROR: reindeer did not generate BUCK file"
        ls -la
        exit 1
      fi

      echo "Generated BUCK file with $(grep -c 'cargo.rust_library' BUCK || echo 0) crate rules"

      # Return to build root for installPhase
      cd $BUILD_ROOT
    '';

    installPhase = ''
      BUILD_ROOT=$PWD
      WORK=$BUILD_ROOT/work

      mkdir -p $out

      # Copy the vendor directory with all crate sources
      cp -r $WORK/vendor $out/
      chmod -R u+w $out/vendor

      # Remove tests and examples directories - they confuse Buck2's crate_root detection
      # The prelude scans the filesystem for lib.rs files, not just the srcs list
      find $out/vendor -type d \( -name tests -o -name examples -o -name benches \) -exec rm -rf {} + 2>/dev/null || true

      # Post-process the reindeer BUCK file to create per-crate BUCK files
      # Reindeer generates a single BUCK file, but we need individual files
      # for compatibility with rustdeps//vendor/<crate>:<crate> target paths
      ${pkgs.python3}/bin/python3 ${./split-reindeer-buck.py} \
        "$WORK/BUCK" \
        "$out/vendor"

      # Create root BUCK file with re-exports for rustdeps//:crate paths
      echo '# Re-exports for rustdeps//:crate paths' > "$out/BUCK"
      echo 'load("@prelude//rust:cargo_package.bzl", "cargo")' >> "$out/BUCK"
      echo "" >> "$out/BUCK"

      for crate_dir in $out/vendor/*/; do
        crate_name=$(basename "$crate_dir")
        echo "alias(name = \"$crate_name\", actual = \"//vendor/$crate_name:$crate_name\", visibility = [\"PUBLIC\"])" >> "$out/BUCK"
      done

      # Generate cell .buckconfig
      cat > $out/.buckconfig << 'BUCKCONFIG'
[cells]
    rustdeps = .
    prelude = prelude

[buildfile]
    name = BUCK
BUCKCONFIG

      echo "Generated rustdeps cell with reindeer ($(ls $out/vendor | wc -l) crates)"
    '';
  };

in
rustdepsCell
