# Rust dependencies cell builder using reindeer
#
# Uses Facebook's reindeer tool to generate proper Buck2 build rules
# from Cargo.toml/Cargo.lock, handling all complex cases like:
# - Inter-crate dependencies
# - Build scripts
# - Features
# - Multiple crate roots
#
# Inputs:
#   cargoToml: Path to Cargo.toml
#   cargoLock: Path to Cargo.lock
#
# This replaces the simpler rust-deps-cell.nix approach which generated
# incomplete BUCK files without dependency information.

{ pkgs, lib, cargoToml, cargoLock }:

let
  # Create a minimal reindeer.toml configuration
  reindeerConfig = pkgs.writeText "reindeer.toml" ''
    # Generated by turnkey rust-deps-cell-reindeer.nix
    vendor = true

    [buck]
    file_name = "BUCK"
  '';

  # Build the vendored deps cell with reindeer-generated BUCK files
  rustdepsCell = pkgs.stdenv.mkDerivation {
    name = "rust-deps-cell";

    # No source needed - we copy files in build phase
    dontUnpack = true;

    nativeBuildInputs = [
      pkgs.cargo
      pkgs.rustc
      pkgs.reindeer
    ];

    buildPhase = ''
      # Create working directory structure
      mkdir -p work/third-party

      # Copy Cargo files
      cp ${cargoToml} work/Cargo.toml
      cp ${cargoLock} work/Cargo.lock

      # Create reindeer config
      cp ${reindeerConfig} work/third-party/reindeer.toml

      # Create third-party Cargo.toml that references root workspace deps
      cat > work/third-party/Cargo.toml << 'EOF'
      [workspace]

      # This file is managed by reindeer
      EOF

      cd work

      # Vendor dependencies
      echo "Vendoring Rust dependencies..."
      cargo vendor third-party/vendor --locked

      # Generate BUCK files with reindeer
      echo "Generating BUCK files with reindeer..."
      cd third-party
      reindeer --third-party-dir . buckify || {
        echo "Warning: reindeer buckify had issues, continuing anyway"
      }
    '';

    installPhase = ''
      mkdir -p $out

      # Copy vendored crates with BUCK files
      cp -r work/third-party/vendor $out/

      # Generate cell .buckconfig
      cat > $out/.buckconfig << 'BUCKCONFIG'
      [cells]
          rustdeps = .
          prelude = prelude

      [buildfile]
          name = BUCK
      BUCKCONFIG

      echo "Generated rustdeps cell"
    '';
  };

in
rustdepsCell
