# Rust dependencies cell builder
#
# Reads a rust-deps.toml file and builds a Buck2 cell containing
# all crate dependencies with BUCK files for rust_library targets.
#
# The TOML file format:
#   [deps.crate-name]
#   version = "1.0.0"
#   hash = "sha256-..."
#   features = ["feature1", "feature2"]  # optional
#
# This allows downstream repos to declare deps in pure data files.

{ pkgs, lib, depsFile }:

let
  # Parse the TOML file
  depsToml = builtins.fromTOML (builtins.readFile depsFile);

  # Convert TOML deps to registry format
  registry = lib.mapAttrs (crateName: dep: {
    inherit (dep) version;
    features = dep.features or [];
    src = fetchCrate crateName dep;
  }) (depsToml.deps or {});

  # Fetch crate from crates.io
  fetchCrate = crateName: dep:
    pkgs.fetchzip {
      url = "https://crates.io/api/v1/crates/${crateName}/${dep.version}/download";
      sha256 = dep.hash;
      extension = "tar.gz";
    };

  # Generate BUCK file content for a crate
  generateBuckFile = crateName: dep:
    let
      # Find all .rs files (will be done at build time)
      visibility = ''["PUBLIC"]'';
    in
    ''
      # Auto-generated by turnkey rust-deps-cell
      load("@prelude//:rules.bzl", "rust_library")

      rust_library(
          name = "${crateName}",
          srcs = glob(["src/**/*.rs"]),
          edition = "2021",
          visibility = ${visibility},
      )
    '';

  # Generate shell commands to set up one crate
  setupCrate = crateName: dep:
    let
      vendorPath = "vendor/${crateName}";
    in
    ''
      # Set up ${crateName}
      mkdir -p $out/${vendorPath}
      cp -r ${dep.src}/* $out/${vendorPath}/
      chmod -R u+w $out/${vendorPath}

      # Generate BUCK file
      cat > $out/${vendorPath}/BUCK << 'BUCK'
      ${generateBuckFile crateName dep}
      BUCK
    '';

  # All setup commands
  allSetupCommands = lib.concatStringsSep "\n" (
    lib.mapAttrsToList setupCrate registry
  );

in
pkgs.runCommand "rust-deps-cell" {} ''
  mkdir -p $out/vendor

  # Set up all crate sources and generate BUCK files
  ${allSetupCommands}

  # Generate cell .buckconfig
  cat > $out/.buckconfig << 'BUCKCONFIG'
  [cells]
      rustdeps = .
      prelude = prelude

  [buildfile]
      name = BUCK
  BUCKCONFIG

  echo "Generated rustdeps cell with ${toString (lib.length (lib.attrNames registry))} crates"
''
