# Rust dependencies cell builder
#
# Reads a rust-deps.toml file and builds a Buck2 cell containing
# all crate dependencies with BUCK files for rust_library targets.
#
# The TOML file format (supports multiple versions of same crate):
#   [deps."crate-name@1.0.0"]
#   name = "crate-name"
#   version = "1.0.0"
#   hash = "sha256-..."
#   features = ["feature1", "feature2"]  # optional
#
# This allows downstream repos to declare deps in pure data files.

{ pkgs, lib, depsFile }:

let
  # Parse the TOML file
  depsToml = builtins.fromTOML (builtins.readFile depsFile);

  # Convert TOML deps to registry format
  # Key is "name@version", value contains name, version, hash
  registry = lib.mapAttrs (key: dep: {
    # Use explicit name field, fallback to parsing key for backwards compat
    crateName = dep.name or (lib.head (lib.splitString "@" key));
    inherit (dep) version;
    features = dep.features or [];
    src = fetchCrate (dep.name or (lib.head (lib.splitString "@" key))) dep;
  }) (depsToml.deps or {});

  # Fetch crate from crates.io
  fetchCrate = crateName: dep:
    pkgs.fetchzip {
      url = "https://crates.io/api/v1/crates/${crateName}/${dep.version}/download";
      sha256 = dep.hash;
      extension = "tar.gz";
    };

  # Generate BUCK file content for a crate
  # Uses versioned directory name to support multiple versions
  generateBuckFile = key: dep:
    let
      # Find all .rs files (will be done at build time)
      visibility = ''["PUBLIC"]'';
    in
    ''
      # Auto-generated by turnkey rust-deps-cell
      load("@prelude//:rules.bzl", "rust_library")

      rust_library(
          name = "${dep.crateName}",
          srcs = glob(["src/**/*.rs"]),
          edition = "2021",
          visibility = ${visibility},
      )
    '';

  # Generate shell commands to set up one crate
  # key is "name@version", dep contains crateName, version, src
  setupCrate = key: dep:
    let
      # Use key (name@version) as directory to support multiple versions
      vendorPath = "vendor/${key}";
    in
    ''
      # Set up ${key}
      mkdir -p $out/${vendorPath}
      cp -r ${dep.src}/* $out/${vendorPath}/
      chmod -R u+w $out/${vendorPath}

      # Generate BUCK file
      cat > $out/${vendorPath}/BUCK << 'BUCK'
      ${generateBuckFile key dep}
      BUCK
    '';

  # All setup commands
  allSetupCommands = lib.concatStringsSep "\n" (
    lib.mapAttrsToList setupCrate registry
  );

  # ==========================================================================
  # Semver utilities for version comparison
  # ==========================================================================

  # Parse semver string "1.2.3" or "1.2.3-pre" into { major, minor, patch, pre }
  # Returns null for unparseable versions
  parseSemver = version:
    let
      # Split off prerelease suffix if present (e.g., "1.0.0-alpha" -> ["1.0.0" "alpha"])
      preParts = lib.splitString "-" version;
      versionPart = lib.head preParts;
      prerelease = if lib.length preParts > 1 then lib.elemAt preParts 1 else null;

      # Split version into major.minor.patch
      parts = lib.splitString "." versionPart;
      major = lib.toInt (lib.elemAt parts 0);
      minor = if lib.length parts > 1 then lib.toInt (lib.elemAt parts 1) else 0;
      patch = if lib.length parts > 2 then lib.toInt (lib.elemAt parts 2) else 0;
    in
    { inherit major minor patch prerelease; };

  # Compare two parsed semver versions
  # Returns: -1 if a < b, 0 if a == b, 1 if a > b
  compareSemver = a: b:
    if a.major != b.major then
      (if a.major > b.major then 1 else -1)
    else if a.minor != b.minor then
      (if a.minor > b.minor then 1 else -1)
    else if a.patch != b.patch then
      (if a.patch > b.patch then 1 else -1)
    else
      # Prerelease versions are less than release versions
      # "1.0.0-alpha" < "1.0.0"
      if a.prerelease == null && b.prerelease != null then 1
      else if a.prerelease != null && b.prerelease == null then -1
      else if a.prerelease == null && b.prerelease == null then 0
      else builtins.compareVersions a.prerelease b.prerelease;

  # Compare version strings directly
  compareVersionStrings = a: b:
    compareSemver (parseSemver a) (parseSemver b);

  # Sort comparator for lib.sort (returns true if a should come before b)
  # We want descending order, so greater versions come first
  semverSortDesc = a: b:
    compareVersionStrings a.version b.version > 0;

  # ==========================================================================
  # Symlink generation with proper version selection
  # ==========================================================================

  # Group crates by unversioned name to create symlinks
  # This allows users to reference crates without version suffix
  cratesByName = lib.foldlAttrs (acc: key: dep:
    let
      name = dep.crateName;
      existing = acc.${name} or [];
    in
    acc // { ${name} = existing ++ [{ inherit key; version = dep.version; }]; }
  ) {} registry;

  # Generate symlink commands for unversioned references
  # When multiple versions exist, sort by semver and pick the greatest
  symlinkCommands = lib.concatStringsSep "\n" (
    lib.mapAttrsToList (name: versions:
      let
        # Sort versions by semver descending (greatest first)
        sorted = lib.sort semverSortDesc versions;
        # Pick the greatest version
        target = (lib.head sorted).key;
      in
      ''
        # Symlink ${name} -> ${target}
        ln -s "${target}" "$out/vendor/${name}"
      ''
    ) cratesByName
  );

in
pkgs.runCommand "rust-deps-cell" {} ''
  mkdir -p $out/vendor

  # Set up all crate sources and generate BUCK files
  ${allSetupCommands}

  # Create symlinks for unversioned crate references
  # Users can reference "rustdeps//vendor/itoa:itoa" instead of "rustdeps//vendor/itoa@1.0.17:itoa"
  ${symlinkCommands}

  # Generate cell .buckconfig
  cat > $out/.buckconfig << 'BUCKCONFIG'
  [cells]
      rustdeps = .
      prelude = prelude

  [buildfile]
      name = BUCK
  BUCKCONFIG

  echo "Generated rustdeps cell with ${toString (lib.length (lib.attrNames registry))} crates"
''
