# Solidity dependencies cell builder
#
# Reads a solidity-deps.toml file and builds a Buck2 cell containing
# all Solidity dependencies (npm and git) with rules.star files.
#
# The TOML file format (generated by soldeps-gen):
#   [meta]
#   generator = "soldeps-gen 0.1.0"
#
#   [[package]]
#   name = "forge-std"
#   version = "v1.8.0"
#   source = "git"
#   repo = "https://github.com/foundry-rs/forge-std"
#   rev = "v1.8.0"
#   remapping = "forge-std/="
#
#   [[package]]
#   name = "@openzeppelin/contracts"
#   version = "5.0.0"
#   source = "npm"
#   url = "https://registry.npmjs.org/@openzeppelin%2fcontracts/-/contracts-5.0.0.tgz"
#   integrity = "sha512-..."
#   remapping = "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/"
#
# This is a thin wrapper around the deps-cell library.

{ pkgs, lib, depsFile, cellName ? "soldeps" }:

let
  adapter = import ../lib/deps-cell/adapters/solidity.nix { inherit pkgs lib; };
in
adapter.mkSolDepsCell {
  inherit depsFile cellName;
}
