# .turnkey/sync.toml, the rules tk sync and tw follow.
#
# Pure: from the language records and the Buck2 options. Returns the
# [[deps]] rules (in the order tk sync runs them), the [[wrappers]] rules
# and the file's content. buck2.nix writes the content to the store and
# symlinks .turnkey/sync.toml to it; direnv's use_turnkey reads the rules;
# checks.buck2-generators and checks.language-records test them.
{ lib }:

{
  # nix/buck2/languages.nix
  languages,
  # The Buck2 options (nix/buck2/options.nix)
  buck2,
}:

let
  # Each language's sync rules, in language order
  syncRules = builtins.concatMap (language: language.syncRules buck2.${language.name}) languages;

  # What tw does for each wrapped tool: which of its commands can change the
  # language's files, and the sync rule to run when they do. Only languages
  # with sync rules get one, so a wrapper always names a rule that exists.
  wrapperRules = builtins.concatMap (
    language:
    let
      rule = language.wrapper.rule buck2.${language.name};
    in
    lib.optional
      (language ? wrapper && language.syncRules buck2.${language.name} != [ ] && rule != null)
      (
        {
          name = language.wrapper.tool;
          command = language.wrapper.tool;
        }
        // rule
      )
  ) languages;

  # Format a single rule as TOML
  formatSyncRule = rule: ''
    [[deps]]
    name = ${builtins.toJSON rule.name}
    sources = ${builtins.toJSON rule.sources}
    target = ${builtins.toJSON rule.target}
    generator = ${builtins.toJSON rule.generator}
  '';

  # Format a wrapper rule as TOML
  formatWrapperRule = rule: ''
    [[wrappers]]
    ${lib.concatStringsSep "\n" (lib.mapAttrsToList (k: v: "${k} = ${builtins.toJSON v}") rule)}
  '';

  # The complete sync.toml
  content = ''
    # Generated by turnkey - do not edit manually
    # This file configures tk sync to keep dependency files up-to-date.
    #
    # The [[deps]] and [[wrappers]] rules come from each enabled language
    # (turnkey's nix/buck2/languages.nix) and its buck2 options in your
    # flake.nix. tk sync runs the [[deps]] rules in this order.
    #
    # To customize, modify your flake.nix buck2 options.

    # Rules.star auto-sync configuration
    # When enabled, tk automatically updates rules.star deps before build commands.
    [rules]
    enabled = ${lib.boolToString buck2.rules.enabled}
    auto_sync = ${lib.boolToString buck2.rules.autoSync}
    strict = ${lib.boolToString buck2.rules.strict}

    [rules.go]
    internal_prefix = ${builtins.toJSON buck2.rules.go.internalPrefix}
    external_cell = ${builtins.toJSON buck2.rules.go.externalCell}

    ${lib.concatMapStringsSep "\n" formatSyncRule syncRules}
    ${lib.concatMapStringsSep "\n" formatWrapperRule wrapperRules}
  '';

in
{
  inherit content;
  rules = syncRules;
  wrappers = wrapperRules;
}
