# .turnkey/sync.toml, the rules tk sync and tw follow.
#
# From the language records and the Buck2 options. Returns the [[deps]]
# rules (in the order tk sync runs them), the [[wrappers]] rules, the file's
# value and the file, rendered from the value with pkgs.formats.toml.
# buck2.nix symlinks .turnkey/sync.toml to the file; direnv's use_turnkey
# reads the rules; checks.buck2-generators and checks.language-records test
# them.
{ pkgs, lib }:

{
  # nix/buck2/languages.nix
  languages,
  # The Buck2 options (nix/buck2/options.nix)
  buck2,
}:

let
  platforms = import ./platforms.nix { inherit lib; };

  # Each language's sync rules, in language order
  syncRules = builtins.concatMap (language: language.syncRules buck2.${language.name}) languages;

  # What tw does for each wrapped tool: which of its commands can change the
  # language's files, and the sync rule to run when they do. Only languages
  # with sync rules get one, so a wrapper always names a rule that exists.
  wrapperRules = builtins.concatMap (
    language:
    let
      rule = language.wrapper.rule buck2.${language.name};
    in
    lib.optional
      (language ? wrapper && language.syncRules buck2.${language.name} != [ ] && rule != null)
      (
        {
          name = language.wrapper.tool;
          command = language.wrapper.tool;
        }
        // rule
      )
  ) languages;

  # The complete sync.toml, as the value pkgs.formats.toml renders
  value = {
    # When enabled, tk updates rules.star deps before build commands
    rules = {
      enabled = buck2.rules.enabled;
      auto_sync = buck2.rules.autoSync;
      inherit (buck2.rules) strict;
    };

    # The platforms rules sync resolves deps for (buck2.platforms), and the
    # package of the combined <os>-<cpu> config_settings its select()s use
    conditions = platforms.conditions buck2.platforms // {
      go_tags = if buck2.go.enable then buck2.go.allowedBuildTags else [ ];
    };

    # Each language's cell and deps file, which rules sync maps the
    # language's external deps with. Every language has one, enabled or
    # not, as rules sync syncs every language's targets.
    languages = map (language: {
      inherit (language) name;
      cell = language.cellName;
      deps_file = language.depsFile buck2.${language.name};
    }) languages;

    deps = syncRules;
    wrappers = wrapperRules;
  };

  # What the file says before its value: TOML has no comments to render
  header = pkgs.writeText "turnkey.sync.toml.header" ''
    # Generated by turnkey - do not edit manually
    # This file configures tk sync to keep dependency files up-to-date.
    #
    # The [[languages]], and the [[deps]] and [[wrappers]] rules of each
    # enabled language, come from turnkey's language records
    # (nix/buck2/languages.nix) and the buck2 options in your flake.nix.
    # tk sync runs the [[deps]] rules in this order.
    #
    # To customize, modify your flake.nix buck2 options.

  '';

  file = pkgs.runCommand "turnkey.sync.toml" { } ''
    cat ${header} ${(pkgs.formats.toml { }).generate "sync.toml" value} > $out
  '';

in
{
  inherit value file;
  rules = syncRules;
  wrappers = wrapperRules;
}
