# The toolchains cell's content, from the declared toolchains.
#
# Pure: which Buck2 toolchains the cell defines (the declared ones with a
# mapping, their implicit dependencies and the always-included ones), what
# their actions need on PATH, and the cell's BUCK file. buck2.nix builds
# the cell from it; checks.buck2-generators tests it.
{ lib }:

{
  # nix/buck2/mappings.nix
  mappings,
  # name -> spec, as toolchain-declaration.nix reads them
  declaredToolchains,
  # name -> package, what a mapping's dynamicAttrs reads
  resolvedRegistry,
}:

let
  # Get toolchain names from the declaration file
  toolchainNames = builtins.attrNames declaredToolchains;

  # Filter to only Buck2-relevant toolchains (those with mappings and not skipped)
  buck2Toolchains = builtins.filter (
    name: mappings ? ${name} && !(mappings.${name}.skip or false)
  ) toolchainNames;

  # Collect all implicit dependencies transitively
  collectDeps =
    toolchains:
    let
      directDeps = builtins.concatMap (name: mappings.${name}.implicitDependencies or [ ]) toolchains;
      # Only include deps that have mappings and aren't skipped
      validDeps = builtins.filter (
        name: mappings ? ${name} && !(mappings.${name}.skip or false)
      ) directDeps;
      allDeps = lib.unique (toolchains ++ validDeps);
    in
    # Recurse until stable (handle transitive deps)
    if allDeps == toolchains then toolchains else collectDeps allDeps;

  # All toolchains including implicit dependencies
  allToolchains = collectDeps buck2Toolchains;

  # Add always-include toolchains (like genrule)
  alwaysIncluded = builtins.filter (name: mappings.${name}.alwaysInclude or false) (
    builtins.attrNames mappings
  );

  finalToolchains = lib.unique (allToolchains ++ alwaysIncluded);

  # Collect runtime dependencies from all active toolchains
  # These are packages that must be in PATH for Buck2 actions (e.g., clang for cxx)
  runtimeDeps = lib.unique (
    builtins.concatMap (name: mappings.${name}.runtimeDependencies or [ ]) finalToolchains
  );

  # Generate load statements for rules.star file
  generateLoads =
    toolchains:
    let
      # Collect all unique load statements
      loads = lib.unique (
        builtins.concatMap (
          name:
          map (t: {
            path = t.load;
            rule = t.rule;
          }) (mappings.${name}.targets or [ ])
        ) toolchains
      );
      # Group by load path for cleaner output
      byPath = lib.groupBy (l: l.path) loads;
      loadStmts = lib.mapAttrsToList (
        path: rules: ''load("${path}", ${lib.concatMapStringsSep ", " (r: ''"${r.rule}"'') rules})''
      ) byPath;
    in
    lib.concatStringsSep "\n" loadStmts;

  # Generate target instantiations for rules.star file
  generateTargets =
    toolchains:
    let
      targets = builtins.concatMap (
        name:
        map (
          t:
          let
            # Static attrs defined in the mapping
            staticAttrs = t.attrs or { };
            # Dynamic attrs resolved from registry (e.g., absolute paths to compilers)
            dynamicAttrs = if t ? dynamicAttrs then t.dynamicAttrs resolvedRegistry else { };
            # Merge: dynamic attrs override static attrs
            attrs = staticAttrs // dynamicAttrs;
            attrLines = [
              "    name = \"${t.name}\","
            ]
            ++ [ "    visibility = ${builtins.toJSON t.visibility}," ]
            ++ (lib.mapAttrsToList (k: v: "    ${k} = ${builtins.toJSON v},") attrs);
          in
          "${t.rule}(\n${lib.concatStringsSep "\n" attrLines}\n)"
        ) (mappings.${name}.targets or [ ])
      ) toolchains;
    in
    lib.concatStringsSep "\n\n" targets;

  # The complete rules.star file content
  buckFile = ''
    # Generated by turnkey - do not edit manually
    # Toolchains: ${lib.concatStringsSep ", " finalToolchains}

    ${generateLoads finalToolchains}

    ${generateTargets finalToolchains}
  '';

in
{
  toolchains = finalToolchains;
  inherit runtimeDeps buckFile;
}
