# The toolchains cell's content, from the declared toolchains.
#
# Pure: which Buck2 toolchains the cell defines (the declared ones with a
# mapping, their implicit dependencies and the always-included ones), what
# their actions need on PATH, and the cell's BUCK file. buck2.nix builds
# the cell from it; checks.buck2-generators tests it.
{ lib }:

{
  # nix/buck2/mappings.nix
  mappings,
  # name -> spec, as toolchain-declaration.nix reads them
  declaredToolchains,
  # name -> package, what a mapping's dynamicAttrs reads
  resolvedRegistry,
}:

let
  # Get toolchain names from the declaration file
  toolchainNames = builtins.attrNames declaredToolchains;

  # Filter to only Buck2-relevant toolchains (those with mappings and not skipped)
  buck2Toolchains = builtins.filter (
    name: mappings ? ${name} && !(mappings.${name}.skip or false)
  ) toolchainNames;

  # Collect all implicit dependencies transitively
  collectDeps =
    toolchains:
    let
      directDeps = builtins.concatMap (name: mappings.${name}.implicitDependencies or [ ]) toolchains;
      # Only include deps that have mappings and aren't skipped
      validDeps = builtins.filter (
        name: mappings ? ${name} && !(mappings.${name}.skip or false)
      ) directDeps;
      allDeps = lib.unique (toolchains ++ validDeps);
    in
    # Recurse until stable (handle transitive deps)
    if allDeps == toolchains then toolchains else collectDeps allDeps;

  # All toolchains including implicit dependencies
  allToolchains = collectDeps buck2Toolchains;

  # Add always-include toolchains (like genrule)
  alwaysIncluded = builtins.filter (name: mappings.${name}.alwaysInclude or false) (
    builtins.attrNames mappings
  );

  finalToolchains = lib.unique (allToolchains ++ alwaysIncluded);

  # Collect runtime dependencies from all active toolchains
  # These are packages that must be in PATH for Buck2 actions (e.g., clang for cxx)
  runtimeDeps = lib.unique (
    builtins.concatMap (name: mappings.${name}.runtimeDependencies or [ ]) finalToolchains
  );

  # Generate load statements for rules.star file
  generateLoads =
    toolchains:
    let
      # Collect all unique load statements
      loads = lib.unique (
        builtins.concatMap (
          name:
          map (t: {
            path = t.load;
            rule = t.rule;
          }) (mappings.${name}.targets or [ ])
        ) toolchains
      );
      # Group by load path for cleaner output
      byPath = lib.groupBy (l: l.path) loads;
      loadStmts = lib.mapAttrsToList (
        path: rules: ''load("${path}", ${lib.concatMapStringsSep ", " (r: ''"${r.rule}"'') rules})''
      ) byPath;
    in
    lib.concatStringsSep "\n" loadStmts;

  # Every target the cell defines, with its attrs resolved once: the BUCK file
  # renders them, and solcPath reads the solc target's
  cellTargets = builtins.concatMap (
    name:
    map (
      t:
      t
      // {
        # Static attrs from the mapping, overridden by the dynamic attrs
        # resolved from the registry (e.g., absolute paths to compilers)
        attrs = (t.attrs or { }) // (if t ? dynamicAttrs then t.dynamicAttrs resolvedRegistry else { });
      }
    ) (mappings.${name}.targets or [ ])
  ) finalToolchains;

  # Generate target instantiations for rules.star file
  generateTargets =
    targets:
    lib.concatStringsSep "\n\n" (
      map (
        t:
        let
          attrLines = [
            "    name = \"${t.name}\","
          ]
          ++ [ "    visibility = ${builtins.toJSON t.visibility}," ]
          ++ (lib.mapAttrsToList (k: v: "    ${k} = ${builtins.toJSON v},") t.attrs);
        in
        "${t.rule}(\n${lib.concatStringsSep "\n" attrLines}\n)"
      ) targets
    );

  # The solc the cell's solc target runs, for the dev shell's FOUNDRY_SOLC, or
  # null without one. Both solc and solidity-toolchain map to a target named
  # solc; declaring both would define it twice, so there is no solc to pick.
  solcPath =
    let
      solcTargets = builtins.filter (t: t.name == "solc") cellTargets;
    in
    if solcTargets == [ ] then
      null
    else if builtins.length solcTargets > 1 then
      throw "turnkey: both solc and solidity-toolchain are declared, and each defines the toolchains cell's solc target; declare one of them"
    else
      (builtins.head solcTargets).attrs.solc_path;

  # The complete rules.star file content
  buckFile = ''
    # Generated by turnkey - do not edit manually
    # Toolchains: ${lib.concatStringsSep ", " finalToolchains}

    ${generateLoads finalToolchains}

    ${generateTargets cellTargets}
  '';

in
{
  toolchains = finalToolchains;
  inherit runtimeDeps buckFile solcPath;
}
